# Preface {.unnumbered}

First Draft (version 0.9 = August 7th, 2018) Last Compiled: `r Sys.Date()`

**Online Textbook**: <https://crumplab.github.io/statistics/>

**Citation**: Crump, M. J. C., Navarro, D. J., & Suzuki, J. (2019, June 5). Answering Questions with Data (Textbook): Introductory Statistics for Psychology Students. https://doi.org/10.17605/OSF.IO/JZE52

## Important notes

This is a free textbook teaching introductory statistics for undergraduates in Psychology. This textbook is part of a larger OER course package for teaching undergraduate statistics in Psychology, including this textbook, a lab manual, and a course website. All of the materials are free and copiable, with source code maintained in Github repositories. The links below connect to various components of the project. The main OSF project link is <https://osf.io/3s68c/>.

### Textbook

-   website: <https://crumplab.github.io/statistics/>
-   OSF: <https://osf.io/jze52/>
-   Github: <https://github.com/CrumpLab/statistics>
-   DOI: 10.17605/OSF.IO/JZE52

### Lab Manual

-   website: <https://crumplab.github.io/statisticsLab/>
-   OSF: <https://osf.io/m2npj/>
-   Github: <https://github.com/CrumpLab/statisticsLab>
-   DOI: 10.17605/OSF.IO/M2NPJ

### Course website

-   website: <https://crumplab.github.io/psyc3400/>
-   OSF: <https://osf.io/awxu9/>
-   Github: <https://github.com/CrumpLab/psyc3400>
-   DOI: 10.17605/OSF.IO/AWXU9

All resources are released under a creative commons licence [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). Click the link to read more about the license, or read more below in the license section.

### Contributors

Team members contributing new content include, Matthew Crump, Alla Chavarga, Anjali Krishnan, Jeffrey Suzuki, and Stephen Volz. This textbook was primarily written by Matthew J. C. Crump. Jeff contributed the YouTube videos peppered throughout the textbook. All of Jeff's statistics videos are available on his Youtube channel: [Statistics Video playlist](https://www.youtube.com/playlist?list=PLKXdxQAT3tCvuex_E1ZnQYaw897ELUSaI).

Alla, Anjali, and Stephen wrote the lab manual exercises for SPSS, JAMOVI, and Excel. Matt Crump wrote the lab manual exercises for R.

Matt Crump wrote a free and copiable [course website](https://crumplab.github.io/psyc3400/), in R Markdown. The course website also contains slide decks for the lectures.

### Attributions

Two of the chapters were adapted from Danielle Navarro's wonderful (and bigger) free textbook, also licensed under the same creative commons license. The citation for that textbook is: Navarro, D. (2018). Learning statistics with R: A tutorial for psychology students and other beginners (version 0.6). The website is <https://compcogscisydney.org/learning-statistics-with-r/>

Chapter notes within the book are provided to indicate sections where material from Navarro was included. A short summary is here

**Chapter 1: Why statistics**, Adapted nearly verbatim with some editorial changes from Chapters 1 and 2, Navarro, D.

**Chapter 4: Probability, Sampling, and Estimation**, Adapted and expanded from Chapters 9 and 10, Navarro D.

### CC BY-SA 4.0 license

This license means that you are free to:

-   Share: copy and redistribute the material in any medium or format
-   Adapt: remix, transform, and build upon the material for any purpose, even commercially.

The licensor cannot revoke these freedoms as long as you follow the license terms.

Under the following terms:

-   Attribution: You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
-   ShareAlike: If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
-   No additional restrictions: You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

## Copying the textbook

This textbook was written in R-Studio, using R Markdown, and compiled into a web-book format using the bookdown package. In general, I thank the larger R community for all of the amazing tools they made, and for making those tools open, so that I could use them to make this thing.

All of the source code for compiling the book is available in the GitHub repository for this book:

<https://github.com/CrumpLab/statistics>

In principle, anybody could fork or otherwise download this repository. Load the Rproj file in R-studio, and then compile the entire book. Then, the individual .rmd files for each chapter could be edited for content and style to better suit your needs.

If you want to contribute to this version of the textbook, you could make pull requests on GitHub, or discuss issues and request on the issues tab.

### Acknowledgments

Thanks to the librarians at Brooklyn College of CUNY, especially Miriam Deutch, and Emily Fairey, for their support throughout the process. Thanks to CUNY for supporting OER development, and for the grant we received to develop this work. Thanks to Jenn Richler for letting me talk about statistics all summer long.

### Why we did this

Why write another statistics textbook, aren't there already loads of those? Yes, there are. We had a couple reasons. First, we would like to make R more accessible for the undergraduate population, and we wrote this textbook around the capabilities of R. The textbook was written entirely in R-Studio, and most of the examples have associated R-code. R is not much of a focus in the textbook, but there is an introduction to using R to solve data-analysis problems in the lab manual. Many instructors still use SPSS, Excel, or newer free GUIs like JAMOVI, so we also made lab exercises for each of those as well.

This is a mildly opinionated, non-traditional introduction to statistics. It acknowledges some of the major ideas from traditional frequentist approaches, and some Bayesian approaches. Much of the conceptual foundation is rooted in simulations that can be conducted in R. We use some formulas, but mostly explain things without formulas. The textbook was written with math-phobia in mind, and attempts to reduce the phobia associated with arithmetic computations. There are many things missing that should probably be added. We will do our best to add necessary things as we update the textbook.
