--- 
title: "Answering questions with data"
author: "Matthew J. C. Crump"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: 
  bookdown::gitbook:
    includes:
      in_header: includeme.html
    css: tufte.css
    fontsettings:
      theme: white
      family: sans
      size: 1
documentclass: book
bibliography: [book.bib, packages.bib, MyLibrary.bib]
biblio-style: apalike
link-citations: yes
#github-repo: rstudio/bookdown-demo
description: "An introductory statistics textbook for psychology students"
---

# Preface {-}

This textbook is intended for psychology students with little to no background in statistics, and who may be afraid of math. Concepts are integrated with tutorials on using the free statistics software R. The goal is to train students to be able to organize and analyze data common to research in psychology using r (e.g., learning recipes), as well as to understand the ideas behind the analyses so students can take creative approaches to answering questions with data (e.g., learning to cook).

*Contributing to the textbook*

1. Use Hypothes.is, an amazing tool for annotating the web.
  
  a. Go to [Hypothes.is](https://web.hypothes.is/), and "get-started"
  
  b. Install the the add-on for chrome, or other browser
  
  c. That's it, turn on Hypothes.is when you are reading this textbook, and you will see all public annotations made by anyone else.
  
2. The source code for this textbook is available in my github repo [statsforpsych](https://github.com/CrumpLab/statsforpsych)
 
 a. Edit the .Rmd files, and push them back
  
  b. The edit link in the top bar of the textbook should automatically take you to the source .Rmd file

