# Programming Challenges II: Data

This set of programming challenges will give you hands on experience with using R for data-analysis.

## Creating and Analyzing Simulated Data

1.  Sample n values from a distribution

2.  Summary Statistics

3.  Mean, Median, Mode

4.  Standard Deviation, Variance

5.  Simulate and analyze data for a one sample t-test

6.  Simulate and analyze data for an independent samples t-test

7.  Simulate and analyze data for a paired samples t-test

8.  Simulate and analyze correlated data between continuous X and Y variables

9.  Simulate and analyze data for a chi-square test

10. Simulate and analyze data for a one-way ANOVA

11. Simulate and analyze data for a one-way repeated-measures ANOVA

12. Simulate and analyze data for a factorial ANOVA

13. Simulate and analyze data for a factorial repeated measures ANOVA

14. Simulate and analyze data for mixed design ANOVAs

15. Simulate and analyze the above by starting with simulated data for individual trials for each subject, and not simply simulated means for each condition

16. Monte-Carlo simulation for power-analysis

## Working with Real Raw Data

1.  Loading data-files from a file

2.  Pre-processing

3.  Handling Exceptions, buggy data

4.  Outliers

5.  Binning means

6.  Splitting the data into subsets

7.  Creating new conditions for exploratory analysis