<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew J. C. Crump">

<title>Answering questions with data - 6&nbsp; t-tests</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-ANOVA.html" rel="next">
<link href="./05-Foundation_Inference.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">

(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-79429674-3', 'auto');

ga('send', {
  hitType: 'pageview',
  'anonymizeIp': true,
});
</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/CrumpLab/statistics/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability, Sampling, and Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-RMANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-FactorialANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-MixedANOVA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Simulation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Simulating Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Thinking.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Thinking about answering questions with data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Gifs.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">GIFs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#check-your-confidence-in-your-mean" id="toc-check-your-confidence-in-your-mean" class="nav-link active" data-scroll-target="#check-your-confidence-in-your-mean"> <span class="header-section-number">6.1</span> Check your confidence in your mean</a></li>
  <li><a href="#one-sample-t-test-a-new-t-test" id="toc-one-sample-t-test-a-new-t-test" class="nav-link" data-scroll-target="#one-sample-t-test-a-new-t-test"> <span class="header-section-number">6.2</span> One-sample t-test: A new t-test</a>
  <ul class="collapse">
  <li><a href="#formulas-for-one-sample-t-test" id="toc-formulas-for-one-sample-t-test" class="nav-link" data-scroll-target="#formulas-for-one-sample-t-test"> <span class="header-section-number">6.2.1</span> Formulas for one-sample t-test</a></li>
  <li><a href="#what-does-t-represent" id="toc-what-does-t-represent" class="nav-link" data-scroll-target="#what-does-t-represent"> <span class="header-section-number">6.2.2</span> What does t represent?</a></li>
  <li><a href="#calculating-t-from-data" id="toc-calculating-t-from-data" class="nav-link" data-scroll-target="#calculating-t-from-data"> <span class="header-section-number">6.2.3</span> Calculating t from data</a></li>
  <li><a href="#how-does-t-behave" id="toc-how-does-t-behave" class="nav-link" data-scroll-target="#how-does-t-behave"> <span class="header-section-number">6.2.4</span> How does t behave?</a></li>
  <li><a href="#making-a-decision" id="toc-making-a-decision" class="nav-link" data-scroll-target="#making-a-decision"> <span class="header-section-number">6.2.5</span> Making a decision</a></li>
  </ul></li>
  <li><a href="#paired-samples-t-test" id="toc-paired-samples-t-test" class="nav-link" data-scroll-target="#paired-samples-t-test"> <span class="header-section-number">6.3</span> Paired-samples t-test</a>
  <ul class="collapse">
  <li><a href="#mehr-song-and-spelke-2016" id="toc-mehr-song-and-spelke-2016" class="nav-link" data-scroll-target="#mehr-song-and-spelke-2016"> <span class="header-section-number">6.3.1</span> Mehr, Song, and Spelke (2016)</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data"> <span class="header-section-number">6.3.2</span> The data</a></li>
  <li><a href="#the-difference-scores" id="toc-the-difference-scores" class="nav-link" data-scroll-target="#the-difference-scores"> <span class="header-section-number">6.3.3</span> The difference scores</a></li>
  <li><a href="#the-mean-difference" id="toc-the-mean-difference" class="nav-link" data-scroll-target="#the-mean-difference"> <span class="header-section-number">6.3.4</span> The mean difference</a></li>
  <li><a href="#calculate-t" id="toc-calculate-t" class="nav-link" data-scroll-target="#calculate-t"> <span class="header-section-number">6.3.5</span> Calculate t</a></li>
  <li><a href="#interpreting-ts" id="toc-interpreting-ts" class="nav-link" data-scroll-target="#interpreting-ts"> <span class="header-section-number">6.3.6</span> Interpreting <span class="math inline">\(t\)</span>s</a></li>
  <li><a href="#getting-the-p-values-for-t-values" id="toc-getting-the-p-values-for-t-values" class="nav-link" data-scroll-target="#getting-the-p-values-for-t-values"> <span class="header-section-number">6.3.7</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</a></li>
  <li><a href="#one-tailed-tests" id="toc-one-tailed-tests" class="nav-link" data-scroll-target="#one-tailed-tests"> <span class="header-section-number">6.3.8</span> One-tailed tests</a></li>
  <li><a href="#two-tailed-tests" id="toc-two-tailed-tests" class="nav-link" data-scroll-target="#two-tailed-tests"> <span class="header-section-number">6.3.9</span> Two-tailed tests</a></li>
  <li><a href="#one-or-two-tailed-which-one" id="toc-one-or-two-tailed-which-one" class="nav-link" data-scroll-target="#one-or-two-tailed-which-one"> <span class="header-section-number">6.3.10</span> One or two tailed, which one?</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"> <span class="header-section-number">6.3.11</span> Degrees of freedom</a></li>
  </ul></li>
  <li><a href="#the-paired-samples-t-test-strikes-back" id="toc-the-paired-samples-t-test-strikes-back" class="nav-link" data-scroll-target="#the-paired-samples-t-test-strikes-back"> <span class="header-section-number">6.4</span> The paired samples t-test strikes back</a></li>
  <li><a href="#independent-samples-t-test-the-return-of-the-t-test" id="toc-independent-samples-t-test-the-return-of-the-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test-the-return-of-the-t-test"> <span class="header-section-number">6.5</span> Independent samples t-test: The return of the t-test?</a></li>
  <li><a href="#simulating-data-for-t-tests" id="toc-simulating-data-for-t-tests" class="nav-link" data-scroll-target="#simulating-data-for-t-tests"> <span class="header-section-number">6.6</span> Simulating data for t-tests</a>
  <ul class="collapse">
  <li><a href="#simulating-a-one-sample-t-test" id="toc-simulating-a-one-sample-t-test" class="nav-link" data-scroll-target="#simulating-a-one-sample-t-test"> <span class="header-section-number">6.6.1</span> Simulating a one-sample t-test</a></li>
  <li><a href="#simulating-a-paired-samples-t-test" id="toc-simulating-a-paired-samples-t-test" class="nav-link" data-scroll-target="#simulating-a-paired-samples-t-test"> <span class="header-section-number">6.6.2</span> Simulating a paired samples t-test</a></li>
  <li><a href="#simulating-an-independent-samples-t.test" id="toc-simulating-an-independent-samples-t.test" class="nav-link" data-scroll-target="#simulating-an-independent-samples-t.test"> <span class="header-section-number">6.6.3</span> Simulating an independent samples t.test</a></li>
  </ul></li>
  <li><a href="#videos" id="toc-videos" class="nav-link" data-scroll-target="#videos"> <span class="header-section-number">6.7</span> Videos</a>
  <ul class="collapse">
  <li><a href="#one-or-two-tailed-tests" id="toc-one-or-two-tailed-tests" class="nav-link" data-scroll-target="#one-or-two-tailed-tests"> <span class="header-section-number">6.7.1</span> One or Two tailed tests</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/CrumpLab/statistics/edit/master/06-ttests.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew J. C. Crump </p>
          </div>
  </div>
    
    
  </div>
  

</header>

<div class="cell" data-hash="cache/unnamed-chunk-2_29d9b2b44cf1f087e24811fe2afd907e">

</div>
<p>Back in the day, William Sealy Gosset got a job working for Guinness Breweries. They make the famous Irish stout called Guinness. What happens next went something like this (total fabrication, but mostly on point).</p>
<p>Guinness wanted all of their beers to be the best beers. No mistakes, no bad beers. They wanted to improve their quality control so that when Guinness was poured anywhere in the world, it would always comes out fantastic: 5 stars out of 5 every time, the best.</p>
<p>Guinness had some beer tasters, who were super-experts. Every time they tasted a Guinness from the factory that wasn’t 5 out of 5, they knew right away.</p>
<p>But, Guinness had a big problem. They would make a keg of beer, and they would want to know if every single pint that would come out would be a 5 out of 5. So, the beer tasters drank pint after pint out of the keg, until it was gone. Some kegs were all 5 out of 5s. Some weren’t, Guinness needed to fix that. But, the biggest problem was that, after the testing, there <strong>was no beer left to sell</strong>, the testers drank it all (remember I’m making this part up to illustrate a point, they probably still had beer left to sell).</p>
<p>Guinness had a sampling and population problem. They wanted to know that the entire population of the beers they made were all 5 out of 5 stars. But, if they sampled the entire population, they would drink all of their beer, and wouldn’t have any left to sell.</p>
<p>Enter William Sealy Gosset. Gosset figured out the solution to the problem. He asked questions like this:</p>
<ol type="1">
<li><p>How many samples do I need to take to know the whole population is 5 out of 5?</p></li>
<li><p>What’s the fewest amount of samples I need to take to know the above, that would mean Guinness could test fewer beers for quality, sell more beers for profit, and make the product testing time shorter.</p></li>
</ol>
<p>Gosset solved those questions, and he invented something called the <em>Student’s t-test</em>. Gosset was working for Guinness, and could be fired for releasing trade-secrets that he invented (the t-test). But, Gosset published the work anyways, under a pseudonym <span class="citation" data-cites="Student1908">(<a href="references.html#ref-Student1908" role="doc-biblioref">Student 1908</a>)</span>. He called himself Student, hence Student’s t-test. Now you know the rest of the story.</p>
<p>It turns out this was a very nice thing for Gosset to have done. t-tests are used all the time, and they are useful, that’s why they are used. In this chapter we learn how they work.</p>
<p>You’ll be surprised to learn that what we’ve already talked about, (the Crump Test, and the Randomization Test), are both very very similar to the t-test. So, in general, you have already been thinking about the things you need to think about to understand t-tests. You’re probably wondering what is this <span class="math inline">\(t\)</span>, what does <span class="math inline">\(t\)</span> mean? We will tell you. Before we tell what it means, we first tell you about one more idea.</p>
<section id="check-your-confidence-in-your-mean" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="check-your-confidence-in-your-mean"><span class="header-section-number">6.1</span> Check your confidence in your mean</h2>
<p>We’ve talked about getting a sample of data. We know we can find the mean, we know we can find the standard deviation. We know we can look at the data in a histogram. These are all useful things to do for us to learn something about the properties of our data.</p>
<p>You might be thinking of the mean and standard deviation as very different things that we would not put together. The mean is about central tendency (where most of the data is), and the standard deviation is about variance (where most of the data isn’t). Yes, they are different things, but we can use them together to create useful new things.</p>
<p>What if I told you my sample mean was 50, and I told you nothing else about my sample. Would you be confident that most of the numbers were near 50? Would you wonder if there was a lot of variability in the sample, and many of the numbers were very different from 50. You should wonder all of those things. The mean alone, just by itself, doesn’t tell you anything about well the mean represents all of the numbers in the sample.</p>
<p>It could be a representative number, when the standard deviation is very small, and all the numbers are close to 50. It could be a non-representative number, when the standard deviation is large, and many of the numbers are not near 50. You need to know the standard deviation in order to be confident in how well the mean represents the data.</p>
<p>How can we put the mean and the standard deviation together, to give us a new number that tells us about confidence in the mean?</p>
<p>We can do this using a ratio:</p>
<p><span class="math inline">\(\frac{mean}{\text{standard deviation}}\)</span></p>
<p>Think about what happens here. We are dividing a number by a number. Look at what happens:</p>
<p><span class="math inline">\(\frac{number}{\text{same number}} = 1\)</span></p>
<p><span class="math inline">\(\frac{number}{\text{smaller number}} = \text{big number}\)</span></p>
<p>compared to:</p>
<p><span class="math inline">\(\frac{number}{\text{bigger number}} = \text{smaller number}\)</span></p>
<p>Imagine we have a mean of 50, and a truly small standard deviation of 1. What do we get with our formula?</p>
<p><span class="math inline">\(\frac{50}{1} = 50\)</span></p>
<p>Imagine we have a mean of 50, and a big standard deviation of 100. What do we get with our formula?</p>
<p><span class="math inline">\(\frac{50}{100} = 0.5\)</span></p>
<p>Notice, when we have a mean paired with a small standard deviation, our formula gives us a big number, like 50. When we have a mean paired with a large standard deviation, our formula gives us a small number, like 0.5. These numbers can tell us something about confidence in our mean, in a general way. We can be 50 confident in our mean in the first case, and only 0.5 (not at a lot) confident in the second case.</p>
<p>What did we do here? We created a descriptive statistic by dividing the mean by the standard deviation. And, we have a sense of how to interpret this number, when it’s big we’re more confident that the mean represents all of the numbers, when it’s small we are less confident. This is a useful kind of number, a ratio between what we think about our sample (the mean), and the variability in our sample (the standard deviation). Get used to this idea. Almost everything that follows in this textbook is based on this kind of ratio. We will see that our ratio turns into different kinds of “statistics”, and the ratios will look like this in general:</p>
<p><span class="math inline">\(\text{name of statistic} = \frac{\text{measure of what we know}}{\text{measure of what we don't know}}\)</span></p>
<p>or, to say it using different words:</p>
<p><span class="math inline">\(\text{name of statistic} = \frac{\text{measure of effect}}{\text{measure of error}}\)</span></p>
<p>In fact, this is the general formula for the t-test. Big surprise!</p>
</section>
<section id="one-sample-t-test-a-new-t-test" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="one-sample-t-test-a-new-t-test"><span class="header-section-number">6.2</span> One-sample t-test: A new t-test</h2>
<p>Now we are ready to talk about t-test. We will talk about three of them. We start with the one-sample t-test.</p>
<p>Commonly, the one-sample t-test is used to estimate the chances that your sample came from a particular population. Specifically, you might want to know whether the mean that you found from your sample, could have come from a particular population having a particular mean.</p>
<p>Straight away, the one-sample t-test becomes a little confusing (and I haven’t even described it yet). Officially, it uses known parameters from the population, like the mean of the population and the standard deviation of the population. However, most times you don’t know those parameters of the population! So, you have to estimate them from your sample. Remember from the chapters on descriptive statistics and sampling, our sample mean is an unbiased estimate of the population mean. And, our sample standard deviation (the one where we divide by n-1) is an unbiased estimate of the population standard deviation. When Gosset developed the t-test, he recognized that he could use these estimates from his samples, to make the t-test. Here is the formula for the one sample t-test, we first use words, and then become more specific:</p>
<section id="formulas-for-one-sample-t-test" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="formulas-for-one-sample-t-test"><span class="header-section-number">6.2.1</span> Formulas for one-sample t-test</h3>
<p><span class="math inline">\(\text{name of statistic} = \frac{\text{measure of effect}}{\text{measure of error}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\text{measure of effect}}{\text{measure of error}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\text{Mean difference}}{\text{standard error}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\bar{X}-u}{S_{\bar{X}}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\text{Sample Mean  - Population Mean}}{\text{Sample Standard Error}}\)</span></p>
<p><span class="math inline">\(\text{Estimated Standard Error} = \text{Standard Error of Sample} = \frac{s}{\sqrt{N}}\)</span></p>
<p>Where, s is the sample standard deviation.</p>
<p>Some of you may have gone cross-eyed looking at all of this. Remember, we’ve seen it before when we divided our mean by the standard deviation in the first bit. The t-test is just a measure of a sample mean, divided by the standard error of the sample mean. That is it.</p>
</section>
<section id="what-does-t-represent" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="what-does-t-represent"><span class="header-section-number">6.2.2</span> What does t represent?</h3>
<p><span class="math inline">\(t\)</span> gives us a measure of confidence, just like our previous ratio for dividing the mean by a standard deviations. The only difference with <span class="math inline">\(t\)</span>, is that we divide by the standard error of mean (remember, this is also a standard deviation, it is the standard deviation of the sampling distribution of the mean)</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>What does the t in t-test stand for? Apparently nothing. Gosset originally labelled it z. And, Fisher later called it t, perhaps because t comes after s, which is often used for the sample standard deviation.</p>
</div>
</div>
<p><span class="math inline">\(t\)</span> is a property of the data that you collect. You compute it with a sample mean, and a sample standard error (there’s one more thing in the one-sample formula, the population mean, which we get to in a moment). This is why we call <span class="math inline">\(t\)</span>, a sample-statistic. It’s a statistic we compute from the sample.</p>
<p>What kinds of numbers should we expect to find for these <span class="math inline">\(ts\)</span>? How could we figure that out?</p>
<p>Let’s start small and work through some examples. Imagine your sample mean is 5. You want to know if it came from a population that also has a mean of 5. In this case, what would <span class="math inline">\(t\)</span> be? It would be zero: we first subtract the sample mean from the population mean, <span class="math inline">\(5-5=0\)</span>. Because the numerator is 0, <span class="math inline">\(t\)</span> will be zero. So, <span class="math inline">\(t\)</span> = 0, occurs, when there is no difference.</p>
<p>Let’s say you take another sample, do you think the mean will be 5 every time, probably not. Let’s say the mean is 6. So, what can <span class="math inline">\(t\)</span> be here? It will be a positive number, because 6-5= +1. But, will <span class="math inline">\(t\)</span> be +1? That depends on the standard error of the sample. If the standard error of the sample is 1, then <span class="math inline">\(t\)</span> could be 1, because 1/1 = 1.</p>
<p>If the sample standard error is smaller than 1, what happens to <span class="math inline">\(t\)</span>? It get’s bigger right? For example, 1 divided by 0.5 = 2. If the sample standard error was 0.5, <span class="math inline">\(t\)</span> would be 2. And, what could we do with this information? Well, it be like a measure of confidence. As <span class="math inline">\(t\)</span> get’s bigger we could be more confident in the mean difference we are measuring.</p>
<p>Can <span class="math inline">\(t\)</span> be smaller than 1? Sure, it can. If the sample standard error is big, say like 2, then <span class="math inline">\(t\)</span> will be smaller than one (in our case), e.g., 1/2 = .5. The direction of the difference between the sample mean and population mean, can also make the <span class="math inline">\(t\)</span> become negative. What if our sample mean was 4. Well, then <span class="math inline">\(t\)</span> will be negative, because the mean difference in the numerator will be negative, and the number in the bottom (denominator) will always be positive (remember why, it’s the standard error, computed from the sample standard deviation, which is always positive because of the squaring that we did.).</p>
<p>So, that is some intuitions about what the kinds of values t can take. <span class="math inline">\(t\)</span> can be positive or negative, and big or small.</p>
<p>Let’s do one more thing to build our intuitions about what <span class="math inline">\(t\)</span> can look like. How about we sample some numbers and then measure the sample mean <strong>and</strong> the standard error of the mean, and then plot those two things against each each. This will show us how a sample mean typically varies with respect to the standard error of the mean.</p>
<p>In <a href="#fig-6sampleMSEM">Figure&nbsp;<span>6.1</span></a>, I pulled 1,000 samples of <span class="math inline">\(N = 10\)</span> from a normal distribution (mean = 0, sd = 1). Each time I measured the mean and standard error of the sample. That gave two descriptive statistics for each sample, letting us plot each sample as dot in a scatter plot.</p>
<div class="cell" data-hash="cache/fig-6sampleMSEM_057a53ba3f75172b70a29e5c5fbc9d76">
<div class="cell-output-display">
<div id="fig-6sampleMSEM" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6sampleMSEM-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.1: A scatter plot with sample mean on the x-axis, and standard error of the mean on the y-axis</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>What we get is a cloud of dots. You might notice the cloud has a circular quality. There’s more dots in the middle, and fewer dots as they radiate out from the middle. The dot cloud shows us the general range of the sample mean, for example most of the dots are in between -1 and 1. Similarly, the range for the sample standard error is roughly between .2 and .5. Remember, each dot represents one sample.</p>
<p>We can look at the same data a different way. For example, rather than using a scatter plot, we can divide the mean for each dot by the standard error for each dot. <a href="#fig-6thisexample">Figure&nbsp;<span>6.2</span></a> shows the result in a histogram.</p>
<div class="cell" data-hash="cache/fig-6thisexample_b493358d2734d5c0028500ee7f97bea3">
<div class="cell-output-display">
<div id="fig-6thisexample" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6thisexample-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.2: A histogram of the sample means divided by the sample standard errors, this is a t-distribution.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Interesting, we can see the histogram is shaped like a normal curve. It is centered on 0, which is the most common value. As values become more extreme, they become less common. If you remember, our formula for <span class="math inline">\(t\)</span>, was the mean divided by the standard error of the mean. That’s what we did here. This histogram is showing you a <span class="math inline">\(t\)</span>-distribution.</p>
</section>
<section id="calculating-t-from-data" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="calculating-t-from-data"><span class="header-section-number">6.2.3</span> Calculating t from data</h3>
<p>Let’s briefly calculate a t-value from a small sample. Let’s say we had 10 students do a true/false quiz with 5 questions on it. There’s a 50% chance of getting each answer correct.</p>
<p>Every student completes the 5 questions, we grade them, and then we find their performance (mean percent correct). What we want to know is whether the students were guessing. If they were all guessing, then the sample mean should be about 50%, it shouldn’t be different from chance, which is 50%. Let’s look at <a href="#tbl-tsmall">Table&nbsp;<span>6.1</span></a>.</p>
<div class="cell" data-hash="cache/tbl-tsmall_e5888ddfec66d5066cd182049e32bcd7">
<div class="cell-output-display">
<div id="tbl-tsmall" class="anchored">

<table><caption>Table 6.1:  Calculating the t-value for a one-sample test. </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> students </th>
   <th style="text-align:left;"> scores </th>
   <th style="text-align:left;"> mean </th>
   <th style="text-align:left;"> Difference_from_Mean </th>
   <th style="text-align:left;"> Squared_Deviations </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 50 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> -11 </td>
   <td style="text-align:left;"> 121 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 70 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 60 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> -1 </td>
   <td style="text-align:left;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 40 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> -21 </td>
   <td style="text-align:left;"> 441 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 80 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> 19 </td>
   <td style="text-align:left;"> 361 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 6 </td>
   <td style="text-align:left;"> 30 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> -31 </td>
   <td style="text-align:left;"> 961 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 7 </td>
   <td style="text-align:left;"> 90 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> 29 </td>
   <td style="text-align:left;"> 841 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 8 </td>
   <td style="text-align:left;"> 60 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> -1 </td>
   <td style="text-align:left;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 70 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> 9 </td>
   <td style="text-align:left;"> 81 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 10 </td>
   <td style="text-align:left;"> 60 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> -1 </td>
   <td style="text-align:left;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sums </td>
   <td style="text-align:left;"> 610 </td>
   <td style="text-align:left;"> 610 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 2890 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Means </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> 61 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 289 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> sd </td>
   <td style="text-align:left;"> 17.92 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> SEM </td>
   <td style="text-align:left;"> 5.67 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> t </td>
   <td style="text-align:left;"> 1.94003527336861 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>You can see the <code>scores</code> column has all of the test scores for each of the 10 students. We did the things we need to do to compute the standard deviation.</p>
<p>Remember the sample standard deviation is the square root of the sample variance, or:</p>
<p><span class="math inline">\(\text{sample standard deviation} = \sqrt{\frac{\sum_{i}^{n}({x_{i}-\bar{x})^2}}{N-1}}\)</span></p>
<p><span class="math inline">\(\text{sd} = \sqrt{\frac{2890}{10-1}} = 17.92\)</span></p>
<p>The standard error of the mean, is the standard deviation divided by the square root of N</p>
<p><span class="math inline">\(\text{SEM} = \frac{s}{\sqrt{N}} = \frac{17.92}{10} = 5.67\)</span></p>
<p><span class="math inline">\(t\)</span> is the difference between our sample mean (61), and our population mean (50, assuming chance), divided by the standard error of the mean.</p>
<p><span class="math inline">\(\text{t} = \frac{\bar{X}-u}{S_{\bar{X}}} = \frac{\bar{X}-u}{SEM} = \frac{61-50}{5.67} = 1.94\)</span></p>
<p>And, that is you how calculate <span class="math inline">\(t\)</span>, by hand. It’s a pain. I was annoyed doing it this way. In the lab, you learn how to calculate <span class="math inline">\(t\)</span> using software, so it will just spit out <span class="math inline">\(t\)</span>. For example in R, all you have to do is this:</p>
<div class="cell" data-hash="cache/unnamed-chunk-6_4cb4944841d69f06e60200a9ac941b0b">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(scores, <span class="at">mu=</span><span class="dv">50</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  One Sample t-test</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; data:  scores</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t = 1.9412, df = 9, p-value = 0.08415</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; alternative hypothesis: true mean is not equal to 50</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  48.18111 73.81889</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample estimates:</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mean of x </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        61</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="how-does-t-behave" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="how-does-t-behave"><span class="header-section-number">6.2.4</span> How does t behave?</h3>
<p>If <span class="math inline">\(t\)</span> is just a number that we can compute from our sample (it is), what can we do with it? How can we use <span class="math inline">\(t\)</span> for statistical inference?</p>
<p>Remember back to the chapter on sampling and distributions, that’s where we discussed the sampling distribution of the sample mean. Remember, we made a lot of samples, then computed the mean for each sample, then we plotted a histogram of the sample means. Later, in that same section, we mentioned that we could generate sampling distributions for any statistic. For each sample, we could compute the mean, the standard deviation, the standard error, and now even <span class="math inline">\(t\)</span>, if we wanted to. We could generate 10,000 samples, and draw four histograms, one for each sampling distribution for each statistic.</p>
<p>This is exactly what I did, and the results are shown in the four panels of <a href="#fig-6sampdists">Figure&nbsp;<span>6.3</span></a> below. I used a sample size of 20, and drew random observations for each sample from a normal distribution, with mean = 0, and standard deviation = 1. Let’s look at the sampling distributions for each of the statistics. <span class="math inline">\(t\)</span> was computed assuming with the population mean assumed to be 0.</p>
<div class="cell" data-hash="cache/fig-6sampdists_61649f2ac8a4760043a67938c73cdabb">
<div class="cell-output-display">
<div id="fig-6sampdists" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6sampdists-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.3: Sampling distributions for the mean, standard deviation, standard error of the mean, and <span class="math inline">\(t\)</span>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>We see four sampling distributions. This is how statistical summaries of these summaries behave. We have used the word chance windows before. These are four chance windows, measuring different aspects of the sample. In this case, all of the samples came from the same normal distribution. Because of sampling error, each sample is not identical. The means are not identical, the standard deviations are not identical, sample standard error of the means are not identical, and the <span class="math inline">\(t\)</span>s of the samples are not identical. They all have some variation, as shown by the histograms. This is how samples of size 20 behave.</p>
<p>We can see straight away, that in this case, we are unlikely to get a sample mean of 2. That’s way outside the window. The range for the sampling distribution of the mean is around -.5 to +.5, and is centered on 0 (the population mean, would you believe!).</p>
<p>We are unlikely to get sample standard deviations of between .6 and 1.5, that is a different range, specific to the sample standard deviation.</p>
<p>Same thing with the sample standard error of the mean, the range here is even smaller, mostly between .1, and .3. You would rarely find a sample with a standard error of the mean greater than .3. Virtually never would you find one of say 1 (for this situation).</p>
<p>Now, look at <span class="math inline">\(t\)</span>. It’s range is basically between -3 and +3 here. 3s barely happen at all. You pretty much never see a 5 or -5 in this situation.</p>
<p>All of these sampling windows are chance windows, and they can all be used in the same way as we have used similar sampling distributions before (e.g., Crump Test, and Randomization Test) for statistical inference. For all of them we would follow the same process:</p>
<ol type="1">
<li>Generate these distributions</li>
<li>Look at your sample statistics for the data you have (mean, SD, SEM, and <span class="math inline">\(t\)</span>)</li>
<li>Find the likelihood of obtaining that value or greater</li>
<li>Obtain that probability</li>
<li>See if you think your sample statistics were probable or improbable.</li>
</ol>
<p>We’ll formalize this in a second. I just want you to know that what you will be doing is something that you have already done before. For example, in the Crump test and the Randomization test we focused on the distribution of mean differences. We could do that again here, but instead, we will focus on the distribution of <span class="math inline">\(t\)</span> values. We then apply the same kinds of decision rules to the <span class="math inline">\(t\)</span> distribution, as we did for the other distributions. Below you will see a graph you have already seen, except this time it is a distribution of <span class="math inline">\(t\)</span>s, not mean differences:</p>
<p>Remember, if we obtained a single <span class="math inline">\(t\)</span> from one sample we collected, we could consult the chance window in <a href="#fig-6tdecision">Figure&nbsp;<span>6.4</span></a> below to find out whether the <span class="math inline">\(t\)</span> we obtained from the sample was likely or unlikely to occur by chance.</p>
<div class="cell" data-hash="cache/fig-6tdecision_73a0838cdbc11f3a632d4e717dd9fed3">
<div class="cell-output-display">
<div id="fig-6tdecision" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6tdecision-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.4: Applying decision criteria to the <span class="math inline">\(t\)</span>-distribution. Histogram of <span class="math inline">\(t\)</span>s from samples (n=20) drawn from the same normal distribution (u=0, sd=1)</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="making-a-decision" class="level3" data-number="6.2.5">
<h3 data-number="6.2.5" class="anchored" data-anchor-id="making-a-decision"><span class="header-section-number">6.2.5</span> Making a decision</h3>
<p>From our early example involving the TRUE/FALSE quizzes, we are now ready to make some kind of decision about what happened there. We found a mean difference of 11. We found a <span class="math inline">\(t\)</span> = 1.9411765. The probability of this <span class="math inline">\(t\)</span> or larger occurring is <span class="math inline">\(p\)</span> = 0.0841503. We were testing the idea that our sample mean of 61 could have come from a normal distribution with mean = 50. The <span class="math inline">\(t\)</span> test tells us that the <span class="math inline">\(t\)</span> for our sample, or a larger one, would happen with p = 0.0841503. In other words, chance can do it a kind of small amount of time, but not often. In English, this means that all of the students could have been guessing, but it wasn’t that likely that were just guessing.</p>
<p>The next <span class="math inline">\(t\)</span>-test is called a <strong>paired samples t-test</strong>. And, spoiler alert, we will find out that a paired samples t-test is actually a one-sample t-test in disguise (WHAT!), yes it is. If the one-sample <span class="math inline">\(t\)</span>-test didn’t make sense to you, read the next section.</p>
</section>
</section>
<section id="paired-samples-t-test" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="paired-samples-t-test"><span class="header-section-number">6.3</span> Paired-samples t-test</h2>
<p>For me (Crump), many analyses often boil down to a paired samples t-test. It just happens that many things I do reduce down to a test like this.</p>
<p>I am a cognitive psychologist, I conduct research about how people do things like remember, pay attention, and learn skills. There are lots of Psychologists like me, who do very similar things.</p>
<p>We all often conduct the same kinds of experiments. They go like this, and they are called <strong>repeated measures</strong> designs. They are called <strong>repeated measures</strong> designs, because we measure how one person does something more than once, we <strong>repeat</strong> the measure.</p>
<p>So, I might measure somebody doing something in condition A, and measure the same person doing something in Condition B, and then I see that same person does different things in the two conditions. I <strong>repeatedly measure</strong> the same person in both conditions. I am interested in whether the experimental manipulation changes something about how people perform the task in question.</p>
<section id="mehr-song-and-spelke-2016" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="mehr-song-and-spelke-2016"><span class="header-section-number">6.3.1</span> Mehr, Song, and Spelke (2016)</h3>
<p>We will introduce the paired-samples t-test with an example using real data, from a real study. <span class="citation" data-cites="mehr20165">Mehr, Song, and Spelke (<a href="references.html#ref-mehr20165" role="doc-biblioref">2016</a>)</span> were interested in whether singing songs to infants helps infants become more sensitive to social cues. For example, infants might need to learn to direct their attention toward people as a part of learning how to interact socially with people. Perhaps singing songs to infants aids this process of directing attention. When an infant hears a familiar song, they might start to pay more attention to the person singing that song, even after they are done singing the song. The person who sang the song might become more socially important to the infant. You will learn more about this study in the lab for this week. This example, prepares you for the lab activities. Here is a brief summary of what they did.</p>
<p>First, parents were trained to sing a song to their infants. After many days of singing this song to the infants, a parent came into the lab with their infant. In the first session, parents sat with their infants on their knees, so the infant could watch two video presentations. There were two videos. Each video involved two unfamiliar new people the infant had never seen before. Each new person in the video (the singers) sang one song to the infant. One singer sang the “familiar” song the infant had learned from their parents. The other singer sang an “unfamiliar” song the infant had not hear before.</p>
<p>There were two really important measurement phases: the baseline phase, and the test phase.</p>
<p>The baseline phase occurred before the infants saw and heard each singer sing a song. During the baseline phase, the infants watched a video of both singers at the same time. The researchers recorded the proportion of time that the infant looked at each singer. The baseline phase was conducted to determine whether infants had a preference to look at either person (who would later sing them a song).</p>
<p>The test phase occurred <strong>after</strong> infants saw and heard each song, sung by each singer. During the test phase, each infant had an opportunity to watch silent videos of both singers. The researchers measured the proportion of time the infants spent looking at each person. The question of interest, was whether the infants would spend a greater proportion of time looking at the singer who sang the familiar song, compared to the singer who sang the unfamiliar song.</p>
<p>There is more than one way to describe the design of this study. We will describe it like this. It was a repeated measures design, with one independent (manipulation) variable called Viewing phase: Baseline versus Test. There was one dependent variable (the measurement), which was proportion looking time (to singer who sung familiar song). This was a repeated measures design because the researchers measured proportion looking time twice (they repeated the measure), once during baseline (before infants heard each singer sing a song), and again during test (after infants head each singer sing a song).</p>
<p>The important question was whether infants would change their looking time, and look more at the singer who sang the familiar song during the test phase, than they did during the baseline phase. This is a question about a change within individual infants. In general, the possible outcomes for the study are:</p>
<ol type="1">
<li><p>No change: The difference between looking time toward the singer of the familiar song during baseline and test is zero, no difference.</p></li>
<li><p>Positive change: Infants will look longer toward the singer of the familiar song during the test phase (after they saw and heard the singers), compared to the baseline phase (before they saw and heard the singers). This is a positive difference if we use the formula: Test Phase Looking time - Baseline phase looking time (to familiar song singer).</p></li>
<li><p>Negative change: Infants will look longer toward the singer of the unfamiliar song during the test phase (after they saw and heard the singers), compared to the baseline phase (before they saw and heard the singers). This is a negative difference if we use the same formula: Test Phase Looking time - Baseline phase looking time (to familiar song singer).</p></li>
</ol>
</section>
<section id="the-data" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="the-data"><span class="header-section-number">6.3.2</span> The data</h3>
<p>Let’s take a look at the data for the first 5 infants in the study. This will help us better understand some properties of the data before we analyze it. We will see that the data is structured in a particular way that we can take advantage of with a paired samples t-test. Note, we look at the first 5 infants to show how the computations work. The results of the paired-samples t-test change when we use all of the data from the study.</p>
<p>Here is a table of the data:</p>
<div class="cell" data-hash="cache/unnamed-chunk-9_19538f361756b5154576d6bb9c5e84e4">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> infant </th>
   <th style="text-align:right;"> Baseline </th>
   <th style="text-align:right;"> Test </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.44 </td>
   <td style="text-align:right;"> 0.60 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.41 </td>
   <td style="text-align:right;"> 0.68 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:right;"> 0.72 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0.44 </td>
   <td style="text-align:right;"> 0.28 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0.47 </td>
   <td style="text-align:right;"> 0.50 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>The table shows proportion looking times toward the singer of the familiar song during the Baseline and Test phases. Notice there are five different infants, (1 to 5). Each infant is measured twice, once during the Baseline phase, and once during the Test phase. To repeat from before, this is a repeated-measures design, because the infants are measured repeatedly (twice in this case). Or, this kind of design is also called a <strong>paired-samples</strong> design. Why? because each participant comes with a pair of samples (two samples), one for each level of the design.</p>
<p>Great, so what are we really interested in here? We want to know if the mean looking time toward the singer of the familiar song for the Test phase is higher than the Baseline phase. We are comparing the two sample means against each other and looking for a difference. We already know that differences could be obtained by chance alone, simply because we took two sets of samples, and we know that samples can be different. So, we are interested in knowing whether chance was likely or unlikely to have produced any difference we might observe.</p>
<p>In other words, we are interested in looking at the difference scores between the baseline and test phase for each infant. The question here is, for each infant, did their proportion looking time to the singer of the familiar song, increase during the test phase as compared to the baseline phase.</p>
</section>
<section id="the-difference-scores" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="the-difference-scores"><span class="header-section-number">6.3.3</span> The difference scores</h3>
<p>Let’s add the difference scores to the table of data so it is easier to see what we are talking about. The first step in creating difference scores is to decide how you will take the difference, there are two options:</p>
<ol type="1">
<li>Test phase score - Baseline Phase Score</li>
<li>Baseline phase score - Test Phase score</li>
</ol>
<p>Let’s use the first formula. Why? Because it will give us positive differences when the test phase score is higher than the baseline phase score. This makes a positive score meaningful with respect to the study design, we know (because we defined it to be this way), that positive scores will refer to longer proportion looking times (to singer of familiar song) during the test phase compared to the baseline phase.</p>
<div class="cell" data-hash="cache/unnamed-chunk-10_1f20aae82ac9988a89ec991aed9dbe1c">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:right;"> infant </th>
   <th style="text-align:right;"> Baseline </th>
   <th style="text-align:right;"> Test </th>
   <th style="text-align:right;"> differences </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0.44 </td>
   <td style="text-align:right;"> 0.60 </td>
   <td style="text-align:right;"> 0.16 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0.41 </td>
   <td style="text-align:right;"> 0.68 </td>
   <td style="text-align:right;"> 0.27 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:right;"> -0.03 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0.44 </td>
   <td style="text-align:right;"> 0.28 </td>
   <td style="text-align:right;"> -0.16 </td>
  </tr>
  <tr>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0.47 </td>
   <td style="text-align:right;"> 0.50 </td>
   <td style="text-align:right;"> 0.03 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>There we have it, the difference scores. The first thing we can do here is look at the difference scores, and ask how many infants showed the effect of interest. Specifically, how many infants showed a positive difference score. We can see that three of five infants showed a positive difference (they looked more at the singer of the familiar song during the test than baseline phase), and two the infants showed the opposite effect (negative difference, they looked more at the singer of the familiar song during baseline than test).</p>
</section>
<section id="the-mean-difference" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="the-mean-difference"><span class="header-section-number">6.3.4</span> The mean difference</h3>
<p>As we have been discussing, the effect of interest in this study is the mean difference between the baseline and test phase proportion looking times. We can calculate the <strong>mean difference</strong>, by finding the <strong>mean of the difference scores</strong>. Let’s do that, in fact, for fun let’s calculate the mean of the baseline scores, the test scores, and the difference scores.</p>
<div class="cell" data-hash="cache/unnamed-chunk-11_be6134d74f13c64999c37ca7e4e5ad99">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> infant </th>
   <th style="text-align:left;"> Baseline </th>
   <th style="text-align:left;"> Test </th>
   <th style="text-align:left;"> differences </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 0.44 </td>
   <td style="text-align:left;"> 0.6 </td>
   <td style="text-align:left;"> 0.16 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 0.41 </td>
   <td style="text-align:left;"> 0.68 </td>
   <td style="text-align:left;"> 0.27 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 0.75 </td>
   <td style="text-align:left;"> 0.72 </td>
   <td style="text-align:left;"> -0.03 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 0.44 </td>
   <td style="text-align:left;"> 0.28 </td>
   <td style="text-align:left;"> -0.16 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 0.47 </td>
   <td style="text-align:left;"> 0.5 </td>
   <td style="text-align:left;"> 0.03 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sums </td>
   <td style="text-align:left;"> 2.51 </td>
   <td style="text-align:left;"> 2.78 </td>
   <td style="text-align:left;"> 0.27 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Means </td>
   <td style="text-align:left;"> 0.502 </td>
   <td style="text-align:left;"> 0.556 </td>
   <td style="text-align:left;"> 0.054 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>We can see there was a positive mean difference of 0.054, between the test and baseline phases.</p>
<p>Can we rush to judgment and conclude that infants are more socially attracted to individuals who have sung them a familiar song? I would hope not based on this very small sample. First, the difference in proportion looking isn’t very large, and of course we recognize that this difference could have been produced by chance.</p>
<p>We will more formally evaluate whether this difference could have been caused by chance with the paired-samples t-test. But, before we do that, let’s again calculate <span class="math inline">\(t\)</span> and discuss what <span class="math inline">\(t\)</span> tells us over and above what our measure of the mean of the difference scores tells us.</p>
</section>
<section id="calculate-t" class="level3" data-number="6.3.5">
<h3 data-number="6.3.5" class="anchored" data-anchor-id="calculate-t"><span class="header-section-number">6.3.5</span> Calculate t</h3>
<p>OK, so how do we calculate <span class="math inline">\(t\)</span> for a paired-samples <span class="math inline">\(t\)</span>-test? Surprise, we use the one-sample t-test formula that you already learned about! Specifically, we use the one-sample <span class="math inline">\(t\)</span>-test formula on the difference scores. We have one sample of difference scores (you can see they are in one column), so we can use the one-sample <span class="math inline">\(t\)</span>-test on the difference scores. Specifically, we are interested in comparing whether the mean of our difference scores came from a distribution with mean difference = 0. This is a special distribution we refer to as the <strong>null distribution</strong>. It is the distribution no differences. Of course, this <strong>null distribution</strong> can produce differences due to to sampling error, but those differences are not caused by any experimental manipulation, they caused by the random sampling process.</p>
<p>We calculate <span class="math inline">\(t\)</span> in a moment. Let’s now consider again why we want to calculate <span class="math inline">\(t\)</span>? Why don’t we just stick with the mean difference we already have?</p>
<p>Remember, the whole concept behind <span class="math inline">\(t\)</span>, is that it gives an indication of how confident we should be in our mean. Remember, <span class="math inline">\(t\)</span> involves a measure of the mean in the numerator, divided by a measure of variation (standard error of the sample mean) in the denominator. The resulting <span class="math inline">\(t\)</span> value is small when the mean difference is small, or when the variation is large. So small <span class="math inline">\(t\)</span>-values tell us that we shouldn’t be that confident in the estimate of our mean difference. Large <span class="math inline">\(t\)</span>-values occur when the mean difference is large and/or when the measure of variation is small. So, large <span class="math inline">\(t\)</span>-values tell us that we can be more confident in the estimate of our mean difference. Let’s find <span class="math inline">\(t\)</span> for the mean difference scores. We use the same formulas as we did last time:</p>
<div class="cell" data-hash="cache/unnamed-chunk-12_bb4b2f75ccfe9eeea128df9e267524a8">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> infant </th>
   <th style="text-align:left;"> Baseline </th>
   <th style="text-align:left;"> Test </th>
   <th style="text-align:left;"> differences </th>
   <th style="text-align:left;"> diff_from_mean </th>
   <th style="text-align:left;"> Squared_differences </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 0.44 </td>
   <td style="text-align:left;"> 0.6 </td>
   <td style="text-align:left;"> 0.16 </td>
   <td style="text-align:left;"> 0.106 </td>
   <td style="text-align:left;"> 0.011236 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 0.41 </td>
   <td style="text-align:left;"> 0.68 </td>
   <td style="text-align:left;"> 0.27 </td>
   <td style="text-align:left;"> 0.216 </td>
   <td style="text-align:left;"> 0.046656 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 0.75 </td>
   <td style="text-align:left;"> 0.72 </td>
   <td style="text-align:left;"> -0.03 </td>
   <td style="text-align:left;"> -0.084 </td>
   <td style="text-align:left;"> 0.00705600000000001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 0.44 </td>
   <td style="text-align:left;"> 0.28 </td>
   <td style="text-align:left;"> -0.16 </td>
   <td style="text-align:left;"> -0.214 </td>
   <td style="text-align:left;"> 0.045796 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 0.47 </td>
   <td style="text-align:left;"> 0.5 </td>
   <td style="text-align:left;"> 0.03 </td>
   <td style="text-align:left;"> -0.024 </td>
   <td style="text-align:left;"> 0.000575999999999999 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sums </td>
   <td style="text-align:left;"> 2.51 </td>
   <td style="text-align:left;"> 2.78 </td>
   <td style="text-align:left;"> 0.27 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0.11132 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Means </td>
   <td style="text-align:left;"> 0.502 </td>
   <td style="text-align:left;"> 0.556 </td>
   <td style="text-align:left;"> 0.054 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0.022264 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> sd </td>
   <td style="text-align:left;"> 0.167 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> SEM </td>
   <td style="text-align:left;"> 0.075 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> t </td>
   <td style="text-align:left;"> 0.72 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p>If we did this test using R, we would obtain almost the same numbers (there is a little bit of rounding in the table).</p>
<div class="cell" data-hash="cache/unnamed-chunk-13_489f83f8c13938b9a63e95331789377c">
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  differences
#&gt; t = 0.72381, df = 4, p-value = 0.5092
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.1531384  0.2611384
#&gt; sample estimates:
#&gt; mean of x 
#&gt;     0.054</code></pre>
</div>
<p>Here is a quick write up of our t-test results, t(4) = .72, p = .509.</p>
<p>What does all of that tell us? There’s a few things we haven’t gotten into much yet. For example, the 4 represents degrees of freedom, which we discuss later. The important part, the <span class="math inline">\(t\)</span> value should start to be a little bit more meaningful. We got a kind of small t-value didn’t we. It’s .72. What can we tell from this value? First, it is positive, so we know the mean difference is positive. The sign of the <span class="math inline">\(t\)</span>-value is always the same as the sign of the mean difference (ours was +0.054). We can also see that the p-value was .509. We’ve seen p-values before. This tells us that our <span class="math inline">\(t\)</span> value or larger, occurs about 50.9% of the time… Actually it means more than this. And, to understand it, we need to talk about the concept of two-tailed and one-tailed tests.</p>
</section>
<section id="interpreting-ts" class="level3" data-number="6.3.6">
<h3 data-number="6.3.6" class="anchored" data-anchor-id="interpreting-ts"><span class="header-section-number">6.3.6</span> Interpreting <span class="math inline">\(t\)</span>s</h3>
<p>Remember what it is we are doing here. We are evaluating whether our sample data could have come from a particular kind of distribution. The null distribution of no differences. This is the distribution of <span class="math inline">\(t\)</span>-values that would occur for samples of size 5, with a mean difference of 0, and a standard error of the sample mean of .075 (this is the SEM that we calculated from our sample). We can see what this particular null-distribution looks like in <a href="#fig-6tnull">Figure&nbsp;<span>6.5</span></a>.</p>
<div class="cell" data-hash="cache/fig-6tnull_189abbf2ff0a1ce817add5a1510c5e99">
<div class="cell-output-display">
<div id="fig-6tnull" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6tnull-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.5: A distribution of <span class="math inline">\(t\)</span>-values that can occur by chance alone, when there is no difference between the sample and a population</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The <span class="math inline">\(t\)</span>-distribution above shows us the kinds of values <span class="math inline">\(t\)</span> will will take by chance alone, when we measure the mean differences for pairs of 5 samples (like our current). <span class="math inline">\(t\)</span> is most likely to be zero, which is good, because we are looking at the distribution of no-differences, which should most often be 0! But, sometimes, due to sampling error, we can get <span class="math inline">\(t\)</span>s that are bigger than 0, either in the positive or negative direction. Notice the distribution is symmetrical, a <span class="math inline">\(t\)</span> from the null-distribution will be positive half of the time, and negative half of the time, that is what we would expect by chance.</p>
<p>So, what kind of information do we want know when we find a particular <span class="math inline">\(t\)</span> value from our sample? We want to know how likely the <span class="math inline">\(t\)</span> value like the one we found occurs just by chance. This is actually a subtly nuanced kind of question. For example, any particular <span class="math inline">\(t\)</span> value doesn’t have a specific probability of occurring. When we talk about probabilities, we are talking about ranges of probabilities. Let’s consider some probabilities. We will use the letter <span class="math inline">\(p\)</span>, to talk about the probabilities of particular <span class="math inline">\(t\)</span> values.</p>
<ol type="1">
<li><p>What is the probability that <span class="math inline">\(t\)</span> is zero or positive or negative? The answer is p=1, or 100%. We will always have a <span class="math inline">\(t\)</span> value that is zero or non-zero…Actually, if we can’t compute the t-value, for example when the standard deviation is undefined, I guess then we would have a non-number. But, assuming we can calculate <span class="math inline">\(t\)</span>, then it will always be 0 or positive or negative.</p></li>
<li><p>What is the probability of <span class="math inline">\(t\)</span> = 0 or greater than 0? The answer is p=.5, or 50%. 50% of <span class="math inline">\(t\)</span>-values are 0 or greater.</p></li>
<li><p>What is the of <span class="math inline">\(t\)</span> = 0 or smaller than 0? The answer is p=.5, or 50%. 50% of <span class="math inline">\(t\)</span>-values are 0 or smaller.</p></li>
</ol>
<p>We can answer all of those questions just by looking at our t-distribution, and dividing it into two equal regions, the left side (containing 50% of the <span class="math inline">\(t\)</span> values), and the right side containing 50% of the <span class="math inline">\(t\)</span>-values).</p>
<p>What if we wanted to take a more fine-grained approach, let’s say we were interested in regions of 10%. What kinds of <span class="math inline">\(t\)</span>s occur 10% of the time. We would apply lines like the following. Notice, the likelihood of bigger numbers (positive or negative) gets smaller, so we have to increase the width of the bars for each of the intervals between the bars to contain 10% of the <span class="math inline">\(t\)</span>-values, it looks like <a href="#fig-6percentregions">Figure&nbsp;<span>6.6</span></a>.</p>
<div class="cell" data-hash="cache/fig-6percentregions_d342b3440f4ab4d9df8b141182ab3c30">
<div class="cell-output-display">
<div id="fig-6percentregions" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6percentregions-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.6: Splitting the t distribution up into regions each containing 10% of the <span class="math inline">\(t\)</span>-values. The width between the bars narrows as they approach the center of the distribution, where there are more <span class="math inline">\(t\)</span>-values.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Consider the probabilities (<span class="math inline">\(p\)</span>) of <span class="math inline">\(t\)</span> for the different ranges.</p>
<ol type="1">
<li><span class="math inline">\(t\)</span> &lt;= -1.5 (<span class="math inline">\(t\)</span> is less than or equal to -1.5), <span class="math inline">\(p\)</span> = 10%</li>
<li>-1.5 &gt;= <span class="math inline">\(t\)</span> &lt;= -0.9 (<span class="math inline">\(t\)</span> is equal to or between -1.5 and -.9), <span class="math inline">\(p\)</span> = 10%</li>
<li>-.9 &gt;= <span class="math inline">\(t\)</span> &lt;= -0.6 (<span class="math inline">\(t\)</span> is equal to or between -.9 and -.6), <span class="math inline">\(p\)</span> = 10%</li>
<li><span class="math inline">\(t\)</span> &gt;= 1.5 (<span class="math inline">\(t\)</span> is greater than or equal to 1.5), <span class="math inline">\(p\)</span> = 10%</li>
</ol>
<p>Notice, that the <span class="math inline">\(p\)</span>s are always 10%. <span class="math inline">\(t\)</span>s occur in these ranges with 10% probability.</p>
</section>
<section id="getting-the-p-values-for-t-values" class="level3" data-number="6.3.7">
<h3 data-number="6.3.7" class="anchored" data-anchor-id="getting-the-p-values-for-t-values"><span class="header-section-number">6.3.7</span> Getting the p-values for <span class="math inline">\(t\)</span>-values</h3>
<p>You might be wondering where I am getting some of these values from. For example, how do I know that 10% of <span class="math inline">\(t\)</span> values (for this null distribution) have a value of approximately 1.5 or greater than 1.5? The answer is I used R to tell me.</p>
<p>In most statistics textbooks the answer would be: there is a table at the back of the book where you can look these things up…This textbook has no such table. We could make one for you. And, we might do that. But, we didn’t do that yet…</p>
<p>So, where do these values come from, how can you figure out what they are? The complicated answer is that we are not going to explain the math behind finding these values because, 1) the authors (some of us) admittedly don’t know the math well enough to explain it, and 2) it would sidetrack us to much, 3) you will learn how to get these numbers in the lab with software, 4) you will learn how to get these numbers in lab without the math, just by doing a simulation, and 5) you can do it in R, or excel, or you can use an <a href="http://www.socscistatistics.com/pvalues/tdistribution.aspx">online calculator</a>.</p>
<p>This is all to say that you can find the <span class="math inline">\(t\)</span>s and their associated <span class="math inline">\(p\)</span>s using software. But, the software won’t tell you what these values mean. That’s we are doing here. You will also see that software wants to know a few more things from you, such as the degrees of freedom for the test, and whether the test is one-tailed or two tailed. We haven’t explained any of these things yet. That’s what we are going to do now. Note, we explain degrees of freedom last. First, we start with a one-tailed test.</p>
</section>
<section id="one-tailed-tests" class="level3" data-number="6.3.8">
<h3 data-number="6.3.8" class="anchored" data-anchor-id="one-tailed-tests"><span class="header-section-number">6.3.8</span> One-tailed tests</h3>
<p>A <strong>one-tailed test</strong> is sometimes also called a directional test. It is called a directional test, because a researcher might have a hypothesis in mind suggesting that the difference they observe in their means is going to have a particular direction, either a positive difference, or a negative difference.</p>
<p>Typically, a researcher would set an <strong>alpha criterion</strong>. The alpha criterion describes a line in the sand for the researcher. Often, the alpha criterion is set at <span class="math inline">\(p = .05\)</span>. What does this mean? <a href="#fig-6critT">Figure&nbsp;<span>6.7</span></a> shows the <span class="math inline">\(t\)</span>-distribution and the alpha criterion.</p>
<div class="cell" data-hash="cache/fig-6critT_cb61540306457844abdd1a0dcf5751a8">
<div class="cell-output-display">
<div id="fig-6critT" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6critT-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.7: The critical value of t for an alpha criterion of 0.05. 5% of all ts are at this value or larger</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The figure shows that <span class="math inline">\(t\)</span> values of +2.13 or greater occur 5% of the time. Because the t-distribution is symmetrical, we also know that <span class="math inline">\(t\)</span> values of -2.13 or smaller also occur 5% of the time. Both of these properties are true under the null distribution of no differences. This means, that when there really are no differences, a researcher can expect to find <span class="math inline">\(t\)</span> values of 2.13 or larger 5% of the time.</p>
<p>Let’s review and connect some of the terms:</p>
<ol type="1">
<li><p><strong>alpha criterion</strong>: the criterion set by the researcher to make decisions about whether they believe chance did or did not cause the difference. The alpha criterion here is set to <span class="math inline">\(p = .05\)</span>.</p></li>
<li><p><strong>Critical</strong> <span class="math inline">\(t\)</span>. The critical <span class="math inline">\(t\)</span> is the <span class="math inline">\(t\)</span>-value associated with the alpha-criterion. In this case for a one-tailed test, it is the <span class="math inline">\(t\)</span> value where 5% of all <span class="math inline">\(t\)</span>s are this number or greater. In our example, the critical <span class="math inline">\(t\)</span> is 2.13. 5% of all <span class="math inline">\(t\)</span> values (with degrees of freedom = 4) are +2.13, or greater than +2.13.</p></li>
<li><p><strong>Observed</strong> <span class="math inline">\(t\)</span>. The observed <span class="math inline">\(t\)</span> is the one that you calculated from your sample. In our example about the infants, the observed <span class="math inline">\(t\)</span> was <span class="math inline">\(t\)</span> (4) = 0.72.</p></li>
<li><p><strong>p-value</strong>. The <span class="math inline">\(p\)</span>-value is the probability of obtaining the observed <span class="math inline">\(t\)</span> value or larger. Now, you could look back at our previous example, and find that the <span class="math inline">\(p\)</span>-value for <span class="math inline">\(t\)</span> (4) = .72, was <span class="math inline">\(p = .509\)</span> . HOWEVER, this p-value was not calculated for a one-directional test…(we talk about what .509 means in the next section).</p></li>
</ol>
<p><a href="#fig-6tonedirection">Figure&nbsp;<span>6.8</span></a> shows what the <span class="math inline">\(p\)</span>-value for <span class="math inline">\(t\)</span> (4) = .72 using a one-directional test would would look like:</p>
<div class="cell" data-hash="cache/fig-6tonedirection_16a85a57e1380346c5125da05ab0c5f7">
<div class="cell-output-display">
<div id="fig-6tonedirection" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6tonedirection-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.8: A case where the observed value of t is much less than the critical value for a one-directional t-test.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Let’s take this one step at a time. We have located the observed <span class="math inline">\(t\)</span> of .72 on the graph. We shaded the right region all grey. What we see is that the grey region represents .256 or 25.6% of all <span class="math inline">\(t\)</span> values. In other words, 25.6% of <span class="math inline">\(t\)</span> values are .72 or larger than .72. You could expect, by chance alone, to a find a <span class="math inline">\(t\)</span> value of .72 or larger, 25.6% of the time. That’s fairly often. We did find a <span class="math inline">\(t\)</span> value of .72. Now that you know this kind of <span class="math inline">\(t\)</span> value or larger occurs 25.6% of the time, would you be confident that the mean difference was not due to chance? Probably not, given that chance can produce this difference fairly often.</p>
<p>Following the “standard” decision making procedure, we would claim that our <span class="math inline">\(t\)</span> value was <strong>not statistically significant</strong>, because it was not large enough. If our observed value was larger than the critical <span class="math inline">\(t\)</span> (larger than 2.13), defined by our alpha criterion, then we would claim that our <span class="math inline">\(t\)</span> value was <strong>statistically significant</strong>. This would be equivalent to saying that we believe it is unlikely that the difference we observed was due to chance. In general, for any observed <span class="math inline">\(t\)</span> value, the associated <span class="math inline">\(p\)</span>-value tells you how likely a <span class="math inline">\(t\)</span> of the observed size or larger would be observed. The <span class="math inline">\(p\)</span>-value <strong>always</strong> refers to a <strong>range</strong> of <span class="math inline">\(t\)</span>-values, never to a single <span class="math inline">\(t\)</span>-value. Researchers use the alpha criterion of .05, as a matter of convenience and convention. There are other ways to interpret these values that do not rely on a strict (significant versus not) dichotomy.</p>
</section>
<section id="two-tailed-tests" class="level3" data-number="6.3.9">
<h3 data-number="6.3.9" class="anchored" data-anchor-id="two-tailed-tests"><span class="header-section-number">6.3.9</span> Two-tailed tests</h3>
<p>OK, so that was one-tailed tests… What are two tailed tests? The <span class="math inline">\(p\)</span>-value that we originally calculated from our paired-samples <span class="math inline">\(t\)</span>-test was for a 2-tailed test. Often, the default is that the <span class="math inline">\(p\)</span>-value is for a two-tailed test.</p>
<p>The two-tailed test, is asking a more general question about whether a difference is likely to have been produced by chance. The question is: what is probability of any difference. It is also called a <strong>non-directional</strong> test, because here we don’t care about the direction or sign of the difference (positive or negative), we just care if there is any kind of difference.</p>
<p>The same basic things as before are involved. We define an alpha criterion (<span class="math inline">\(\alpha = 0.05\)</span>). And, we say that any observed <span class="math inline">\(t\)</span> value that has a probability of <span class="math inline">\(p\)</span> &lt;.05 (<span class="math inline">\(p\)</span> is less than .05) will be called <strong>statistically significant</strong>, and ones that are more likely (<span class="math inline">\(p\)</span> &gt;.05, <span class="math inline">\(p\)</span> is greater than .05) will be called null-results, or not statistically significant. The only difference is how we draw the alpha range. Before it was on the right side of the <span class="math inline">\(t\)</span> distribution (we were conducting a one-sided test remember, so we were only interested in one side).</p>
<p><a href="#fig-6twotailedt">Figure&nbsp;<span>6.9</span></a> shows what the most extreme 5% of the <span class="math inline">\(t\)</span>-values are when we ignore their sign (whether they are positive or negative).</p>
<div class="cell" data-hash="cache/fig-6twotailedt_ba549b950637cd8b392617532fbc8246">
<div class="cell-output-display">
<div id="fig-6twotailedt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6twotailedt-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.9: Critical values for a two-tailed test. Each line represents the location where 2.5% of all <span class="math inline">\(t\)</span>s are larger or smaller than critical value. The total for both tails is 5%</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Here is what we are seeing. A distribution of no differences (the null, which is what we are looking at), will produce <span class="math inline">\(t\)</span>s that are 2.78 or greater 2.5% of the time, and <span class="math inline">\(t\)</span>s that are -2.78 or smaller 2.5% of the time. 2.5% + 2.5% is a total of 5% of the time. We could also say that <span class="math inline">\(t\)</span>s larger than +/- 2.78 occur 5% of the time.</p>
<p>As a result, the critical <span class="math inline">\(t\)</span> value is (+/-) 2.78 for a two-tailed test. As you can see, the two-tailed test is blind to the direction or sign of the difference. Because of this, the critical <span class="math inline">\(t\)</span> value is also higher for a two-tailed test, than for the one-tailed test that we did earlier. Hopefully, now you can see why it is called a two-tailed test. There are two tails of the distribution, one on the left and right, both shaded in green.</p>
</section>
<section id="one-or-two-tailed-which-one" class="level3" data-number="6.3.10">
<h3 data-number="6.3.10" class="anchored" data-anchor-id="one-or-two-tailed-which-one"><span class="header-section-number">6.3.10</span> One or two tailed, which one?</h3>
<p>Now that you know there are two kinds of tests, one-tailed, and two-tailed, which one should you use? There is some conventional wisdom on this, but also some debate. In the end, it is up to you to be able to justify your choice and why it is appropriate for you data. That is the real answer.</p>
<p>The conventional answer is that you use a one-tailed test when you have a theory or hypothesis that is making a directional prediction (the theory predicts that the difference will be positive, or negative). Similarly, use a two-tailed test when you are looking for any difference, and you don’t have a theory that makes a directional prediction (it just makes the prediction that there will be a difference, either positive or negative).</p>
<p>Also, people appear to choose one or two-tailed tests based on how risky they are as researchers. If you always ran one-tailed tests, your critical <span class="math inline">\(t\)</span> values for your set alpha criterion would always be smaller than the critical <span class="math inline">\(t\)</span>s for a two-tailed test. Over the long run, you would make more type I errors, because the criterion to detect an effect is a lower bar for one than two tailed tests.</p>
<blockquote class="blockquote">
<p>Remember type 1 errors occur when you reject the idea that chance could have caused your difference. You often never know when you make this error. It happens anytime that sampling error was the actual cause of the difference, but a researcher dismisses that possibility and concludes that their manipulation caused the difference.</p>
</blockquote>
<p>Similarly, if you always ran two-tailed tests, even when you had a directional prediction, you would make fewer type I errors over the long run, because the <span class="math inline">\(t\)</span> for a two-tailed test is higher than the <span class="math inline">\(t\)</span> for a one-tailed test. It seems quite common for researchers to use a more conservative two-tailed test, even when they are making a directional prediction based on theory. In practice, researchers tend to adopt a standard for reporting that is common in their field. Whether or not the practice is justifiable can sometimes be an open question. The important task for any researcher, or student learning statistics, is to be able to justify their choice of test.</p>
</section>
<section id="degrees-of-freedom" class="level3" data-number="6.3.11">
<h3 data-number="6.3.11" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">6.3.11</span> Degrees of freedom</h3>
<p>Before we finish up with paired-samples <span class="math inline">\(t\)</span>-tests, we should talk about degrees of freedom. Our sense is that students don’t really understand degrees of freedom very well. If you are reading this textbook, you are probably still wondering what is degrees of freedom, seeing as we haven’t really talked about it all.</p>
<p>For the <span class="math inline">\(t\)</span>-test, there is a formula for degrees of freedom. For the one-sample and paired sample <span class="math inline">\(t\)</span>-tests, the formula is:</p>
<p><span class="math inline">\(\text{Degrees of Freedom} = \text{df} = n-1\)</span>. Where n is the number of samples in the test.</p>
<p>In our paired <span class="math inline">\(t\)</span>-test example, there were 5 infants. Therefore, degrees of freedom = 5-1 = 4.</p>
<p>OK, that’s a formula. Who cares about degrees of freedom, what does the number mean? And why do we report it when we report a <span class="math inline">\(t\)</span>-test… you’ve probably noticed the number in parentheses e.g., <span class="math inline">\(t\)</span>(4)=.72, the 4 is the <span class="math inline">\(df\)</span>, or degrees of freedom.</p>
<p>Degrees of freedom is both a concept, and a correction. The concept is that if you estimate a property of the numbers, and you use this estimate, you will be forcing some constraints on your numbers.</p>
<p>Consider the numbers: 1, 2, 3. The mean of these numbers is 2. Now, let’s say I told you that the mean of three numbers is 2. Then, how many of these three numbers have freedom? Funny question right. What we mean is, how many of the three numbers could be any number, or have the freedom to be any number.</p>
<p>The first two numbers could be any number. But, once those two numbers are set, the final number (the third number), MUST be a particular number that makes the mean 2. The first two numbers have freedom. The third number has no freedom.</p>
<p>To illustrate. Let’s freely pick two numbers: 51 and -3. I used my personal freedom to pick those two numbers. Now, if our three numbers are 51, -3, and x, and the mean of these three numbers is 2. There is only one solution, x has to be -42, otherwise the mean won’t be 2. This is one way to think about degrees of freedom. The degrees of freedom for these three numbers is n-1 = 3-1= 2, because 2 of the numbers can be free, but the last number has no freedom, it becomes fixed after the first two are decided.</p>
<p>Now, statisticians often apply degrees of freedom to their calculations, especially when a second calculation relies on an estimated value. For example, when we calculate the standard deviation of a sample, we first calculate the mean of the sample right! By estimating the mean, we are fixing an aspect of our sample, and so, our sample now has n-1 degrees of freedom when we calculate the standard deviation (remember for the sample standard deviation, we divide by n-1…there’s that n-1 again.)</p>
<section id="simulating-how-degrees-of-freedom-affects-the-t-distribution" class="level4" data-number="6.3.11.1">
<h4 data-number="6.3.11.1" class="anchored" data-anchor-id="simulating-how-degrees-of-freedom-affects-the-t-distribution"><span class="header-section-number">6.3.11.1</span> Simulating how degrees of freedom affects the <span class="math inline">\(t\)</span> distribution</h4>
<p>There are at least two ways to think the degrees of freedom for a <span class="math inline">\(t\)</span>-test. For example, if you want to use math to compute aspects of the <span class="math inline">\(t\)</span> distribution, then you need the degrees of freedom to plug in to the formula… If you want to see the formulas I’m talking about, scroll down on the <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution"><span class="math inline">\(t\)</span>-test wikipedia page</a> and look for the probability density or cumulative distribution functions…We think that is quite scary for most people, and one reason why degrees of freedom are not well-understood.</p>
<p>If we wanted to simulate the <span class="math inline">\(t\)</span> distribution we could more easily see what influence degrees of freedom has on the shape of the distribution. Remember, <span class="math inline">\(t\)</span> is a sample statistic, it is something we measure from the sample. So, we could simulate the process of measuring <span class="math inline">\(t\)</span> from many different samples, then plot the histogram of <span class="math inline">\(t\)</span> to show us the simulated <span class="math inline">\(t\)</span> distribution.</p>
<div class="cell" data-fig.asp="0.5" data-hash="cache/fig-6dft_13af9a44a296ecf13325100e598d21b6">
<div class="cell-output-display">
<div id="fig-6dft" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6dft-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.10: The width of the t distribution shrinks as sample size and degrees of freedom (from 4 to 100) increases.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-6dft">Figure&nbsp;<span>6.10</span></a> notice that the red distribution for <span class="math inline">\(df = 4\)</span>, is a little bit shorter, and a little bit wider than the bluey-green distribution for <span class="math inline">\(df = 100\)</span>. As degrees of freedom increase the <span class="math inline">\(t\)</span> distribution gets taller (in the middle), and narrower in the range. It get’s more peaky. Can you guess the reason for this? Remember, we are estimating a sample statistic, and degrees of freedom is really just a number that refers to the number of subjects (well minus one). And, we already know that as we increase <span class="math inline">\(n\)</span>, our sample statistics become better estimates (less variance) of the distributional parameters they are estimating. So, <span class="math inline">\(t\)</span> becomes a better estimate of it’s “true” value as sample size increase, resulting in a more narrow distribution of <span class="math inline">\(t\)</span>s.</p>
<p>There is a slightly different <span class="math inline">\(t\)</span> distribution for every degrees of freedom, and the critical regions associated with 5% of the extreme values are thus slightly different every time. This is why we report the degrees of freedom for each t-test, they define the distribution of <span class="math inline">\(t\)</span> values for the sample-size in question. Why do we use n-1 and not n? Well, we calculate <span class="math inline">\(t\)</span> using the sample standard deviation to estimate the standard error or the mean, that estimate uses n-1 in the denominator, so our <span class="math inline">\(t\)</span> distribution is built assuming n-1. That’s enough for degrees of freedom…</p>
</section>
</section>
</section>
<section id="the-paired-samples-t-test-strikes-back" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="the-paired-samples-t-test-strikes-back"><span class="header-section-number">6.4</span> The paired samples t-test strikes back</h2>
<p>You must be wondering if we will ever be finished talking about paired samples t-tests… why are we doing round 2, oh no! Don’t worry, we’re just going to 1) remind you about what we were doing with the infant study, and 2) do a paired samples t-test on the entire data set and discuss.</p>
<p>Remember, we were wondering if the infants would look longer toward the singer who sang the familiar song during the test phase compared to the baseline phase. We showed you data from 5 infants, and walked through the computations for the <span class="math inline">\(t\)</span>-test. As a reminder, it looked like this:</p>
<div class="cell" data-hash="cache/unnamed-chunk-20_3053c5cb998871619691b404db9fdbb4">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> infant </th>
   <th style="text-align:left;"> Baseline </th>
   <th style="text-align:left;"> Test </th>
   <th style="text-align:left;"> differences </th>
   <th style="text-align:left;"> diff_from_mean </th>
   <th style="text-align:left;"> Squared_differences </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 1 </td>
   <td style="text-align:left;"> 0.44 </td>
   <td style="text-align:left;"> 0.6 </td>
   <td style="text-align:left;"> 0.16 </td>
   <td style="text-align:left;"> 0.106 </td>
   <td style="text-align:left;"> 0.011236 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2 </td>
   <td style="text-align:left;"> 0.41 </td>
   <td style="text-align:left;"> 0.68 </td>
   <td style="text-align:left;"> 0.27 </td>
   <td style="text-align:left;"> 0.216 </td>
   <td style="text-align:left;"> 0.046656 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 3 </td>
   <td style="text-align:left;"> 0.75 </td>
   <td style="text-align:left;"> 0.72 </td>
   <td style="text-align:left;"> -0.03 </td>
   <td style="text-align:left;"> -0.084 </td>
   <td style="text-align:left;"> 0.00705600000000001 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 4 </td>
   <td style="text-align:left;"> 0.44 </td>
   <td style="text-align:left;"> 0.28 </td>
   <td style="text-align:left;"> -0.16 </td>
   <td style="text-align:left;"> -0.214 </td>
   <td style="text-align:left;"> 0.045796 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 5 </td>
   <td style="text-align:left;"> 0.47 </td>
   <td style="text-align:left;"> 0.5 </td>
   <td style="text-align:left;"> 0.03 </td>
   <td style="text-align:left;"> -0.024 </td>
   <td style="text-align:left;"> 0.000575999999999999 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sums </td>
   <td style="text-align:left;"> 2.51 </td>
   <td style="text-align:left;"> 2.78 </td>
   <td style="text-align:left;"> 0.27 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0.11132 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Means </td>
   <td style="text-align:left;"> 0.502 </td>
   <td style="text-align:left;"> 0.556 </td>
   <td style="text-align:left;"> 0.054 </td>
   <td style="text-align:left;"> 0 </td>
   <td style="text-align:left;"> 0.022264 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> sd </td>
   <td style="text-align:left;"> 0.167 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> SEM </td>
   <td style="text-align:left;"> 0.075 </td>
  </tr>
  <tr>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;">  </td>
   <td style="text-align:left;"> t </td>
   <td style="text-align:left;"> 0.72 </td>
  </tr>
</tbody>
</table>

</div>
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  round(differences, digits = 2)
#&gt; t = 0.72381, df = 4, p-value = 0.5092
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  -0.1531384  0.2611384
#&gt; sample estimates:
#&gt; mean of x 
#&gt;     0.054</code></pre>
</div>
<p>Let’s write down the finding one more time: The mean difference was 0.054, <span class="math inline">\(t\)</span>(4) = .72, <span class="math inline">\(p\)</span> =.509. We can also now confirm, that the <span class="math inline">\(p\)</span>-value was from a two-tailed test. So, what does this all really mean.</p>
<p>We can say that a <span class="math inline">\(t\)</span> value with an absolute of .72 or larger occurs 50.9% of the time. More precisely, the distribution of no differences (the null), will produce a <span class="math inline">\(t\)</span> value this large or larger 50.9% of the time. In other words, chance alone good have easily produced the <span class="math inline">\(t\)</span> value from our sample, and the mean difference we observed or .054, could easily have been a result of chance.</p>
<p>Let’s quickly put all of the data in the <span class="math inline">\(t\)</span>-test, and re-run the test using all of the infant subjects.</p>
<div class="cell" data-hash="cache/unnamed-chunk-21_c1f6fa95ff64ed100751073ddc2c49f2">
<pre><code>#&gt; 
#&gt;  One Sample t-test
#&gt; 
#&gt; data:  differences
#&gt; t = 2.4388, df = 31, p-value = 0.02066
#&gt; alternative hypothesis: true mean is not equal to 0
#&gt; 95 percent confidence interval:
#&gt;  0.01192088 0.13370412
#&gt; sample estimates:
#&gt; mean of x 
#&gt; 0.0728125</code></pre>
</div>
<p>Now we get a very different answer. We would summarize the results saying the mean difference was .073, t(31) = 2.44, p = 0.020. How many total infants were their? Well the degrees of freedom was 31, so there must have been 32 infants in the study. Now we see a much smaller <span class="math inline">\(p\)</span>-value. This was also a two-tailed test, so we that observing a <span class="math inline">\(t\)</span> value of 2.4 or greater (absolute value) only occurs 2% of the time. In other words, the distribution of no differences will produce the observed t-value very rarely. So, it is unlikely that the observed mean difference of .073 was due to chance (it could have been due to chance, but that is very unlikely). As a result, we can be somewhat confident in concluding that something about seeing and hearing a unfamiliar person sing a familiar song, causes an infant to draw their attention toward the singer, and this potentially benefits social learning on the part of the infant.</p>
</section>
<section id="independent-samples-t-test-the-return-of-the-t-test" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="independent-samples-t-test-the-return-of-the-t-test"><span class="header-section-number">6.5</span> Independent samples t-test: The return of the t-test?</h2>
<p>If you’ve been following the Star Wars references, we are on last movie (of the original trilogy)… the independent t-test. This is were basically the same story plays out as before, only slightly different.</p>
<p>Remember there are different <span class="math inline">\(t\)</span>-tests for different kinds of research designs. When your design is a <strong>between-subjects</strong> design, you use an <strong>independent samples t-test</strong>. Between-subjects design involve different people or subjects in each experimental condition. If there are two conditions, and 10 people in each, then there are 20 total people. And, there are no paired scores, because every single person is measured once, not twice, no repeated measures. Because there are no repeated measures we can’t look at the difference scores between conditions one and two. The scores are not paired in any meaningful way, to it doesn’t make sense to subtract them. So what do we do?</p>
<p>The logic of the independent samples t-test is the very same as the other <span class="math inline">\(t\)</span>-tests. We calculated the means for each group, then we find the difference. That goes into the numerator of the t formula. Then we get an estimate of the variation for the denominator. We divide the mean difference by the estimate of the variation, and we get <span class="math inline">\(t\)</span>. It’s the same as before.</p>
<p>The only wrinkle here is what goes into the denominator? How should we calculate the estimate of the variance? It would be nice if we could do something very straightforward like this, say for an experiment with two groups A and B:</p>
<p><span class="math inline">\(t = \frac{\bar{A}-\bar{B}}{(\frac{SEM_A+SEM_B}{2})}\)</span></p>
<p>In plain language, this is just:</p>
<ol type="1">
<li>Find the mean difference for the top part</li>
<li>Compute the SEM (standard error of the mean) for each group, and average them together to make a single estimate, pooling over both samples.</li>
</ol>
<p>This would be nice, but unfortunately, it turns out that finding the average of two standard errors of the mean is not the best way to do it. This would create a biased estimator of the variation for the hypothesized distribution of no differences. We won’t go into the math here, but instead of the above formula, we an use a different one that gives as an <strong>unbiased estimate of the pooled standard error of the sample mean</strong>. Our new and improved <span class="math inline">\(t\)</span> formula would look like this:</p>
<p><span class="math inline">\(t = \frac{\bar{X_A}-\bar{X_B}}{s_p * \sqrt{\frac{1}{n_A} + \frac{1}{n_B}}}\)</span></p>
<p>and, <span class="math inline">\(s_p\)</span>, which is the pooled sample standard deviation is defined as, note the $s$es in the formula are variances:</p>
<p><span class="math inline">\(s_p = \sqrt{\frac{(n_A-1)s_A^2 + (n_B-1)s^2_B}{n_A +n_B -2}}\)</span></p>
<p>Believe you me, that is so much more formula than I wanted to type out. Shall we do one independent <span class="math inline">\(t\)</span>-test example by hand, just to see the computations? Let’s do it…but in a slightly different way than you expect. I show the steps using R. I made some fake scores for groups A and B. Then, I followed all of the steps from the formula, but made R do each of the calculations. This shows you the needed steps by following the code. At the end, I print the <span class="math inline">\(t\)</span>-test values I computed “by hand”, and then the <span class="math inline">\(t\)</span>-test value that the R software outputs using the <span class="math inline">\(t\)</span>-test function. You should be able to get the same values for <span class="math inline">\(t\)</span>, if you were brave enough to compute <span class="math inline">\(t\)</span> by hand.</p>
<div class="cell" data-hash="cache/unnamed-chunk-22_fb11a7b818bd05d1d08216bedc39ab08">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">## By "hand" using R r code</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">9</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>mean_difference <span class="ot">&lt;-</span> <span class="fu">mean</span>(a)<span class="sc">-</span><span class="fu">mean</span>(b) <span class="co"># compute mean difference</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>variance_a <span class="ot">&lt;-</span> <span class="fu">var</span>(a) <span class="co"># compute variance for A</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>variance_b <span class="ot">&lt;-</span> <span class="fu">var</span>(b) <span class="co"># compute variance for B</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute top part and bottom part of sp formula</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>sp_numerator <span class="ot">&lt;-</span> (<span class="dv">4</span><span class="sc">*</span>variance_a <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span> variance_b) </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>sp_denominator <span class="ot">&lt;-</span> <span class="dv">5</span><span class="sc">+</span><span class="dv">5-2</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>sp <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sp_numerator<span class="sc">/</span>sp_denominator) <span class="co"># compute sp</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="co"># compute t following formulat</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> mean_difference <span class="sc">/</span> ( sp <span class="sc">*</span> <span class="fu">sqrt</span>( (<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) <span class="sc">+</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">5</span>) ) )</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>t <span class="co"># print results</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] -2.017991</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co"># using the R function t.test</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(a,b, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  Two Sample t-test</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; data:  a and b</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; t = -2.018, df = 8, p-value = 0.0783</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; alternative hypothesis: true difference in means is not equal to 0</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 95 percent confidence interval:</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  -5.5710785  0.3710785</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; sample estimates:</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; mean of x mean of y </span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       3.0       5.6</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulating-data-for-t-tests" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="simulating-data-for-t-tests"><span class="header-section-number">6.6</span> Simulating data for t-tests</h2>
<p>An “advanced” topic for <span class="math inline">\(t\)</span>-tests is the idea of using R to conduct simulations for <span class="math inline">\(t\)</span>-tests.</p>
<p>If you recall, <span class="math inline">\(t\)</span> is a property of a sample. We calculate <span class="math inline">\(t\)</span> from our sample. The <span class="math inline">\(t\)</span> distribution is the hypothetical behavior of our sample. That is, if we had taken thousands upon thousands of samples, and calculated <span class="math inline">\(t\)</span> for each one, and then looked at the distribution of those <span class="math inline">\(t\)</span>’s, we would have the sampling distribution of <span class="math inline">\(t\)</span>!</p>
<p>It can be very useful to get in the habit of using R to simulate data under certain conditions, to see how your sample data, and things like <span class="math inline">\(t\)</span> behave. Why is this useful? It mainly prepares you with some intuitions about how sampling error (random chance) can influence your results, given specific parameters of your design, such as sample-size, the size of the mean difference you expect to find in your data, and the amount of variation you might find. These methods can be used formally to conduct power-analyses. Or more informally for data sense.</p>
<section id="simulating-a-one-sample-t-test" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="simulating-a-one-sample-t-test"><span class="header-section-number">6.6.1</span> Simulating a one-sample t-test</h3>
<p>Here are the steps you might follow to simulate data for a one sample <span class="math inline">\(t\)</span>-test.</p>
<ol type="1">
<li><p>Make some assumptions about what your sample (that you might be planning to collect) might look like. For example, you might be planning to collect 30 subjects worth of data. The scores of those data points might come from a normal distribution (mean = 50, sd = 10).</p></li>
<li><p>sample simulated numbers from the distribution, then conduct a <span class="math inline">\(t\)</span>-test on the simulated numbers. Save the statistics you want (such as <span class="math inline">\(t\)</span>s and <span class="math inline">\(p\)</span>s), and then see how things behave.</p></li>
</ol>
<p>Let’s do this a couple different times. First, let’s simulate samples with N = 30, taken from a normal (mean= 50, sd = 25). We’ll do a simulation with 1000 simulations. For each simulation, we will compare the sample mean with a population mean of 50. There should be no difference on average here. <a href="#fig-6nullt">Figure&nbsp;<span>6.11</span></a> is the null distribution that we are simulating.</p>
<div class="cell" data-hash="cache/unnamed-chunk-23_411d07c410c2a7a3c9d92020129c0673">

</div>
<div class="cell" data-hash="cache/fig-6nullt_57fb68339002167348a737d42f97873f">
<div class="cell-output-display">
<div id="fig-6nullt" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6nullt-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.11: The distribution of <span class="math inline">\(t\)</span>-values under the null. These are the <span class="math inline">\(t\)</span> values that are produced by chance alone.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="cache/fig-6flatp_5886dc71ea38822ee7aa1978dfb1a5e7">
<div class="cell-output-display">
<div id="fig-6flatp" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6flatp-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.12: The distribution of <span class="math inline">\(p\)</span>-values that are observed is flat under the null.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Neat. We see both a <span class="math inline">\(t\)</span> distribution, that looks like <span class="math inline">\(t\)</span> distribution as it should. And we see the <span class="math inline">\(p\)</span> distribution. This shows us how often we get <span class="math inline">\(t\)</span> values of particular sizes. You may find it interesting that the <span class="math inline">\(p\)</span>-distribution is flat under the null, which we are simulating here. This means that you have the same chances of a getting a <span class="math inline">\(t\)</span> with a p-value between 0 and 0.05, as you would for getting a <span class="math inline">\(t\)</span> with a p-value between .90 and .95. Those ranges are both ranges of 5%, so there are an equal amount of <span class="math inline">\(t\)</span> values in them by definition.</p>
<p>Here’s another way to do the same simulation in R, using the replicate function, instead a for loop:</p>
<div class="cell" data-hash="cache/fig-6simtsRep_a73e71fc05728e0f62f9ddb398f4da68">
<div class="cell-output-display">
<div id="fig-6simtsRep" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simtsRep-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.13: Simulating <span class="math inline">\(t\)</span>s in R.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="cache/fig-6simpsRep_544bac8e30563e3f5a6bb4dc63967f67">
<div class="cell-output-display">
<div id="fig-6simpsRep" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simpsRep-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.14: Simulating <span class="math inline">\(p\)</span>s in R.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="simulating-a-paired-samples-t-test" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="simulating-a-paired-samples-t-test"><span class="header-section-number">6.6.2</span> Simulating a paired samples t-test</h3>
<p>The code below is set up to sample 10 scores for condition A and B from the same normal distribution. The simulation is conducted 1000 times, and the <span class="math inline">\(t\)</span>s and <span class="math inline">\(p\)</span>s are saved and plotted for each.</p>
<div class="cell" data-hash="cache/unnamed-chunk-28_93cd9c871802c2368703077e1899f1b4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="cache/fig-6simps1000_9fa21e0f723da1adee81bd1ab2f1818f">
<div class="cell-output-display">
<div id="fig-6simps1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simps1000-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.15: 1000 simulated ts from the null distribution</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="cache/fig-6simts1000_0a6939f160dcbd4c2e79be432e5956ca">
<div class="cell-output-display">
<div id="fig-6simts1000" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simts1000-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.16: 1000 simulated ps from the null distribution</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>According to the simulation. When there are no differences between the conditions, and the samples are being pulled from the very same distribution, you get these two distributions for <span class="math inline">\(t\)</span> and <span class="math inline">\(p\)</span>. These again show how the null distribution of no differences behaves.</p>
<p>For any of these simulations, if you rejected the null-hypothesis (that your difference was only due to chance), you would be making a type I error. If you set your alpha criteria to <span class="math inline">\(\alpha = .05\)</span>, we can ask how many type I errors were made in these 1000 simulations. The answer is:</p>
<div class="cell" data-hash="cache/unnamed-chunk-31_803727eacfaddb7783720893ea87f45a">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 54</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.054</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We happened to make 54. The expectation over the long run is 5% type I error rates (if your alpha is .05).</p>
<p>What happens if there actually is a difference in the simulated data, let’s set one condition to have a larger mean than the other:</p>
<div class="cell" data-hash="cache/unnamed-chunk-32_8373ff378e7b82934438883827a17021">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">13</span>,<span class="dv">5</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="cache/fig-6simtruets_84ff9d129890ccb1e856fe8044addb0c">
<div class="cell-output-display">
<div id="fig-6simtruets" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simtruets-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.17: 1000 ts when there is a true difference</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="cache/fig-6simtrueps_f5acccef2b56b3954c25e59321620390">
<div class="cell-output-display">
<div id="fig-6simtrueps" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simtrueps-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.18: 1000 ps when there is a true difference</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Now you can see that the <span class="math inline">\(p\)</span>-value distribution is skewed to the left. This is because when there is a true effect, you will get p-values that are less than .05 more often. Or, rather, you get larger <span class="math inline">\(t\)</span> values than you normally would if there were no differences.</p>
<p>In this case, we wouldn’t be making a type I error if we rejected the null when p was smaller than .05. How many times would we do that out of our 1000 experiments?</p>
<div class="cell" data-hash="cache/unnamed-chunk-35_889d4ad25fbfd083ce10c3a0e8ec30ae">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 243</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(save_ps[save_ps<span class="sc">&lt;</span>.<span class="dv">05</span>])<span class="sc">/</span><span class="dv">1000</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 0.243</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We happened to get 243 simulations where p was less than .05, that’s only 0.243 experiments. If you were the researcher, would you want to run an experiment that would be successful only 0.243 of the time? I wouldn’t. I would run a better experiment.</p>
<p>How would you run a better simulated experiment? Well, you could increase <span class="math inline">\(n\)</span>, the number of subjects in the experiment. Let’s increase <span class="math inline">\(n\)</span> from 10 to 100, and see what happens to the number of “significant” simulated experiments.</p>
<div class="cell" data-hash="cache/unnamed-chunk-36_fa839dc6fc1d47ff1d2b418d85f2f086">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  condition_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  condition_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">100</span>,<span class="dv">13</span>,<span class="dv">5</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  differences <span class="ot">&lt;-</span> condition_A <span class="sc">-</span> condition_B</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(differences, <span class="at">mu=</span><span class="dv">0</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="cache/fig-6simtsB_a0d85578e233cef6a299ddcaf4f5e2c6">
<div class="cell-output-display">
<div id="fig-6simtsB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simtsB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.19: 1000 ts for n =100, when there is a true effect</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="cache/fig-6simpsB_978963e6aa3a7ebfc0856d785cc9ed01">
<pre><code>#&gt; [1] 982
#&gt; [1] 0.982</code></pre>
<div class="cell-output-display">
<div id="fig-6simpsB" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simpsB-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.20: 1000 ps for n =100, when there is a true effect</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Cool, now almost all of the experiments show a <span class="math inline">\(p\)</span>-value of less than .05 (using a two-tailed test, that’s the default in R). See, you could use this simulation process to determine how many subjects you need to reliably find your effect.</p>
</section>
<section id="simulating-an-independent-samples-t.test" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="simulating-an-independent-samples-t.test"><span class="header-section-number">6.6.3</span> Simulating an independent samples t.test</h3>
<p>Just change the t.test function like so… this is for the null, assuming no difference between groups.</p>
<div class="cell" data-hash="cache/unnamed-chunk-39_0d854ad31ea8adc07f553d99e670aa00">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>save_ps <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>save_ts <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="dv">1000</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ( i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span> ){</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  group_A <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  group_B <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10</span>,<span class="dv">10</span>,<span class="dv">5</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(group_A, group_B, <span class="at">paired=</span><span class="cn">FALSE</span>, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  save_ps[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>p.value</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  save_ts[i] <span class="ot">&lt;-</span> t_test<span class="sc">$</span>statistic</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-hash="cache/fig-6simtsC_d304cfd480ba8e7a9617271cbab79c0c">
<div class="cell-output-display">
<div id="fig-6simtsC" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simtsC-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.21: 1000 ts for n =100, when there is a true effect</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-hash="cache/fig-6simpsC_4331c4ba8b9b8f492508a2c5b55f1d81">
<pre><code>#&gt; [1] 66
#&gt; [1] 0.066</code></pre>
<div class="cell-output-display">
<div id="fig-6simpsC" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="06-ttests_files/figure-html/fig-6simpsC-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
<p></p><figcaption class="figure-caption">Figure 6.22: 1000 ps for n =100, when there is a true effect</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="videos" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="videos"><span class="header-section-number">6.7</span> Videos</h2>
<section id="one-or-two-tailed-tests" class="level3" data-number="6.7.1">
<h3 data-number="6.7.1" class="anchored" data-anchor-id="one-or-two-tailed-tests"><span class="header-section-number">6.7.1</span> One or Two tailed tests</h3>
<iframe width="560" height="315" src="https://www.youtube.com/embed/PuoGsguuY30" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-mehr20165" class="csl-entry" role="doc-biblioentry">
Mehr, Samuel A, Lee Ann Song, and Elizabeth S Spelke. 2016. <span>“For 5-Month-Old Infants, Melodies Are Social.”</span> <em>Psychological Science</em> 27 (4): 486–501. <a href="https://doi.org/10.1177/0956797615626691">https://doi.org/10.1177/0956797615626691</a>.
</div>
<div id="ref-Student1908" class="csl-entry" role="doc-biblioentry">
Student, A. 1908. <span>“The Probable Error of a Mean.”</span> <em>Biometrika</em> 6: 1–2.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-Foundation_Inference.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-ANOVA.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>