<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.258">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew J. C. Crump">

<title>Answering questions with data - 8&nbsp; Repeated Measures ANOVA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./09-FactorialANOVA.html" rel="next">
<link href="./07-ANOVA.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-1116FZ99DZ"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-1116FZ99DZ', { 'anonymize_ip': true});
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="Answering questions with data - 8&nbsp; Repeated Measures ANOVA">
<meta property="og:description" content="A free textbook teaching introductory statistics for undergraduates in psychology, including a lab manual, and course website. Licensed on CC BY SA 4.0">
<meta property="og:image" content="https://crumplab.com/statistics/imgs/figures/SS_ANOVA.png">
<meta property="og:site-name" content="Answering questions with data">
<meta property="og:image:height" content="1160">
<meta property="og:image:width" content="1520">
<meta name="twitter:title" content="Answering questions with data - 8&nbsp; Repeated Measures ANOVA">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://crumplab.com/statistics/imgs/TextbookCover.png">
<meta name="twitter:site" content="@MattCrumpLab">
<meta name="twitter:card" content="summary">
<meta name="twitter:image-height" content="1310">
<meta name="twitter:image-width" content="916">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-RMANOVA.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Answering questions with data</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/CrumpLab/statistics/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-Science_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Why Statistics?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-Describing_Data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Describing Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-Correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-SamplesPopulations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability, Sampling, and Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-Foundation_Inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Foundations for inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-ANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-RMANOVA.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-FactorialANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-MixedANOVA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">More On Factorial Designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-Simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Simulating Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-Thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Thinking about answering questions with data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-Gifs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">GIFs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#repeated-measures-design" id="toc-repeated-measures-design" class="nav-link active" data-scroll-target="#repeated-measures-design"><span class="header-section-number">8.1</span> Repeated measures design</a></li>
  <li><a href="#partitioning-the-sums-of-squares" id="toc-partitioning-the-sums-of-squares" class="nav-link" data-scroll-target="#partitioning-the-sums-of-squares"><span class="header-section-number">8.2</span> Partitioning the Sums of Squares</a></li>
  <li><a href="#calculating-the-rm-anova" id="toc-calculating-the-rm-anova" class="nav-link" data-scroll-target="#calculating-the-rm-anova"><span class="header-section-number">8.3</span> Calculating the RM ANOVA</a>
  <ul class="collapse">
  <li><a href="#ss-total" id="toc-ss-total" class="nav-link" data-scroll-target="#ss-total"><span class="header-section-number">8.3.1</span> SS Total</a></li>
  <li><a href="#ss-effect" id="toc-ss-effect" class="nav-link" data-scroll-target="#ss-effect"><span class="header-section-number">8.3.2</span> SS Effect</a></li>
  <li><a href="#ss-error-within-conditions" id="toc-ss-error-within-conditions" class="nav-link" data-scroll-target="#ss-error-within-conditions"><span class="header-section-number">8.3.3</span> SS Error (within-conditions)</a></li>
  <li><a href="#ss-subjects" id="toc-ss-subjects" class="nav-link" data-scroll-target="#ss-subjects"><span class="header-section-number">8.3.4</span> SS Subjects</a></li>
  <li><a href="#ss-error-left-over" id="toc-ss-error-left-over" class="nav-link" data-scroll-target="#ss-error-left-over"><span class="header-section-number">8.3.5</span> SS Error (left-over)</a></li>
  <li><a href="#check-our-work" id="toc-check-our-work" class="nav-link" data-scroll-target="#check-our-work"><span class="header-section-number">8.3.6</span> Check our work</a></li>
  <li><a href="#compute-the-mses" id="toc-compute-the-mses" class="nav-link" data-scroll-target="#compute-the-mses"><span class="header-section-number">8.3.7</span> Compute the MSEs</a></li>
  <li><a href="#compute-f" id="toc-compute-f" class="nav-link" data-scroll-target="#compute-f"><span class="header-section-number">8.3.8</span> Compute F</a></li>
  <li><a href="#p-value" id="toc-p-value" class="nav-link" data-scroll-target="#p-value"><span class="header-section-number">8.3.9</span> p-value</a></li>
  </ul></li>
  <li><a href="#things-worth-knowing" id="toc-things-worth-knowing" class="nav-link" data-scroll-target="#things-worth-knowing"><span class="header-section-number">8.4</span> Things worth knowing</a>
  <ul class="collapse">
  <li><a href="#repeated-vs-between-subjects-anova" id="toc-repeated-vs-between-subjects-anova" class="nav-link" data-scroll-target="#repeated-vs-between-subjects-anova"><span class="header-section-number">8.4.1</span> Repeated vs between-subjects ANOVA</a></li>
  <li><a href="#repeated-measures-designs-are-more-sensitive" id="toc-repeated-measures-designs-are-more-sensitive" class="nav-link" data-scroll-target="#repeated-measures-designs-are-more-sensitive"><span class="header-section-number">8.4.2</span> repeated measures designs are more sensitive</a></li>
  </ul></li>
  <li><a href="#real-data" id="toc-real-data" class="nav-link" data-scroll-target="#real-data"><span class="header-section-number">8.5</span> Real Data</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">8.6</span> Summary</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/CrumpLab/statistics/edit/master/08-RMANOVA.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Repeated Measures ANOVA</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Matthew J. C. Crump </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<p>This chapter introduces you to <strong>repeated measures ANOVA</strong>. Repeated measures ANOVAs are very common in Psychology, because psychologists often use repeated measures designs, and repeated measures ANOVAs are the appropriate test for making inferences about repeated measures designs.</p>
<p>Remember the paired sample <span class="math inline">\(t\)</span>-test? We used that test to compare two means from a repeated measures design. Remember what a repeated measures design is? It’s also called a within-subjects design. These designs involve measuring the same subject more than once. Specifically, at least once for every experimental condition. In the paired <span class="math inline">\(t\)</span>-test example, we discussed a simple experiment with only two experimental conditions. There, each subject would contribute a measurement to level one and level two of the design.</p>
<p>However, paired-samples <span class="math inline">\(t\)</span>-tests are limited to comparing two means. What if you had a design that had more than two experimental conditions? For example, perhaps your experiment had 3 levels for the independent variable, and each subject contributed data to each of the three levels?</p>
<p>This is starting to sounds like an ANOVA problem. ANOVAs are capable of evaluating whether there is a difference between any number of means, two or greater. So, we can use an ANOVA for our repeated measures design with three levels for the independent variable.</p>
<p>Great! So, what makes a repeated measures ANOVA different from the ANOVA we just talked about?</p>
<section id="repeated-measures-design" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="repeated-measures-design"><span class="header-section-number">8.1</span> Repeated measures design</h2>
<p>Let’s use the exact same toy example from the previous chapter, but let’s convert it to a repeated measures design.</p>
<p>Last time, we imagined we had some data in three groups, A, B, and C, such as in <a href="#tbl-8rmdata1">Table&nbsp;<span>8.1</span></a>:</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/tbl-8rmdata1_ed68e8aff3a78a8b0fc3aab6d0f15f4f">
<div class="cell-output-display">
<div id="tbl-8rmdata1" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;8.1: Example data for three groups.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">groups</th>
<th style="text-align: right;">scores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">A</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">B</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">C</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The above table represents a between-subject design where each score involves a unique subject.</p>
<p>Let’s change things up a tiny bit, and imagine we only had 3 subjects in total in the experiment. And, that each subject contributed data to the three levels of the independent variable, A, B, and C. Before we called the IV <code>groups</code>, because there were different groups of subjects. Let’s change that to <code>conditions</code>, because now the same group of subjects participates in all three conditions. <a href="#tbl-8rmdata2">Table&nbsp;<span>8.2</span></a> shows a within-subjects (repeated measures) version of this experiment:</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/tbl-8rmdata2_5d22fa3595d2fabe8fa40455232de4f6">
<div class="cell-output-display">
<div id="tbl-8rmdata2" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;8.2: Example data for a repeated measures design with three conditions, where each subject contributes data in each condition.</caption>
<thead>
<tr class="header">
<th style="text-align: right;">subjects</th>
<th style="text-align: left;">conditions</th>
<th style="text-align: right;">scores</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">C</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="partitioning-the-sums-of-squares" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="partitioning-the-sums-of-squares"><span class="header-section-number">8.2</span> Partitioning the Sums of Squares</h2>
<p>Time to introduce a new name for an idea you learned about last chapter, it’s called <strong>partitioning the sums of squares</strong>. Sometimes an obscure new name can be helpful for your understanding of what is going on. ANOVAs are all about partitioning the sums of squares. We already did some partitioning in the last chapter. What do we mean by partitioning?</p>
<p>Imagine you had a big empty house with no rooms in it. What would happen if you partitioned the house? What would you be doing? One way to partition the house is to split it up into different rooms. You can do this by adding new walls and making little rooms everywhere. That’s what partitioning means, to split up.</p>
<p>The act of partitioning, or splitting up, is the core idea of ANOVA. To use the house analogy. Our total sums of squares (SS Total) is our big empty house. We want to split it up into little rooms. Before we partitioned SS Total using this formula:</p>
<p><span class="math inline">\(SS_\text{TOTAL} = SS_\text{Effect} + SS_\text{Error}\)</span></p>
<p>Remember, the <span class="math inline">\(SS_\text{Effect}\)</span> was the variance we could attribute to the means of the different groups, and <span class="math inline">\(SS_\text{Error}\)</span> was the leftover variance that we couldn’t explain. <span class="math inline">\(SS_\text{Effect}\)</span> and <span class="math inline">\(SS_\text{Error}\)</span> are the partitions of <span class="math inline">\(SS_\text{TOTAL}\)</span>, they are the little rooms.</p>
<p>In the between-subjects case above, we got to split <span class="math inline">\(SS_\text{TOTAL}\)</span> into two parts. What is most interesting about the repeated-measures design, is that we get to split <span class="math inline">\(SS_\text{TOTAL}\)</span> into three parts, there’s one more partition. Can you guess what the new partition is? Hint: whenever we have a new way to calculate means in our design, we can always create a partition for those new means. What are the new means in the repeated measures design?</p>
<p>Here is the new idea for partitioning <span class="math inline">\(SS_\text{TOTAL}\)</span> in a repeated-measures design:</p>
<p><span class="math inline">\(SS_\text{TOTAL} = SS_\text{Effect} + SS_\text{Subjects} +SS_\text{Error}\)</span></p>
<p>We’ve added <span class="math inline">\(SS_\text{Subjects}\)</span> as the new idea in the formula. What’s the idea here? Well, because each subject was measured in each condition, we have a new set of means. These are the means for each subject, collapsed across the conditions. For example, subject 1 has a mean (mean of their scores in conditions A, B, and C); subject 2 has a mean (mean of their scores in conditions A, B, and C); and subject 3 has a mean (mean of their scores in conditions A, B, and C). There are three subject means, one for each subject, collapsed across the conditions. And, we can now estimate the portion of the total variance that is explained by these subject means.</p>
<p>We just showed you a “formula” to split up <span class="math inline">\(SS_\text{TOTAL}\)</span> into three parts, but we called the formula an idea. We did that because the way we wrote the formula is a little bit misleading, and we need to clear something up. Before we clear the thing up, we will confuse you just a little bit. Be prepared to be confused a little bit.</p>
<p>First, we need to introduce you to some more terms. It turns out that different authors use different words to describe parts of the ANOVA. This can be really confusing. For example, we described the SS formula for a between subjects design like this:</p>
<p><span class="math inline">\(SS_\text{TOTAL} = SS_\text{Effect} + SS_\text{Error}\)</span></p>
<p>However, the very same formula is often written differently, using the words between and within in place of effect and error, it looks like this:</p>
<p><span class="math inline">\(SS_\text{TOTAL} = SS_\text{Between} + SS_\text{Within}\)</span></p>
<p>Whoa, hold on a minute. Haven’t we switched back to talking about a <strong>between-subjects</strong> ANOVA. YES! Then why are we using the word <strong>within</strong>, what does that mean? YES! We think this is very confusing for people. Here the word <strong>within</strong> has a special meaning. It <strong>does not</strong> refer to a within-subjects design. Let’s explain. First, <span class="math inline">\(SS_\text{Between}\)</span> (which we have been calling <span class="math inline">\(SS_\text{Effect}\)</span>) refers to variation <strong>between</strong> the group means, that’s why it is called <span class="math inline">\(SS_\text{Between}\)</span>. Second, and most important, <span class="math inline">\(SS_\text{Within}\)</span> (which we have been calling <span class="math inline">\(SS_\text{Error}\)</span>), refers to the leftover variation within each group mean. Specifically, it is the variation between each group mean and each score in the group. “AAGGH, you’ve just used the word between to describe within group variation!”. Yes! We feel your pain. Remember, for each group mean, every score is probably off a little bit from the mean. So, the scores within each group have some variation. This is the within group variation, and it is why the leftover error that we can’t explain is often called <span class="math inline">\(SS_\text{Within}\)</span>.</p>
<p>OK. So why did we introduce this new confusing way of talking about things? Why can’t we just use <span class="math inline">\(SS_\text{Error}\)</span> to talk about this instead of <span class="math inline">\(SS_\text{Within}\)</span>, which you might (we do) find confusing. We’re getting there, but perhaps <a href="#fig-8splitSS">Figure&nbsp;<span>8.1</span></a> will help out.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/fig-8splitSS_6a41ec922154aa98a4009a801f7cb3a6">
<div class="cell-output-display">
<div id="fig-8splitSS" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/figures/SS_ANOVA.png" class="quarto-discovered-preview-image img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.1: Illustration showing how the total sums of squares are partitioned differently for a between versus repeated-measures design</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The figure lines up the partitioning of the Sums of Squares for both between-subjects and repeated-measures designs. In both designs, <span class="math inline">\(SS_\text{Total}\)</span> is first split up into two pieces <span class="math inline">\(SS_\text{Effect (between-groups)}\)</span> and <span class="math inline">\(SS_\text{Error (within-groups)}\)</span>. At this point, both ANOVAs are the same. In the repeated measures case we split the <span class="math inline">\(SS_\text{Error (within-groups)}\)</span> into two more littler parts, which we call <span class="math inline">\(SS_\text{Subjects (error variation about the subject mean)}\)</span> and <span class="math inline">\(SS_\text{Error (left-over variation we can't explain)}\)</span>.</p>
<p>So, when we earlier wrote the formula to split up SS in the repeated-measures design, we were kind of careless in defining what we actually meant by <span class="math inline">\(SS_\text{Error}\)</span>, this was a little too vague:</p>
<p><span class="math inline">\(SS_\text{TOTAL} = SS_\text{Effect} + SS_\text{Subjects} +SS_\text{Error}\)</span></p>
<p>The critical feature of the repeated-measures ANOVA, is that the <span class="math inline">\(SS_\text{Error}\)</span> that we will later use to compute the MSE in the denominator for the <span class="math inline">\(F\)</span>-value, is smaller in a repeated-measures design, compared to a between subjects design. This is because the <span class="math inline">\(SS_\text{Error (within-groups)}\)</span> is split into two parts, <span class="math inline">\(SS_\text{Subjects (error variation about the subject mean)}\)</span> and <span class="math inline">\(SS_\text{Error (left-over variation we can't explain)}\)</span>.</p>
<p>To make this more clear, consider <a href="#fig-8moresplit">Figure&nbsp;<span>8.2</span></a>:</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/fig-8moresplit_c7cb55c5266902cc1c20b08b1da5f62b">
<div class="cell-output-display">
<div id="fig-8moresplit" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/figures/SS_RMANOVA.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.2: Close-up showing that the Error term is split into two parts in the repeated measures design</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>As we point out, the <span class="math inline">\(SS_\text{Error (left-over)}\)</span> in the green circle will be a smaller number than the <span class="math inline">\(SS_\text{Error (within-group)}\)</span>. That’s because we are able to subtract out the <span class="math inline">\(SS_\text{Subjects}\)</span> part of the <span class="math inline">\(SS_\text{Error (within-group)}\)</span>. As we will see shortly, this can have the effect of producing larger F-values when using a repeated-measures design compared to a between-subjects design.</p>
</section>
<section id="calculating-the-rm-anova" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="calculating-the-rm-anova"><span class="header-section-number">8.3</span> Calculating the RM ANOVA</h2>
<p>Now that you are familiar with the concept of an ANOVA table (remember the table from last chapter where we reported all of the parts to calculate the <span class="math inline">\(F\)</span>-value?), we can take a look at the things we need to find out to make the ANOVA table. <a href="#fig-8rmtable">Figure&nbsp;<span>8.3</span></a> presents an abstract for the repeated-measures ANOVA table. It shows us all the thing we need to calculate to get the <span class="math inline">\(F\)</span>-value for our data.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/fig-8rmtable_b9a53b694afd12543f49b6b35b572fcd">
<div class="cell-output-display">
<div id="fig-8rmtable" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="imgs/figures/RMANOVA_table.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.3: Equations for computing the ANOVA table for a repeated measures design</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>So, what we need to do is calculate all the <span class="math inline">\(SS\)</span>es that we did before for the between-subjects ANOVA. That means the next three steps are identical to the ones you did before. In fact, I will just basically copy the next three steps to find <span class="math inline">\(SS_\text{TOTAL}\)</span>, <span class="math inline">\(SS_\text{Effect}\)</span> , and <span class="math inline">\(SS_\text{Error (within-conditions)}\)</span>. After that we will talk about splitting up <span class="math inline">\(SS_\text{Error (within-conditions)}\)</span> into two parts, this is the new thing for this chapter. Here we go!</p>
<section id="ss-total" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="ss-total"><span class="header-section-number">8.3.1</span> SS Total</h3>
<p>The total sums of squares, or <span class="math inline">\(SS\text{Total}\)</span> measures the total variation in a set of data. All we do is find the difference between each score and the grand mean, then we square the differences and add them all up.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/unnamed-chunk-8_771b34e93fc6cd2e87cdae95b950eae8">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">subjects</th>
<th style="text-align: left;">conditions</th>
<th style="text-align: left;">scores</th>
<th style="text-align: left;">diff</th>
<th style="text-align: left;">diff_squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">169</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">-5</td>
<td style="text-align: left;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">302</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">33.5555555555556</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean of all of the scores is called the <strong>Grand Mean</strong>. It’s calculated in the table, the Grand Mean = 7.</p>
<p>We also calculated all of the difference scores <strong>from the Grand Mean</strong>. The difference scores are in the column titled <code>diff</code>. Next, we squared the difference scores, and those are in the next column called <code>diff_squared</code>.</p>
<p>When you add up all of the individual squared deviations (difference scores) you get the sums of squares. That’s why it’s called the sums of squares (SS).</p>
<p>Now, we have the first part of our answer:</p>
<p><span class="math inline">\(SS_\text{total} = SS_\text{Effect} + SS_\text{Error}\)</span></p>
<p><span class="math inline">\(SS_\text{total} = 302\)</span> and</p>
<p><span class="math inline">\(302 = SS_\text{Effect} + SS_\text{Error}\)</span></p>
</section>
<section id="ss-effect" class="level3" data-number="8.3.2">
<h3 data-number="8.3.2" class="anchored" data-anchor-id="ss-effect"><span class="header-section-number">8.3.2</span> SS Effect</h3>
<p><span class="math inline">\(SS_\text{Total}\)</span> gave us a number representing all of the change in our data, how they all are different from the grand mean.</p>
<p>What we want to do next is estimate how much of the total change in the data might be due to the experimental manipulation. For example, if we ran an experiment that causes causes change in the measurement, then the means for each group will be different from other, and the scores in each group will be different from each. As a result, the manipulation forces change onto the numbers, and this will naturally mean that some part of the total variation in the numbers is caused by the manipulation.</p>
<p>The way to isolate the variation due to the manipulation (also called effect) is to look at the means in each group, and the calculate the difference scores between each group mean and the grand mean, and then the squared deviations to find the sum for <span class="math inline">\(SS_\text{Effect}\)</span>.</p>
<p>Consider this table, showing the calculations for <span class="math inline">\(SS_\text{Effect}\)</span>.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/unnamed-chunk-9_dd6e47e6a4d2ca4d321606e2d9ffe075">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">subjects</th>
<th style="text-align: left;">conditions</th>
<th style="text-align: left;">scores</th>
<th style="text-align: left;">means</th>
<th style="text-align: left;">diff</th>
<th style="text-align: left;">diff_squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">72</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notice we created a new column called <code>means</code>, these are the means for each condition, A, B, and C.</p>
<p><span class="math inline">\(SS_\text{Effect}\)</span> represents the amount of variation that is caused by differences between the means. The <code>diff</code> column is the difference between each condition mean and the grand mean, so for the first row, we have 11-7 = 4, and so on.</p>
<p>We found that <span class="math inline">\(SS_\text{Effect} = 72\)</span>, this is the same as the ANOVA from the previous chapter</p>
</section>
<section id="ss-error-within-conditions" class="level3" data-number="8.3.3">
<h3 data-number="8.3.3" class="anchored" data-anchor-id="ss-error-within-conditions"><span class="header-section-number">8.3.3</span> SS Error (within-conditions)</h3>
<p>Great, we made it to SS Error. We already found SS Total, and SS Effect, so now we can solve for SS Error just like this:</p>
<p><span class="math inline">\(SS_\text{total} = SS_\text{Effect} + SS_\text{Error (within-conditions)}\)</span></p>
<p>switching around:</p>
<p>$ SS_ = SS_ - SS_ $</p>
<p>$ SS_ = 302 - 72 = 230 $</p>
<p>Or, we could compute <span class="math inline">\(SS_\text{Error (within conditions)}\)</span> directly from the data as we did last time:</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/unnamed-chunk-10_5a195e89b198122a2ab3c984b8d29540">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;">subjects</th>
<th style="text-align: left;">conditions</th>
<th style="text-align: left;">scores</th>
<th style="text-align: left;">means</th>
<th style="text-align: left;">diff</th>
<th style="text-align: left;">diff_squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">-9</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">81</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-2</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">-6</td>
<td style="text-align: left;">36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">230</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">25.5555555555556</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>When we compute <span class="math inline">\(SS_\text{Error (within conditions)}\)</span> directly, we find the difference between each score and the condition mean for that score. This gives us the remaining error variation around the condition mean, that the condition mean does not explain.</p>
</section>
<section id="ss-subjects" class="level3" data-number="8.3.4">
<h3 data-number="8.3.4" class="anchored" data-anchor-id="ss-subjects"><span class="header-section-number">8.3.4</span> SS Subjects</h3>
<p>Now we are ready to calculate new partition, called <span class="math inline">\(SS_\text{Subjects}\)</span>. We first find the means for each subject. For subject 1, this is the mean of their scores across Conditions A, B, and C. The mean for subject 1 is 9.33 (repeating). Notice there is going to be some rounding error here, that’s OK for now.</p>
<p>The <code>means</code> column now shows all of the subject means. We then find the difference between each subject mean and the grand mean. These deviations are shown in the <code>diff</code> column. Then we square the deviations, and sum them up.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/unnamed-chunk-11_32131791a3036f155c22a315194b2361">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 26%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">subjects</th>
<th style="text-align: left;">conditions</th>
<th style="text-align: left;">scores</th>
<th style="text-align: left;">means</th>
<th style="text-align: left;">diff</th>
<th style="text-align: left;">diff_squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">9.33</td>
<td style="text-align: left;">2.33</td>
<td style="text-align: left;">5.4289</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">A</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">3.66</td>
<td style="text-align: left;">-3.34</td>
<td style="text-align: left;">11.1556</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">9.33</td>
<td style="text-align: left;">2.33</td>
<td style="text-align: left;">5.4289</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">3.66</td>
<td style="text-align: left;">-3.34</td>
<td style="text-align: left;">11.1556</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">9.33</td>
<td style="text-align: left;">2.33</td>
<td style="text-align: left;">5.4289</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">C</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">3.66</td>
<td style="text-align: left;">-3.34</td>
<td style="text-align: left;">11.1556</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sums</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">63</td>
<td style="text-align: left;">62.97</td>
<td style="text-align: left;">-0.0299999999999994</td>
<td style="text-align: left;">52.7535</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Means</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">6.99666666666667</td>
<td style="text-align: left;">-0.00333333333333326</td>
<td style="text-align: left;">5.8615</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We found that the sum of the squared deviations <span class="math inline">\(SS_\text{Subjects}\)</span> = 52.75. Note again, this has some small rounding error because some of the subject means had repeating decimal places, and did not divide evenly.</p>
<p>We can see the effect of the rounding error if we look at the sum and mean in the <code>diff</code> column. We know these should be both zero, because the Grand mean is the balancing point in the data. The sum and mean are both very close to zero, but they are not zero because of rounding error.</p>
</section>
<section id="ss-error-left-over" class="level3" data-number="8.3.5">
<h3 data-number="8.3.5" class="anchored" data-anchor-id="ss-error-left-over"><span class="header-section-number">8.3.5</span> SS Error (left-over)</h3>
<p>Now we can do the last thing. Remember we wanted to split up the <span class="math inline">\(SS_\text{Error (within conditions)}\)</span> into two parts, <span class="math inline">\(SS_\text{Subjects}\)</span> and <span class="math inline">\(SS_\text{Error (left-over)}\)</span>. Because we have already calculate <span class="math inline">\(SS_\text{Error (within conditions)}\)</span> and <span class="math inline">\(SS_\text{Subjects}\)</span>, we can solve for <span class="math inline">\(SS_\text{Error (left-over)}\)</span>:</p>
<p><span class="math inline">\(SS_\text{Error (left-over)} = SS_\text{Error (within conditions)} - SS_\text{Subjects}\)</span></p>
<p><span class="math inline">\(SS_\text{Error (left-over)} = SS_\text{Error (within conditions)} - SS_\text{Subjects} = 230 - 52.75 = 177.25\)</span></p>
</section>
<section id="check-our-work" class="level3" data-number="8.3.6">
<h3 data-number="8.3.6" class="anchored" data-anchor-id="check-our-work"><span class="header-section-number">8.3.6</span> Check our work</h3>
<p>Before we continue to compute the MSEs and F-value for our data, let’s quickly check our work. For example, we could have R compute the repeated measures ANOVA for us, and then we could look at the ANOVA table and see if we are on the right track so far.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/tbl-8rmANOVA1_8668971c16a8421513f225158cb83e02">
<div class="cell-output-display">
<div id="tbl-8rmANOVA1" class="anchored">
<table class="table table-sm table-striped">
<caption>Table&nbsp;8.3: Example ANOVA table table reporting the degrees of freedom, sums of squares, mean squares, <span class="math inline">\(F\)</span> value and associated <span class="math inline">\(p\)</span> value.</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">52.66667</td>
<td style="text-align: right;">26.33333</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">conditions</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">72.00000</td>
<td style="text-align: right;">36.00000</td>
<td style="text-align: right;">0.8120301</td>
<td style="text-align: right;">0.505848</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">177.33333</td>
<td style="text-align: right;">44.33333</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p><a href="#tbl-8rmANOVA1">Table&nbsp;<span>8.3</span></a> looks good. We found the <span class="math inline">\(SS_\text{Effect}\)</span> to be 72, and the SS for the conditions (same thing) in the table is also 72. We found the <span class="math inline">\(SS_\text{Subjects}\)</span> to be 52.75, and the SS for the first residual (same thing) in the table is also 53.66 repeating. That’s close, and our number is off because of rounding error. Finally, we found the <span class="math inline">\(SS_\text{Error (left-over)}\)</span> to be 177.25, and the SS for the bottom residuals in the table (same thing) in the table is 177.33 repeating, again close but slightly off due to rounding error.</p>
<p>We have finished our job of computing the sums of squares that we need in order to do the next steps, which include computing the MSEs for the effect and the error term. Once we do that, we can find the F-value, which is the ratio of the two MSEs.</p>
<p>Before we do that, you may have noticed that we solved for <span class="math inline">\(SS_\text{Error (left-over)}\)</span>, rather than directly computing it from the data. In this chapter we are not going to show you the steps for doing this. We are not trying to hide anything from, instead it turns out these steps are related to another important idea in ANOVA. We discuss this idea, which is called an <strong>interaction</strong> in the next chapter, when we discuss <strong>factorial</strong> designs (designs with more than one independent variable).</p>
</section>
<section id="compute-the-mses" class="level3" data-number="8.3.7">
<h3 data-number="8.3.7" class="anchored" data-anchor-id="compute-the-mses"><span class="header-section-number">8.3.7</span> Compute the MSEs</h3>
<p>Calculating the MSEs (mean squared error) that we need for the <span class="math inline">\(F\)</span>-value involves the same general steps as last time. We divide each SS by the degrees of freedom for the SS.</p>
<p>The degrees of freedom for <span class="math inline">\(SS_\text{Effect}\)</span> are the same as before, the number of conditions - 1. We have three conditions, so the df is 2. Now we can compute the <span class="math inline">\(MSE_\text{Effect}\)</span>.</p>
<p><span class="math inline">\(MSE_\text{Effect} = \frac{SS_\text{Effect}}{df} = \frac{72}{2} = 36\)</span></p>
<p>The degrees of freedom for <span class="math inline">\(SS_\text{Error (left-over)}\)</span> are different than before, they are the (number of subjects - 1) multiplied by the (number of conditions -1). We have 3 subjects and three conditions, so <span class="math inline">\((3-1) * (3-1) = 2*2 =4\)</span>. You might be wondering why we are multiplying these numbers. Hold that thought for now and wait until the next chapter. Regardless, now we can compute the <span class="math inline">\(MSE_\text{Error (left-over)}\)</span>.</p>
<p><span class="math inline">\(MSE_\text{Error (left-over)} = \frac{SS_\text{Error (left-over)}}{df} = \frac{177.33}{4}= 44.33\)</span></p>
</section>
<section id="compute-f" class="level3" data-number="8.3.8">
<h3 data-number="8.3.8" class="anchored" data-anchor-id="compute-f"><span class="header-section-number">8.3.8</span> Compute F</h3>
<p>We just found the two MSEs that we need to compute <span class="math inline">\(F\)</span>. We went through all of this to compute <span class="math inline">\(F\)</span> for our data, so let’s do it:</p>
<p><span class="math inline">\(F = \frac{MSE_\text{Effect}}{MSE_\text{Error (left-over)}} = \frac{36}{44.33}= 0.812\)</span></p>
<p>And, there we have it!</p>
</section>
<section id="p-value" class="level3" data-number="8.3.9">
<h3 data-number="8.3.9" class="anchored" data-anchor-id="p-value"><span class="header-section-number">8.3.9</span> p-value</h3>
<p>We already conducted the repeated-measures ANOVA using R and reported the ANOVA. Here it is again. The table shows the <span class="math inline">\(p\)</span>-value associated with our <span class="math inline">\(F\)</span>-value.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/unnamed-chunk-13_04c7fc1f9b617e161f33cc7e1b75e79f">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">52.66667</td>
<td style="text-align: right;">26.33333</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">conditions</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">72.00000</td>
<td style="text-align: right;">36.00000</td>
<td style="text-align: right;">0.8120301</td>
<td style="text-align: right;">0.505848</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">177.33333</td>
<td style="text-align: right;">44.33333</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We might write up the results of our experiment and say that the main effect condition was not significant, F(2,4) = 0.812, MSE = 44.33, p = 0.505.</p>
<p>What does this statement mean? Remember, that the <span class="math inline">\(p\)</span>-value represents the probability of getting the <span class="math inline">\(F\)</span> value we observed or larger under the null (assuming that the samples come from the same distribution, the assumption of no differences). So, we know that an <span class="math inline">\(F\)</span>-value of 0.812 or larger happens fairly often by chance (when there are no real differences), in fact it happens 50.5% of the time. As a result, we do not reject the idea that any differences in the means we have observed could have been produced by chance.</p>
</section>
</section>
<section id="things-worth-knowing" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="things-worth-knowing"><span class="header-section-number">8.4</span> Things worth knowing</h2>
<p>Repeated Measures ANOVAs have some special properties that are worth knowing about. The main special property is that the error term used to for the <span class="math inline">\(F\)</span>-value (the MSE in the denominator) will always be smaller than the error term used for the <span class="math inline">\(F\)</span>-value the ANOVA for a between-subjects design. We discussed this earlier. It is smaller, because we subtract out the error associated with the subject means.</p>
<p>This can have the consequence of generally making <span class="math inline">\(F\)</span>-values in repeated measures designs larger than <span class="math inline">\(F\)</span>-values in between-subjects designs. When the number in the bottom of the <span class="math inline">\(F\)</span> formula is generally smaller, it will generally make the resulting ratio a larger number. That’s what happens when you make the number in the bottom smaller.</p>
<p>Because big <span class="math inline">\(F\)</span> values usually let us reject the idea that differences in our means are due to chance, the repeated-measures ANOVA becomes a more sensitive test of the differences (its <span class="math inline">\(F\)</span>-values are usually larger).</p>
<p>At the same time, there is a trade-off here. The repeated measures ANOVA uses different degrees of freedom for the error term, and these are typically a smaller number of degrees of freedom. So, the <span class="math inline">\(F\)</span>-distributions for the repeated measures and between-subjects designs are actually different <span class="math inline">\(F\)</span>-distributions, because they have different degrees of freedom.</p>
<section id="repeated-vs-between-subjects-anova" class="level3" data-number="8.4.1">
<h3 data-number="8.4.1" class="anchored" data-anchor-id="repeated-vs-between-subjects-anova"><span class="header-section-number">8.4.1</span> Repeated vs between-subjects ANOVA</h3>
<p>Let’s do a couple simulations to see some the differences between the ANOVA for a repeated measures design, and the ANOVA for a between-subjects design.</p>
<p>We will do the following.</p>
<ol type="1">
<li>Simulate a design with three conditions, A, B, and C</li>
<li>sample 10 scores into each condition from the same normal distribution (mean = 100, SD = 10)</li>
<li>We will include a subject factor for the repeated-measures version. Here there are 10 subjects, each contributing three scores, one each condition</li>
<li>For the between-subjects design there are 30 different subjects, each contributing one score in the condition they were assigned to (really the group).</li>
</ol>
<p>We run 1000 simulated experiments for each design. We calculate the <span class="math inline">\(F\)</span> for each experiment, for both the between and repeated measures designs. <a href="#fig-8critcompare">Figure&nbsp;<span>8.4</span></a> has the sampling distributions of <span class="math inline">\(F\)</span> for both designs.</p>
<div class="cell" data-fig.asp="0.5" data-hash="08-RMANOVA_cache/html/fig-8critcompare_15987e4716dd369ca5ec6c343e4c713d">
<div class="cell-output-display">
<div id="fig-8critcompare" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-RMANOVA_files/figure-html/fig-8critcompare-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.4: Comparing critical F values for a between and repeated measures design</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>These two <span class="math inline">\(F\)</span> sampling distributions look pretty similar. However, they are subtly different. The between <span class="math inline">\(F\)</span> distribution has degrees of freedom 2, and 27, for the numerator and denominator. There are 3 conditions, so $df$1 = 3-1 = 2. There are 30 subjects, so $df$2 = 30-3 =27. The critical value, assuming an alpha of 0.05 is 3.35. This means <span class="math inline">\(F\)</span> is 3.35 or larger 5% of the time under the null.</p>
<p>The repeated-measures <span class="math inline">\(F\)</span> distribution has degrees of freedom 2, and 18, for the numerator and denominator. There are 3 conditions, so $df$1 = 3-1 = 2. There are 10 subjects, so $df$2 = (10-1)<em>(3-1) = 9</em>2 = 18. The critical value, assuming an alpha of 0.05 is 3.55. This means <span class="math inline">\(F\)</span> is 3.55 or larger 5% of the time under the null.</p>
<p>The critical value for the repeated measures version is slightly higher. This is because when $df$2 (the denominator) is smaller, the <span class="math inline">\(F\)</span>-distribution spreads out to the right a little bit. When it is skewed like this, we get some bigger <span class="math inline">\(F\)</span>s a greater proportion of the time.</p>
<p>So, in order to detect a real difference, you need an <span class="math inline">\(F\)</span> of 3.35 or greater in a between-subjects design, or an <span class="math inline">\(F\)</span> of 3.55 or greater for a repeated-measures design. The catch here is that when there is a real difference between the means, you will detect it more often with the repeated-measures design, even though you need a larger <span class="math inline">\(F\)</span> (to pass the higher critical <span class="math inline">\(F\)</span>-value for the repeated measures design).</p>
</section>
<section id="repeated-measures-designs-are-more-sensitive" class="level3" data-number="8.4.2">
<h3 data-number="8.4.2" class="anchored" data-anchor-id="repeated-measures-designs-are-more-sensitive"><span class="header-section-number">8.4.2</span> repeated measures designs are more sensitive</h3>
<p>To illustrate why repeated-measures designs are more sensitive, we will conduct another set of simulations.</p>
<p>We will do something slightly different this time. We will make sure that the scores for condition A, are always a little bit higher than the other scores. In other words, we will program in a real true difference. Specifically, the scores for condition will be sampled from a normal distribution with mean = 105, and SD = 10. This mean is 5 larger than the means for the other two conditions (still set to 100).</p>
<p>With a real difference in the means, we should now reject the hypothesis of no differences more often. We should find <span class="math inline">\(F\)</span> values larger than the critical value more often. And, we should find <span class="math inline">\(p\)</span>-values for each experiment that are smaller than .05 more often, those should occur more than 5% of the time.</p>
<p>To look at this we conduct 1000 experiments for each design, we conduct the ANOVA, then we save the <span class="math inline">\(p\)</span>-value we obtained for each experiment. This is like asking how many times will we find a <span class="math inline">\(p\)</span>-value less than 0.05, when there is a real difference (in this case an average of 5) between some of the means. <a href="#fig-8fpvaluedist">Figure&nbsp;<span>8.5</span></a> contains histograms of the <span class="math inline">\(p\)</span>-values:</p>
<div class="cell" data-fig.asp="0.5" data-hash="08-RMANOVA_cache/html/fig-8fpvaluedist_ec407eec1907439019ac5704306f8235">
<div class="cell-output-display">
<div id="fig-8fpvaluedist" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-RMANOVA_files/figure-html/fig-8fpvaluedist-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.5: <span class="math inline">\(p\)</span>-value distributions for a between and within-subjects ANOVA</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Here we have two distributions of observed p-values for the simulations. The red line shows the location of 0.05. Overall, we can see that for both designs, we got a full range of <span class="math inline">\(p\)</span>-values from 0 to 1. This means that many times we would not have rejected the hypothesis of no differences (even though we know there is a small difference). We would have rejected the null every time the <span class="math inline">\(p\)</span>-value was less than 0.05.</p>
<p>For the between subject design, there were 584 experiments with a <span class="math inline">\(p\)</span> less than 0.05, or 0.584 of experiments were “significant”, with alpha=.05.</p>
<p>For the within subject design, there were 569 experiments with a <span class="math inline">\(p\)</span> less than 0.05, or 0.569 of experiments were “significant”, with alpha=.05.</p>
<p>OK, well, you still might not be impressed. In this case, the between-subjects design detected the true effect slightly more often than the repeated measures design. Both them were right around 55% of the time. Based on this, we could say the two designs are pretty comparable in their sensitivity, or ability to detect a true difference when there is one.</p>
<p>However, remember that the between-subjects design uses 30 subjects, and the repeated measures design only uses 10. We had to make a big investment to get our 30 subjects. And, we’re kind of unfairly comparing the between design (which is more sensitive because it has more subjects) with the repeated measures design that has fewer subjects.</p>
<p>What do you think would happen if we ran 30 subjects in the repeated measures design? Let’s find out. <a href="#fig-8pdistwithin">Figure&nbsp;<span>8.6</span></a> re-plots the above, but this time only for the repeated measures design. We increase <span class="math inline">\(N\)</span> from 10 to 30.</p>
<div class="cell" data-fig.asp="0.5" data-hash="08-RMANOVA_cache/html/fig-8pdistwithin_13c974dbebd09d3b7b7341b1e9858b9d">
<div class="cell-output-display">
<div id="fig-8pdistwithin" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-RMANOVA_files/figure-html/fig-8pdistwithin-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.6: <span class="math inline">\(p\)</span>-value distribution for within-subjects design with <span class="math inline">\(n = 30\)</span></figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>Wowsers! Look at that. When we ran 30 subjects in the repeated measures design almost all of the <span class="math inline">\(p\)</span>-values were less than .05. There were 986 experiments with a <span class="math inline">\(p\)</span> less than 0.05, or 0.986 of experiments were “significant”, with alpha=.05. That’s huge! If we ran the repeated measures design, we would almost always detect the true difference when it is there. This is why the repeated measures design can be more sensitive than the between-subjects design.</p>
</section>
</section>
<section id="real-data" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="real-data"><span class="header-section-number">8.5</span> Real Data</h2>
<p>Let’s look at some real data from a published experiment that uses a repeated measures design. This is the same example that you will be using in the lab for repeated measures ANOVA. The data happen to be taken from a recent study conducted by Lawrence Behmer and myself, at Brooklyn College <span class="citation" data-cites="behmer2017spatial">(<a href="#ref-behmer2017spatial" role="doc-biblioref">Behmer and Crump 2017</a>)</span>.</p>
<p>We were interested in how people perform sequences of actions. One question is whether people learn individual parts of actions, or the whole larger pattern of a sequence of actions. We looked at these issues in a computer keyboard typing task. One of our questions was whether we would replicate some well known findings about how people type words and letters.</p>
<p>From prior work we knew that people type words way faster than than random letters, but if you made the random letters a little bit more English-like, then people type those letter strings a little bit faster, but not as slow as random string.</p>
<p>In the study, 38 participants sat in front of a computer and typed 5 letter strings one at a time. Sometimes the 5 letter made a word (Normal condition, TRUCK), sometimes they were completely random (Random Condition, JWYFG), and sometimes they followed patterns like you find in English (Bigram Condition, QUEND), but were not actual words. So, the independent variable for the typing material had three levels. We measured every single keystroke that participants made. This gave us a few different dependent measures. Let’s take a look a the reaction times. This is how long it took for participants to start typing the first letter in the string.</p>
<div class="cell" data-fig.asp="0.5" data-hash="08-RMANOVA_cache/html/fig-8behmcrump_1ff90435e67207bce03d7423b9ed0297">
<div class="cell-output-display">
<div id="fig-8behmcrump" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="08-RMANOVA_files/figure-html/fig-8behmcrump-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
<p></p><figcaption class="figure-caption">Figure&nbsp;8.7: Results from Behmer &amp; Crump (2017)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>OK, I made a figure showing the mean reaction times for the different typing material conditions. You will notice that there are two sets of lines. That’s because there was another manipulation I didn’t tell you about. In one block of trials participants got to look at the keyboard while they typed, but in the other condition we covered up the keyboard so people had to type without looking. Finally, the error bars are standard error of the means.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note, the use of error bars for repeated-measures designs is not very straightforward. In fact the standard error of the means that we have added here are not very meaningful for judging whether the differences between the means are likely not due to chance. They would be if this was a between-subjects design. We will update this textbook with a longer discussion of this issue, for now we will just live with these error bars.</p>
</div>
</div>
<p>For the purpose of this example, we will say, it sure looks like the previous finding replicated. For example, people started typing Normal words faster than Bigram strings (English-like), and they started typing random letters the most slowly of all. Just like prior research had found.</p>
<p>Let’s focus only on the block of trials where participants were allowed to look at the keyboard while they typed, that’s the red line, for the “visible keyboard” block. We can see the means look different. Let’s next ask, what is the likelihood that chance (random sampling error) could have produced these mean differences. To do that we run a repeated-measures ANOVA in R. Here is the ANOVA table.</p>
<div class="cell" data-hash="08-RMANOVA_cache/html/unnamed-chunk-18_dcbb703a7d3afea83db5398df8d71a48">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">2452611.9</td>
<td style="text-align: right;">66286.808</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">Stimulus</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1424914.0</td>
<td style="text-align: right;">712457.010</td>
<td style="text-align: right;">235.7342</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residuals1</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">223649.4</td>
<td style="text-align: right;">3022.289</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Alright, we might report the results like this. There was a significant main effect of Stimulus type, F(2, 74) = 235.73, MSE = 3022.289, p &lt; 0.001.</p>
<p>Notice a couple things. First, this is a huge <span class="math inline">\(F\)</span>-value. It’s 253! Notice also that the p-value is listed as 0. That doesn’t mean there is zero chance of getting an F-value this big under the null. This is a rounding error. The true p-value is 0.00000000000000… The zeros keep going for a while. This means there is only a vanishingly small probability that these differences could have been produced by sampling error. So, we reject the idea that the differences between our means could be explained by chance. Instead, we are pretty confident, based on this evidence and and previous work showing the same thing, that our experimental manipulation caused the difference. In other words, people really do type normal words faster than random letters, and they type English-like strings somewhere in the middle in terms of speed.</p>
</section>
<section id="summary" class="level2" data-number="8.6">
<h2 data-number="8.6" class="anchored" data-anchor-id="summary"><span class="header-section-number">8.6</span> Summary</h2>
<p>In this chapter you were introduced to the repeated-measures ANOVA. This analysis is appropriate for within-subjects or repeated measures designs. The main difference between the independent factor ANOVA and the repeated measures ANOVA, is the ability to partial out variance due to the individual subject means. This can often result in the repeated-measures ANOVA being more sensitive to true effects than the between-subjects ANOVA.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-behmer2017spatial" class="csl-entry" role="listitem">
Behmer, Lawrence P, and Matthew JC Crump. 2017. <span>“Spatial Knowledge During Skilled Action Sequencing: <span>Hierarchical</span> Versus Nonhierarchical Representations.”</span> <em>Attention, Perception, &amp; Psychophysics</em> 79 (8): 2435–48. <a href="https://doi.org/10.3758/s13414-017-1389-3">https://doi.org/10.3758/s13414-017-1389-3</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./07-ANOVA.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ANOVA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./09-FactorialANOVA.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Factorial ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>