<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Programming for Psychologists: Data Creation and Analysis</title>
  <meta name="description" content="Tips on learning programming skills for experimental psychology">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="Programming for Psychologists: Data Creation and Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Tips on learning programming skills for experimental psychology" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Programming for Psychologists: Data Creation and Analysis" />
  
  <meta name="twitter:description" content="Tips on learning programming skills for experimental psychology" />
  

<meta name="author" content="Matthew J. C. Crump">


<meta name="date" content="2017-10-17">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="dealing-with-data.html">
<link rel="next" href="visualizing-the-data.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script type="text/javascript">
mattcrump=1;
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="tufte.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Programming</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html"><i class="fa fa-check"></i><b>1</b> Fundamentals of Computer Programming Languages</a><ul>
<li class="chapter" data-level="1.1" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#why-should-psychologists-learn-to-program"><i class="fa fa-check"></i><b>1.1</b> Why should Psychologists learn to program?</a></li>
<li class="chapter" data-level="1.2" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#learning-to-program"><i class="fa fa-check"></i><b>1.2</b> Learning to program</a><ul>
<li class="chapter" data-level="1.2.1" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#some-preliminaries"><i class="fa fa-check"></i><b>1.2.1</b> Some Preliminaries</a></li>
<li class="chapter" data-level="1.2.2" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#chicken-and-egg-problem"><i class="fa fa-check"></i><b>1.2.2</b> Chicken and Egg Problem</a></li>
<li class="chapter" data-level="1.2.3" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#understanding-the-tools-available-to-you"><i class="fa fa-check"></i><b>1.2.3</b> Understanding the tools available to you</a></li>
<li class="chapter" data-level="1.2.4" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#applying-the-tools-to-the-problems-you-want-to-solve"><i class="fa fa-check"></i><b>1.2.4</b> Applying the tools to the problems you want to solve</a></li>
<li class="chapter" data-level="1.2.5" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#being-a-good-coder"><i class="fa fa-check"></i><b>1.2.5</b> Being a good coder</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#foundational-concepts-in-computer-programming"><i class="fa fa-check"></i><b>1.3</b> Foundational concepts in computer programming</a><ul>
<li class="chapter" data-level="1.3.1" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#algorithms"><i class="fa fa-check"></i><b>1.3.1</b> Algorithms</a></li>
<li class="chapter" data-level="1.3.2" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#median-a-conceptual-algorithm"><i class="fa fa-check"></i><b>1.3.2</b> Median: A conceptual algorithm</a></li>
<li class="chapter" data-level="1.3.3" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#variables"><i class="fa fa-check"></i><b>1.3.3</b> Variables</a></li>
<li class="chapter" data-level="1.3.4" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#logic"><i class="fa fa-check"></i><b>1.3.4</b> Logic</a></li>
<li class="chapter" data-level="1.3.5" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#loops"><i class="fa fa-check"></i><b>1.3.5</b> Loops</a></li>
<li class="chapter" data-level="1.3.6" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#functions"><i class="fa fa-check"></i><b>1.3.6</b> Functions</a></li>
<li class="chapter" data-level="1.3.7" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#intrinsics"><i class="fa fa-check"></i><b>1.3.7</b> Intrinsics</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="fundamentals-of-computer-programming-languages.html"><a href="fundamentals-of-computer-programming-languages.html#what-is-the-computer-actually-doing-a-view-from-the-top"><i class="fa fa-check"></i><b>1.4</b> What is the computer actually doing? A view from the top</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="programming-in-r.html"><a href="programming-in-r.html"><i class="fa fa-check"></i><b>2</b> Programming in R</a><ul>
<li class="chapter" data-level="2.1" data-path="programming-in-r.html"><a href="programming-in-r.html#installing-r-and-r-studio"><i class="fa fa-check"></i><b>2.1</b> Installing R and R Studio</a><ul>
<li class="chapter" data-level="2.1.1" data-path="programming-in-r.html"><a href="programming-in-r.html#r-studio-notes-and-tips"><i class="fa fa-check"></i><b>2.1.1</b> R studio notes and tips</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="programming-in-r.html"><a href="programming-in-r.html#basic-math"><i class="fa fa-check"></i><b>2.2</b> Basic Math</a><ul>
<li class="chapter" data-level="2.2.1" data-path="programming-in-r.html"><a href="programming-in-r.html#precedence"><i class="fa fa-check"></i><b>2.2.1</b> Precedence</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="programming-in-r.html"><a href="programming-in-r.html#variables-1"><i class="fa fa-check"></i><b>2.3</b> Variables</a><ul>
<li class="chapter" data-level="2.3.1" data-path="programming-in-r.html"><a href="programming-in-r.html#numbers"><i class="fa fa-check"></i><b>2.3.1</b> Numbers</a></li>
<li class="chapter" data-level="2.3.2" data-path="programming-in-r.html"><a href="programming-in-r.html#integers"><i class="fa fa-check"></i><b>2.3.2</b> Integers</a></li>
<li class="chapter" data-level="2.3.3" data-path="programming-in-r.html"><a href="programming-in-r.html#numeric"><i class="fa fa-check"></i><b>2.3.3</b> Numeric</a></li>
<li class="chapter" data-level="2.3.4" data-path="programming-in-r.html"><a href="programming-in-r.html#vector"><i class="fa fa-check"></i><b>2.3.4</b> Vector</a></li>
<li class="chapter" data-level="2.3.5" data-path="programming-in-r.html"><a href="programming-in-r.html#matrices"><i class="fa fa-check"></i><b>2.3.5</b> Matrices</a></li>
<li class="chapter" data-level="2.3.6" data-path="programming-in-r.html"><a href="programming-in-r.html#strings"><i class="fa fa-check"></i><b>2.3.6</b> Strings</a></li>
<li class="chapter" data-level="2.3.7" data-path="programming-in-r.html"><a href="programming-in-r.html#arrays-lists-dataframes-factors-and-other-classes"><i class="fa fa-check"></i><b>2.3.7</b> Arrays, Lists, Dataframes, Factors and other classes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="programming-in-r.html"><a href="programming-in-r.html#logic-1"><i class="fa fa-check"></i><b>2.4</b> Logic</a><ul>
<li class="chapter" data-level="2.4.1" data-path="programming-in-r.html"><a href="programming-in-r.html#if-statements"><i class="fa fa-check"></i><b>2.4.1</b> IF statements</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="programming-in-r.html"><a href="programming-in-r.html#loops-1"><i class="fa fa-check"></i><b>2.5</b> Loops</a><ul>
<li class="chapter" data-level="2.5.1" data-path="programming-in-r.html"><a href="programming-in-r.html#for-loops"><i class="fa fa-check"></i><b>2.5.1</b> FOR Loops</a></li>
<li class="chapter" data-level="2.5.2" data-path="programming-in-r.html"><a href="programming-in-r.html#while-loops"><i class="fa fa-check"></i><b>2.5.2</b> WHILE loops</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="programming-in-r.html"><a href="programming-in-r.html#algorithms-1"><i class="fa fa-check"></i><b>2.6</b> Algorithms</a></li>
<li class="chapter" data-level="2.7" data-path="programming-in-r.html"><a href="programming-in-r.html#functions-1"><i class="fa fa-check"></i><b>2.7</b> Functions</a></li>
<li class="chapter" data-level="2.8" data-path="programming-in-r.html"><a href="programming-in-r.html#intrinsics-1"><i class="fa fa-check"></i><b>2.8</b> Intrinsics</a></li>
<li class="chapter" data-level="2.9" data-path="programming-in-r.html"><a href="programming-in-r.html#r-libraries"><i class="fa fa-check"></i><b>2.9</b> R Libraries</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html"><i class="fa fa-check"></i><b>3</b> Programming Challenges I: Learning the fundamentals</a><ul>
<li class="chapter" data-level="3.1" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#tips-for-approaching-the-problems"><i class="fa fa-check"></i><b>3.1</b> Tips for Approaching the Problems</a><ul>
<li class="chapter" data-level="3.1.1" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#rstudios-text-editor"><i class="fa fa-check"></i><b>3.1.1</b> Rstudio’s Text editor</a></li>
<li class="chapter" data-level="3.1.2" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#use-informative-variable-names."><i class="fa fa-check"></i><b>3.1.2</b> Use informative variable names.</a></li>
<li class="chapter" data-level="3.1.3" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#use-comments."><i class="fa fa-check"></i><b>3.1.3</b> Use comments.</a></li>
<li class="chapter" data-level="3.1.4" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#r-markdown."><i class="fa fa-check"></i><b>3.1.4</b> R Markdown.</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#use-hypothesis-to-annotate-your-solutions"><i class="fa fa-check"></i><b>3.2</b> Use Hypothesis to annotate your solutions</a></li>
<li class="chapter" data-level="3.3" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#easier-problems"><i class="fa fa-check"></i><b>3.3</b> Easier Problems</a></li>
<li class="chapter" data-level="3.4" data-path="programming-challenges-i-learning-the-fundamentals.html"><a href="programming-challenges-i-learning-the-fundamentals.html#harder-problems"><i class="fa fa-check"></i><b>3.4</b> Harder Problems</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="dealing-with-data.html"><a href="dealing-with-data.html"><i class="fa fa-check"></i><b>4</b> Dealing with Data</a><ul>
<li class="chapter" data-level="4.1" data-path="dealing-with-data.html"><a href="dealing-with-data.html#data"><i class="fa fa-check"></i><b>4.1</b> Data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="dealing-with-data.html"><a href="dealing-with-data.html#experiments-are-data-machines"><i class="fa fa-check"></i><b>4.1.1</b> Experiments are data machines</a></li>
<li class="chapter" data-level="4.1.2" data-path="dealing-with-data.html"><a href="dealing-with-data.html#what-is-data"><i class="fa fa-check"></i><b>4.1.2</b> What is Data?</a></li>
<li class="chapter" data-level="4.1.3" data-path="dealing-with-data.html"><a href="dealing-with-data.html#practical-issues-with-data-in-psychology"><i class="fa fa-check"></i><b>4.1.3</b> Practical issues with data in Psychology</a></li>
<li class="chapter" data-level="4.1.4" data-path="dealing-with-data.html"><a href="dealing-with-data.html#data-transformation-skills"><i class="fa fa-check"></i><b>4.1.4</b> Data Transformation Skills</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="dealing-with-data.html"><a href="dealing-with-data.html#standard-data-formats"><i class="fa fa-check"></i><b>4.2</b> Standard Data Formats</a></li>
<li class="chapter" data-level="4.3" data-path="dealing-with-data.html"><a href="dealing-with-data.html#examples-using-excel"><i class="fa fa-check"></i><b>4.3</b> Examples Using Excel</a><ul>
<li class="chapter" data-level="4.3.1" data-path="dealing-with-data.html"><a href="dealing-with-data.html#a-simple-detection-experiment"><i class="fa fa-check"></i><b>4.3.1</b> A simple detection experiment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html"><i class="fa fa-check"></i><b>5</b> Simulating and Analyzing Data in R</a><ul>
<li class="chapter" data-level="5.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#creating-a-sample-distribution"><i class="fa fa-check"></i><b>5.1</b> Creating a sample distribution</a><ul>
<li class="chapter" data-level="5.1.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#sampling-random-numbers-uniform-distribution"><i class="fa fa-check"></i><b>5.1.1</b> Sampling random numbers (uniform distribution)</a></li>
<li class="chapter" data-level="5.1.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#sampling-from-a-normal-distribution"><i class="fa fa-check"></i><b>5.1.2</b> Sampling from a normal distribution</a></li>
<li class="chapter" data-level="5.1.3" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#other-distributions"><i class="fa fa-check"></i><b>5.1.3</b> Other distributions</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#simulating-a-coin-toss"><i class="fa fa-check"></i><b>5.2</b> Simulating a coin toss</a></li>
<li class="chapter" data-level="5.3" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#t-testdata-simulation-and-analysis"><i class="fa fa-check"></i><b>5.3</b> t-test:Data Simulation and Analysis</a><ul>
<li class="chapter" data-level="5.3.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#simulating-a-one-sample-t-test"><i class="fa fa-check"></i><b>5.3.1</b> Simulating a one-sample t-test</a></li>
<li class="chapter" data-level="5.3.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#simulating-an-independent-samples-t-test-two-groups-between-subjects"><i class="fa fa-check"></i><b>5.3.2</b> Simulating an independent samples t-test (two groups, between-subjects)</a></li>
<li class="chapter" data-level="5.3.3" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#simulating-a-paired-samples-t-test-two-conditions-within-subjects"><i class="fa fa-check"></i><b>5.3.3</b> Simulating a paired samples t-test (two conditions, within-subjects)</a></li>
<li class="chapter" data-level="5.3.4" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#generality-of-the-t-test-examples"><i class="fa fa-check"></i><b>5.3.4</b> Generality of the t-test examples</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#formatting-data-in-r-for-more-complex-designs"><i class="fa fa-check"></i><b>5.4</b> Formatting data in R for more complex designs</a></li>
<li class="chapter" data-level="5.5" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#single-factor-anovas-data-simulation-and-analysis"><i class="fa fa-check"></i><b>5.5</b> Single Factor ANOVAs: Data-Simulation and Analysis</a><ul>
<li class="chapter" data-level="5.5.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#simulating-data-for-a-one-way-within-subjects-anova-with-3-levels"><i class="fa fa-check"></i><b>5.5.1</b> Simulating data for a one-way within subjects ANOVA with 3 levels</a></li>
<li class="chapter" data-level="5.5.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#simulating-data-for-a-one-way-between-subjects-design-with-3-levels"><i class="fa fa-check"></i><b>5.5.2</b> Simulating data for a one-way between subjects design with 3 levels</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#using-the-aov-function-for-within-or-between-subjects-designs"><i class="fa fa-check"></i><b>5.6</b> Using the aov function for within or between-subjects designs</a><ul>
<li class="chapter" data-level="5.6.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#between-subjects-anova-formulas"><i class="fa fa-check"></i><b>5.6.1</b> Between subjects ANOVA formulas</a></li>
<li class="chapter" data-level="5.6.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#within-subjects-anova-formulas-all-factors-within"><i class="fa fa-check"></i><b>5.6.2</b> Within subjects ANOVA formulas (all factors within)</a></li>
<li class="chapter" data-level="5.6.3" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#mixed-design-anovas-with-between-and-within-factors"><i class="fa fa-check"></i><b>5.6.3</b> Mixed design ANOVAs with between and within factors</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#simulating-data-for-multi-factor-designs"><i class="fa fa-check"></i><b>5.7</b> Simulating data for multi-factor designs</a><ul>
<li class="chapter" data-level="5.7.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#x2-between-subjects-design"><i class="fa fa-check"></i><b>5.7.1</b> 2x2 between subjects design</a></li>
<li class="chapter" data-level="5.7.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#x2-within-subjects-designs"><i class="fa fa-check"></i><b>5.7.2</b> 2x2 within subjects designs</a></li>
<li class="chapter" data-level="5.7.3" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#x2-mixed-design-1-within-1-between"><i class="fa fa-check"></i><b>5.7.3</b> 2x2 mixed design (1 within, 1 between)</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#power-analysis-and-sample-size-planning-by-monte-carlo-simulation"><i class="fa fa-check"></i><b>5.8</b> Power analysis and sample-size planning by Monte Carlo simulation</a><ul>
<li class="chapter" data-level="5.8.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#monte-carlo-one-sample-t-test-simulation"><i class="fa fa-check"></i><b>5.8.1</b> Monte-Carlo one-sample T-test Simulation</a></li>
<li class="chapter" data-level="5.8.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#monte-carlo-paired-t-test-simulation"><i class="fa fa-check"></i><b>5.8.2</b> Monte-Carlo paired T-test Simulation</a></li>
<li class="chapter" data-level="5.8.3" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#monte-carlo-one-way-repeated-measures-simulation"><i class="fa fa-check"></i><b>5.8.3</b> Monte-Carlo One-way Repeated Measures Simulation</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#analysing-data-from-a-file"><i class="fa fa-check"></i><b>5.9</b> Analysing data from a file</a></li>
<li class="chapter" data-level="5.10" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#reading-data-into-r"><i class="fa fa-check"></i><b>5.10</b> Reading data into R</a></li>
<li class="chapter" data-level="5.11" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#running-an-anova-for-a-single-factor-design-between-subjects-design"><i class="fa fa-check"></i><b>5.11</b> Running an ANOVA for a single-factor design between-subjects design</a><ul>
<li class="chapter" data-level="5.11.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#prettier-results-using-kable-and-broom"><i class="fa fa-check"></i><b>5.11.1</b> Prettier results using kable and broom</a></li>
<li class="chapter" data-level="5.11.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#writing-up-the-results"><i class="fa fa-check"></i><b>5.11.2</b> Writing up the results</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#running-a-between-subjects-anova-for-a-2x2-factorial-design"><i class="fa fa-check"></i><b>5.12</b> Running a between subjects ANOVA for a 2x2 Factorial design</a><ul>
<li class="chapter" data-level="5.12.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#writing-up-the-results-section"><i class="fa fa-check"></i><b>5.12.1</b> Writing up the results section</a></li>
</ul></li>
<li class="chapter" data-level="5.13" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#practice-problems"><i class="fa fa-check"></i><b>5.13</b> Practice Problems</a><ul>
<li class="chapter" data-level="5.13.1" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#single-factor-design-with-a-within-subjects-factor"><i class="fa fa-check"></i><b>5.13.1</b> Single factor design with a within-subjects factor</a></li>
<li class="chapter" data-level="5.13.2" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#x2-within-subjects-design"><i class="fa fa-check"></i><b>5.13.2</b> 2x2 within-subjects design</a></li>
</ul></li>
<li class="chapter" data-level="5.14" data-path="simulating-and-analyzing-data-in-r.html"><a href="simulating-and-analyzing-data-in-r.html#loading-raw-data-into-r"><i class="fa fa-check"></i><b>5.14</b> Loading raw-data into R</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html"><i class="fa fa-check"></i><b>6</b> Visualizing the Data</a><ul>
<li class="chapter" data-level="6.1" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html#graphing-results-in-r"><i class="fa fa-check"></i><b>6.1</b> Graphing results in R</a><ul>
<li class="chapter" data-level="6.1.1" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html#install-the-ggplot2-package"><i class="fa fa-check"></i><b>6.1.1</b> Install the ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html#simulating-analyzing-and-graphing-the-results-from-a-2x4-within-subjects-design"><i class="fa fa-check"></i><b>6.2</b> Simulating, analyzing, and graphing the results from a 2x4 within-subjects design</a></li>
<li class="chapter" data-level="6.3" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html#graphing-the-data-using-ggplot2"><i class="fa fa-check"></i><b>6.3</b> Graphing the data using ggplot2</a><ul>
<li class="chapter" data-level="6.3.1" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html#the-ggplot2-layer-metaphor-for-graphing-data"><i class="fa fa-check"></i><b>6.3.1</b> The ggplot2 layer metaphor for graphing data</a></li>
<li class="chapter" data-level="6.3.2" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html#changing-labels-and-making-a-journal-ready-figure"><i class="fa fa-check"></i><b>6.3.2</b> Changing labels and making a journal-ready figure</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="visualizing-the-data.html"><a href="visualizing-the-data.html#adding-error-bars-to-figures-in-ggplot2"><i class="fa fa-check"></i><b>6.4</b> Adding error bars to figures in ggplot2</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="programming-challenges-ii-data.html"><a href="programming-challenges-ii-data.html"><i class="fa fa-check"></i><b>7</b> Programming Challenges II: Data</a><ul>
<li class="chapter" data-level="7.1" data-path="programming-challenges-ii-data.html"><a href="programming-challenges-ii-data.html#creating-and-analyzing-simulated-data"><i class="fa fa-check"></i><b>7.1</b> Creating and Analyzing Simulated Data</a></li>
<li class="chapter" data-level="7.2" data-path="programming-challenges-ii-data.html"><a href="programming-challenges-ii-data.html#working-with-real-raw-data"><i class="fa fa-check"></i><b>7.2</b> Working with Real Raw Data</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="livecode-experiments.html"><a href="livecode-experiments.html"><i class="fa fa-check"></i><b>8</b> LIVECODE experiments</a><ul>
<li class="chapter" data-level="8.1" data-path="livecode-experiments.html"><a href="livecode-experiments.html#download-livecode"><i class="fa fa-check"></i><b>8.1</b> Download LIVECODE</a></li>
<li class="chapter" data-level="8.2" data-path="livecode-experiments.html"><a href="livecode-experiments.html#what-is-livecode"><i class="fa fa-check"></i><b>8.2</b> What is LIVECODE</a></li>
<li class="chapter" data-level="8.3" data-path="livecode-experiments.html"><a href="livecode-experiments.html#basic-livecode-concepts"><i class="fa fa-check"></i><b>8.3</b> Basic LIVECODE concepts</a><ul>
<li class="chapter" data-level="8.3.1" data-path="livecode-experiments.html"><a href="livecode-experiments.html#stacks-cards-and-elements"><i class="fa fa-check"></i><b>8.3.1</b> Stacks, Cards and Elements</a></li>
<li class="chapter" data-level="8.3.2" data-path="livecode-experiments.html"><a href="livecode-experiments.html#scripting"><i class="fa fa-check"></i><b>8.3.2</b> Scripting</a></li>
<li class="chapter" data-level="8.3.3" data-path="livecode-experiments.html"><a href="livecode-experiments.html#livecode-syntax"><i class="fa fa-check"></i><b>8.3.3</b> LIVECODE syntax</a></li>
<li class="chapter" data-level="8.3.4" data-path="livecode-experiments.html"><a href="livecode-experiments.html#manipulating-words-and-letters-strings"><i class="fa fa-check"></i><b>8.3.4</b> Manipulating words and letters (strings)</a></li>
<li class="chapter" data-level="8.3.5" data-path="livecode-experiments.html"><a href="livecode-experiments.html#manipulating-numbers-items"><i class="fa fa-check"></i><b>8.3.5</b> Manipulating numbers (items)</a></li>
<li class="chapter" data-level="8.3.6" data-path="livecode-experiments.html"><a href="livecode-experiments.html#advanced-data-storage-arrays"><i class="fa fa-check"></i><b>8.3.6</b> Advanced data storage (arrays)</a></li>
<li class="chapter" data-level="8.3.7" data-path="livecode-experiments.html"><a href="livecode-experiments.html#logic-statements-if-then"><i class="fa fa-check"></i><b>8.3.7</b> Logic statements (IF THEN)</a></li>
<li class="chapter" data-level="8.3.8" data-path="livecode-experiments.html"><a href="livecode-experiments.html#loops-2"><i class="fa fa-check"></i><b>8.3.8</b> Loops</a></li>
<li class="chapter" data-level="8.3.9" data-path="livecode-experiments.html"><a href="livecode-experiments.html#functions-2"><i class="fa fa-check"></i><b>8.3.9</b> Functions</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="livecode-experiments.html"><a href="livecode-experiments.html#practice-coding"><i class="fa fa-check"></i><b>8.4</b> Practice coding</a><ul>
<li class="chapter" data-level="8.4.1" data-path="livecode-experiments.html"><a href="livecode-experiments.html#livecode-features-checklist"><i class="fa fa-check"></i><b>8.4.1</b> LIVECODE features checklist</a></li>
<li class="chapter" data-level="8.4.2" data-path="livecode-experiments.html"><a href="livecode-experiments.html#using-the-interface"><i class="fa fa-check"></i><b>8.4.2</b> Using the interface</a></li>
<li class="chapter" data-level="8.4.3" data-path="livecode-experiments.html"><a href="livecode-experiments.html#livecode-commands"><i class="fa fa-check"></i><b>8.4.3</b> LIVECODE commands</a></li>
<li class="chapter" data-level="8.4.4" data-path="livecode-experiments.html"><a href="livecode-experiments.html#simple-programming-problems"><i class="fa fa-check"></i><b>8.4.4</b> Simple programming problems</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="livecode-experiments.html"><a href="livecode-experiments.html#logic-for-programming-experiments"><i class="fa fa-check"></i><b>8.5</b> Logic for programming experiments</a><ul>
<li class="chapter" data-level="8.5.1" data-path="livecode-experiments.html"><a href="livecode-experiments.html#experiments-are-designed-to-create-data-files"><i class="fa fa-check"></i><b>8.5.1</b> Experiments are designed to create data-files</a></li>
<li class="chapter" data-level="8.5.2" data-path="livecode-experiments.html"><a href="livecode-experiments.html#long-format-data-files"><i class="fa fa-check"></i><b>8.5.2</b> Long-format data files</a></li>
<li class="chapter" data-level="8.5.3" data-path="livecode-experiments.html"><a href="livecode-experiments.html#the-data-file-is-the-design"><i class="fa fa-check"></i><b>8.5.3</b> The Data-file is the Design</a></li>
<li class="chapter" data-level="8.5.4" data-path="livecode-experiments.html"><a href="livecode-experiments.html#creating-the-list-of-trials"><i class="fa fa-check"></i><b>8.5.4</b> Creating the list of trials</a></li>
<li class="chapter" data-level="8.5.5" data-path="livecode-experiments.html"><a href="livecode-experiments.html#interpeting-the-list-to-run-each-trial"><i class="fa fa-check"></i><b>8.5.5</b> Interpeting the list to run each trial</a></li>
<li class="chapter" data-level="8.5.6" data-path="livecode-experiments.html"><a href="livecode-experiments.html#presenting-a-stimulus"><i class="fa fa-check"></i><b>8.5.6</b> Presenting a stimulus</a></li>
<li class="chapter" data-level="8.5.7" data-path="livecode-experiments.html"><a href="livecode-experiments.html#collecting-a-response"><i class="fa fa-check"></i><b>8.5.7</b> Collecting a response</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="livecode-experiments.html"><a href="livecode-experiments.html#look-and-feel"><i class="fa fa-check"></i><b>8.6</b> Look and feel</a><ul>
<li class="chapter" data-level="8.6.1" data-path="livecode-experiments.html"><a href="livecode-experiments.html#preventing-unwanted-actions"><i class="fa fa-check"></i><b>8.6.1</b> Preventing unwanted actions</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="livecode-experiments.html"><a href="livecode-experiments.html#saving-the-data"><i class="fa fa-check"></i><b>8.7</b> Saving the data</a></li>
<li class="chapter" data-level="8.8" data-path="livecode-experiments.html"><a href="livecode-experiments.html#data-analysis"><i class="fa fa-check"></i><b>8.8</b> Data-analysis</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="web-experiments.html"><a href="web-experiments.html"><i class="fa fa-check"></i><b>9</b> Web Experiments</a><ul>
<li class="chapter" data-level="9.1" data-path="web-experiments.html"><a href="web-experiments.html#getting-started-html-javascript-jquery"><i class="fa fa-check"></i><b>9.1</b> Getting started: HTML, Javascript, JQUERY</a></li>
<li class="chapter" data-level="9.2" data-path="web-experiments.html"><a href="web-experiments.html#basic-html"><i class="fa fa-check"></i><b>9.2</b> Basic HTML</a></li>
<li class="chapter" data-level="9.3" data-path="web-experiments.html"><a href="web-experiments.html#javascript-basics"><i class="fa fa-check"></i><b>9.3</b> Javascript Basics</a><ul>
<li class="chapter" data-level="9.3.1" data-path="web-experiments.html"><a href="web-experiments.html#variables-2"><i class="fa fa-check"></i><b>9.3.1</b> Variables</a></li>
<li class="chapter" data-level="9.3.2" data-path="web-experiments.html"><a href="web-experiments.html#variable-types"><i class="fa fa-check"></i><b>9.3.2</b> Variable Types</a></li>
<li class="chapter" data-level="9.3.3" data-path="web-experiments.html"><a href="web-experiments.html#common-operations"><i class="fa fa-check"></i><b>9.3.3</b> Common operations</a></li>
<li class="chapter" data-level="9.3.4" data-path="web-experiments.html"><a href="web-experiments.html#loops-3"><i class="fa fa-check"></i><b>9.3.4</b> Loops</a></li>
<li class="chapter" data-level="9.3.5" data-path="web-experiments.html"><a href="web-experiments.html#logic-2"><i class="fa fa-check"></i><b>9.3.5</b> Logic</a></li>
<li class="chapter" data-level="9.3.6" data-path="web-experiments.html"><a href="web-experiments.html#writing-a-function"><i class="fa fa-check"></i><b>9.3.6</b> Writing a function</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="web-experiments.html"><a href="web-experiments.html#programming-a-simple-stroop-experiment"><i class="fa fa-check"></i><b>9.4</b> Programming a simple Stroop Experiment</a><ul>
<li class="chapter" data-level="9.4.1" data-path="web-experiments.html"><a href="web-experiments.html#implementing-the-design"><i class="fa fa-check"></i><b>9.4.1</b> Implementing the design</a></li>
<li class="chapter" data-level="9.4.2" data-path="web-experiments.html"><a href="web-experiments.html#coding-the-design-in-javascript"><i class="fa fa-check"></i><b>9.4.2</b> Coding the design in Javascript</a></li>
<li class="chapter" data-level="9.4.3" data-path="web-experiments.html"><a href="web-experiments.html#displaying-trials-on-screen"><i class="fa fa-check"></i><b>9.4.3</b> Displaying trials on screen</a></li>
<li class="chapter" data-level="9.4.4" data-path="web-experiments.html"><a href="web-experiments.html#next-steps-webstrooptutorial"><i class="fa fa-check"></i><b>9.4.4</b> Next steps: WebStroopTutorial</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="web-experiments.html"><a href="web-experiments.html#amazon-turk"><i class="fa fa-check"></i><b>9.5</b> Amazon Turk</a><ul>
<li class="chapter" data-level="9.5.1" data-path="web-experiments.html"><a href="web-experiments.html#create-an-account"><i class="fa fa-check"></i><b>9.5.1</b> Create an Account</a></li>
<li class="chapter" data-level="9.5.2" data-path="web-experiments.html"><a href="web-experiments.html#worker-site-requester-site-the-sandbox"><i class="fa fa-check"></i><b>9.5.2</b> Worker site, Requester site, &amp; the Sandbox</a></li>
<li class="chapter" data-level="9.5.3" data-path="web-experiments.html"><a href="web-experiments.html#basic-overview-of-interfacing-with-amazon-turk"><i class="fa fa-check"></i><b>9.5.3</b> Basic overview of interfacing with Amazon Turk</a></li>
<li class="chapter" data-level="9.5.4" data-path="web-experiments.html"><a href="web-experiments.html#download-the-command-line-tools"><i class="fa fa-check"></i><b>9.5.4</b> Download the Command Line Tools</a></li>
<li class="chapter" data-level="9.5.5" data-path="web-experiments.html"><a href="web-experiments.html#external-hit-sample-application"><i class="fa fa-check"></i><b>9.5.5</b> External Hit sample application</a></li>
<li class="chapter" data-level="9.5.6" data-path="web-experiments.html"><a href="web-experiments.html#running-the-example"><i class="fa fa-check"></i><b>9.5.6</b> Running the example</a></li>
<li class="chapter" data-level="9.5.7" data-path="web-experiments.html"><a href="web-experiments.html#running-the-example-in-the-terminal"><i class="fa fa-check"></i><b>9.5.7</b> Running the example in the terminal</a></li>
<li class="chapter" data-level="9.5.8" data-path="web-experiments.html"><a href="web-experiments.html#getting-results"><i class="fa fa-check"></i><b>9.5.8</b> Getting results</a></li>
<li class="chapter" data-level="9.5.9" data-path="web-experiments.html"><a href="web-experiments.html#approving-and-deleting"><i class="fa fa-check"></i><b>9.5.9</b> Approving and deleting</a></li>
<li class="chapter" data-level="9.5.10" data-path="web-experiments.html"><a href="web-experiments.html#general-points-about-the-example"><i class="fa fa-check"></i><b>9.5.10</b> General points about the example</a></li>
<li class="chapter" data-level="9.5.11" data-path="web-experiments.html"><a href="web-experiments.html#data-handling"><i class="fa fa-check"></i><b>9.5.11</b> Data handling</a></li>
<li class="chapter" data-level="9.5.12" data-path="web-experiments.html"><a href="web-experiments.html#loading-the-stroop-example-experiment-onto-amazon-turk"><i class="fa fa-check"></i><b>9.5.12</b> Loading the Stroop example experiment onto Amazon Turk</a></li>
<li class="chapter" data-level="9.5.13" data-path="web-experiments.html"><a href="web-experiments.html#steps-to-run-the-demo-on-amazon-turk"><i class="fa fa-check"></i><b>9.5.13</b> Steps to run the demo on Amazon Turk</a></li>
<li class="chapter" data-level="9.5.14" data-path="web-experiments.html"><a href="web-experiments.html#ready-to-load"><i class="fa fa-check"></i><b>9.5.14</b> Ready to Load!</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Programming for Psychologists: Data Creation and Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simulating-and-analyzing-data-in-r" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Simulating and Analyzing Data in R</h1>
<div id="creating-a-sample-distribution" class="section level2">
<h2><span class="header-section-number">5.1</span> Creating a sample distribution</h2>
<p>R has several built-in functions for sampling from different kinds of distributions. This makes it very easy to create simulated data. You can access these functions by typing “distribution” into R’s help. Because all of the examples involving simulating data will also involve sampling from distributions, it is worth spending some time on sampling from different distributions.</p>
<div id="sampling-random-numbers-uniform-distribution" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Sampling random numbers (uniform distribution)</h3>
<p>R generate lists of random numbers between a minimum and maximum value. One definition of a random number is the idea of a uniform distribution. In a uniform distribution, all of the possible numbers in the range have an equal chance of occurrence. The following code samples 100 numbers from the range between 0 and 100, using the runif function.</p>
<p>The syntax for runif is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(n, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>)</code></pre></div>
<p>n is the number of samples. The min and max are the lower and upper limits of the distribution. Here is the runif function in action.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">RandomNumbers &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">100</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">100</span>)</code></pre></div>
<p>Typing the above line into the terminal will sample 100 numbers betwen 0 and 100 and place them into the variable named RandomNumbers. If you then type RandomNumbers into the terminal and press enter, you will see the contents (all of the 100 numbers) displayed in the R terminal. By changing the values in the function you can make your sample of numbers any size, and make the range any size.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">RandomNumbers</code></pre></div>
<pre><code>##   [1] 21.5385069 24.1217537  5.5205319 98.6914350 56.0482205 19.0834504
##   [7] 41.5542824  9.0681762 86.2728300 19.7900222 51.1716209 31.8495827
##  [13] 61.1380349  0.6130128 47.3266298 64.1195175 75.2347539 44.9230373
##  [19]  1.8672902 80.5226092 73.2443550 42.2966262 72.4051937 63.7460291
##  [25] 44.5798928 13.3126147  0.6476694 53.1629358 48.4643196 12.5848893
##  [31] 77.0326327  9.0183387 31.1804438 16.0659276 31.8138681 31.2511057
##  [37]  2.2382184 10.6997486  2.2110644 81.4859002  0.6963449 92.6043166
##  [43] 43.0952458 97.9367697 30.3246824 11.0857920  5.7007622 76.9447100
##  [49] 31.5510164 81.9969214 47.8161891 20.2825969 10.5798439 57.0234205
##  [55]  5.1219866 51.8180070 79.5934065 76.7076199 97.6941437 26.8736460
##  [61] 10.2261277 99.2236801  6.9796426 71.1325564 59.4318171  3.2587463
##  [67] 57.7267511 87.0873878 62.1778032 73.6653679 53.6131297 11.4827671
##  [73] 54.9507030  0.9911769  9.0063479 29.3172139 80.2523126 86.2994477
##  [79] 86.6863397 87.7245990 69.2522622 50.7745496 78.8257404 90.4993603
##  [85] 23.2893591 51.6032850 67.7350153 84.4415316 94.5819981 93.6330210
##  [91] 69.5714108 15.3915163 36.9836267 21.0659561 57.5681849 92.2497975
##  [97] 44.5136476  5.3229517 69.7897812 86.3212093</code></pre>
<p>It is also very easy to view these numbers graphically. For example, you might to see if your sample actually looks like a uniform distribution. One way to do this would be to create a histrogram that shows the frequency of each number according to different bin sizes (e.g., frequency of numbers between 0 and 10, 11 and 20, and so on). If the sample is a uniform distribution, then the bars of the histogram ought to be approximately the same height (e.g., flat and uniform). A histogram can be created using the function hist.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(RandomNumbers)</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-49"></span>
<img src="Programming_Crump_files/figure-html/unnamed-chunk-49-1.png" alt="Histogram of small sample of random numbers" width="384" />
<p class="caption">
Figure 5.1: Histogram of small sample of random numbers
</p>
</div>
<p>Notice that some of the bars are higher than others, but overall the distribution is relatively flat and uniform. The fact that the distribution is not perfectly uniform shows that a sample distribution does not always look exactly like the parent distribution. This variability in the sample is due to chance. The effect of chance can be reduced by taking a larger sample. For example, the above code could be modified to sample 10,000 numbers rather than 100 numbers. This larger sample ought to produce a histogram that shows a more flat and uniform distribution. An example of a histogram for such a sample is shown below:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">RandomNumbers &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">10000</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">100</span>)
<span class="kw">hist</span>(RandomNumbers)</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-50"></span>
<img src="Programming_Crump_files/figure-html/unnamed-chunk-50-1.png" alt="Histogram of large sample of random numbers" width="384" />
<p class="caption">
Figure 5.2: Histogram of large sample of random numbers
</p>
</div>
<p>There is still some variability in the height of the bars, but overall this larger sample appears to have a more flat and uniform distribution. Again, this means that each of the numbers in the distribution have an equal chance occurrence. All of the other distributions covered here involve non-uniform distributions, where each value in the population has different likelihoods of occurrence.</p>
</div>
<div id="sampling-from-a-normal-distribution" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Sampling from a normal distribution</h3>
<p>The normal distribution (or bell-curve) can be sample by using the function rnorm. The syntax for rnorm is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(n, <span class="dt">mean =</span> <span class="dv">0</span>, <span class="dt">sd =</span> <span class="dv">1</span>)</code></pre></div>
<p>n is the number of samples, the mean is center of the distribution, and sd is the standard deviation of the distribution.</p>
<p>Let’s take 100 samples from a normal distribution with mean =100, and sd = 50, and plot the result in a histogram.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">normalSample &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">100</span>, <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="dv">50</span>)
<span class="kw">hist</span>(normalSample)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-52-1.png" width="384" /></p>
<p>The above histogram shows a bell-like curve typical of a normal distribution. If we take a much larger sample of 10,000 numbers, the bell-like curve will become even more apparent.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(<span class="kw">rnorm</span>(<span class="dv">10000</span>, <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="dv">50</span>))</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-53-1.png" width="384" /></p>
</div>
<div id="other-distributions" class="section level3">
<h3><span class="header-section-number">5.1.3</span> Other distributions</h3>
<p>R has functions for many other different kinds of distributions, including exponential, power, weibull, and many others. You can find the functions for these distributions in the help section. We will use the normal distribution for the tutorials here.</p>
</div>
</div>
<div id="simulating-a-coin-toss" class="section level2">
<h2><span class="header-section-number">5.2</span> Simulating a coin toss</h2>
<p>If you flip a fair coin 10 times, what are chance that you get 5 heads and 5 tails? What are the chances that you get 4 heads and 6 tails? What are the chances of the other possible combinations? We could figure out the answer mathematically, or we could use R to simulate the results of a coin toss. This simulation will demonstrate the use of loops in R. If you want to give yourself a challenge, which you should, then stop here and try to figure out how to solve this problem yourself before reading on.</p>
<p>The strategy for the simulation will involve the following steps. 1) flip a coin 10 times, 2) count the number of heads, and save the result, 3) repeat steps 1 and 2 several thousand times. Step 3 will produce a distribution showing how many times 1 heads, 2 heads, 3 heads, and so on occurred when a coin is flipped 10 times.</p>
<p>We already know how to sample from a uniform distribution, so let’s apply this knowledge to simulate flipping a coin 10 times. We can sample 10 numbers from a distribution between 0 and 1. Then we can evaluate each number. If it is &lt;=.5 we will call it a tails, and &gt;.5 a heads.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">coinToss &lt;-<span class="st"> </span><span class="kw">runif</span>(<span class="dv">10</span>, <span class="dt">min=</span><span class="dv">0</span>, <span class="dt">max=</span><span class="dv">1</span>)</code></pre></div>
<p>Then, we can use the round function to convert the decimal values into 0s or 1s.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">coinToss &lt;-<span class="st"> </span><span class="kw">round</span>(coinToss)</code></pre></div>
<p>Then, we can use the sum function to yield the total number of heads.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">totalHeads &lt;-<span class="st"> </span><span class="kw">sum</span>(coinToss)</code></pre></div>
<p>In fact, all of these operations could be done on one line in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">totalHeads &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="kw">round</span>(<span class="kw">runif</span>(<span class="dv">10</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>)))</code></pre></div>
<p>The next step is to use a loop in R to simulate a large number of cases where a coin is flipped 10 times, store the results of each set of flips, and then plot the histogram.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">allHeads &lt;-<span class="st"> </span><span class="kw">c</span>()
for (i in <span class="dv">1</span>:<span class="dv">10000</span>) {
  totalHeads &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="kw">round</span>(<span class="kw">runif</span>(<span class="dv">10</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>)))
  allHeads &lt;-<span class="st"> </span><span class="kw">c</span>(allHeads,totalHeads)
}
<span class="kw">hist</span>(allHeads)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-58-1.png" width="384" /> The above histogram shows the frequency of getting 0, 1, 2, 3 and so on heads out of 10 coin flips for 10,000 simulations.</p>
<p>The histogram function has an option to graph a probability density function as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(allHeads,<span class="dt">freq=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-59-1.png" width="384" /></p>
<p>The hist function has several options that you can configure. Notice that the two histograms above have gaps between the bars. For this histogram, R has automatically created bins of size .5. So, it is attempting to produce a bar at 0, .5, 1, 1.5, 2, and so on. The size of the bin is called breaks and can be set by the user. In this simulation there are 11 possible outcomes (0,1, 2, 3, 4,5 6, 7, 8, 9, or 10 heads), so it makes sense to set the breaks to 11.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">hist</span>(allHeads, <span class="dt">freq =</span> <span class="ot">FALSE</span>, <span class="dt">breaks =</span> <span class="dv">11</span>)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-60-1.png" width="384" /></p>
<p>A few other points are worth mentioning about the hist function. It is possible to save the results of the hist function to a variable or object. For example, we could use:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x&lt;-<span class="kw">hist</span>(allHeads, <span class="dt">freq =</span> <span class="ot">FALSE</span>, <span class="dt">breaks =</span> <span class="dv">11</span>)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-61-1.png" width="384" /> This line creates a variable x, and saves the results of the hist function to x. The variable x now contains the numerical details of the histogram. You can inspect these by typing x into the terminal and pressing enter. You should see a result like following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x</code></pre></div>
<pre><code>## $breaks
##  [1]  0  1  2  3  4  5  6  7  8  9 10
## 
## $counts
##  [1]  112  419 1184 2114 2501 2012 1132  432   82   12
## 
## $density
##  [1] 0.0112 0.0419 0.1184 0.2114 0.2501 0.2012 0.1132 0.0432 0.0082 0.0012
## 
## $mids
##  [1] 0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5
## 
## $xname
## [1] &quot;allHeads&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
<p>Each of the variables with a $ represent different components of the histogram. We can see that the breaks or bins are divided equally between 0 and 10, we can see the raw counts of number of heads in each bin, and we can see the probabilities for each number of heads in the density variable. Each of these variables can be listed individually.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x$breaks
x$counts
x$density</code></pre></div>
<p>The above lines of code show how to output each of the variables contained within the object x that is storing the results of the histogram. This basic idea will apply to data frames that will be encountered later when simulating more complex experimental designs.</p>
</div>
<div id="t-testdata-simulation-and-analysis" class="section level2">
<h2><span class="header-section-number">5.3</span> t-test:Data Simulation and Analysis</h2>
<div id="simulating-a-one-sample-t-test" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Simulating a one-sample t-test</h3>
<p>The purpose of a one-sample t-test is to determine whether the mean of a sample is statistically different from a population mean. Simulating the data simply involves taking some number of samples from a distribution, and then running a t-test to determine if the mean of the sample if different some other mean.</p>
<p>Consider simulating the test scores from a class of 10 students who completed a true/false quiz. Each of the students will have a percentage on their test. So, their test scores could range between 0 and 100%. One question to ask of these test scores is whether they are on average different from chance. If all of the students were guessing, the mean of all of the test scores should be not be statistically different from 50. If the students performed above chance then the mean of their scores should be significantly above 50. If we assume that the test scores are distributed normally, then it is possible to simulate 10 scores using the now familiar rnorm function (to sample from the normal distribution.</p>
<p>Let’s create a sample that assumes the students were guessing. This sample will have 10 scores, with a mean of 50. Let’s set the standard deviation to 20.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">testScores &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dt">mean =</span> <span class="dv">50</span>, <span class="dt">sd =</span> <span class="dv">20</span>)</code></pre></div>
<p>The above line of code will sample 10 numbers from the normal distribution above. However, there is a potential problem that needs to be addressed. It is possible for the rnorm function to sample numbers larger than 100 and smaller 0. These would be unlikely extreme values that are several standard deviations away from the mean, nevertheless they could be included in the sample. To address this problem, we can use logical operators in R to find and replace any numbers larger than 100 with the value 100, and any number smaller than 0 with the value 0.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">testScores[testScores &gt;<span class="st"> </span><span class="dv">100</span>] &lt;-<span class="st"> </span><span class="dv">100</span>
testScores[testScores &lt;<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="dv">0</span></code></pre></div>
<p>Now the variable testScores will only contain numbers between the range 0-100.</p>
<p>One first question is to determine the mean of sample. Use the mean function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(testScores)</code></pre></div>
<pre><code>## [1] 46.06487</code></pre>
<p>The next step is to perform a one-sample t-test to determine if the mean of the sample if statistically different from 50. A one-sample t-test can be computed using the t.test function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(testScores,<span class="dt">mu=</span><span class="dv">50</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  testScores
## t = -0.56472, df = 9, p-value = 0.5861
## alternative hypothesis: true mean is not equal to 50
## 95 percent confidence interval:
##  30.30155 61.82818
## sample estimates:
## mean of x 
##  46.06487</code></pre>
<p>In the above, mu refers to the population mean. Most likely the t-test will return a non-significant p-value. This makes sense because the sample was taken from a distribution with a mean of 50, so the sample mean should not be different from 50. However, because the number of samples was small (only 10), it is possible by chance alone to find a significant result. Let’s create a different sample of test scores with a mean of 80, and run a one-sample t-test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">testScores &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">10</span>, <span class="dt">mean =</span> <span class="dv">80</span>, <span class="dt">sd =</span> <span class="dv">20</span>)
testScores[testScores &gt;<span class="st"> </span><span class="dv">100</span>] &lt;-<span class="st"> </span><span class="dv">100</span>
testScores[testScores &lt;<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
<span class="kw">t.test</span>(testScores, <span class="dt">mu =</span> <span class="dv">50</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  testScores
## t = 9.8832, df = 9, p-value = 3.946e-06
## alternative hypothesis: true mean is not equal to 50
## 95 percent confidence interval:
##  74.87617 89.64421
## sample estimates:
## mean of x 
##  82.26019</code></pre>
<p>In this case, the t-test will usually return a significant result, and this makes sense because the sample was drawn from a distribution with a mean of 80, not 50. However, even though we sampled from a distribution with mean 80, it is possible by chance alone that the t-test will return a non-significant result. The main factors that influence whether or not a one-sample test returns a significant result are: 1) the size of the difference between the sample and population mean, 2) the number of subjects or scores in the sample, 3) the variance of the sample. Larger differences, larger number of subjects, and smaller variances all lead to significant differences. Smaller differences, smaller number of subjects, and larger variance all lead to non-significant differences.</p>
</div>
<div id="simulating-an-independent-samples-t-test-two-groups-between-subjects" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Simulating an independent samples t-test (two groups, between-subjects)</h3>
<p>The independent samples t-test is used to compare the differences between two groups of scores, specifically for between-subjects designs.</p>
<p>Consider a simple reaction time experiment where participants are asked to detect the onset of a light as fast as possible. In this experiment one group of 20 subjects performs the task after drinking alcohol. As well, a control group of 20 different subjects performs the task without drinking alcohol. The prediction is that mean reaction time should be slower for the alcohol group than the control group.</p>
<p>To simulate the data we need to create two samples of 20 fictitious reaction times, one for the alcohol group and one for the control group, and then perform an independent samples t-test. When creating the samples for each group it is important to set the means of the sample distribution to reflect the predictions of the design. The choice of means and standard deviations is somewhat arbitrary, and requires educated guessing. When simulating the data from an existing experiment, a good educated guess is the means and standard deviations reported in the manuscript. In this case, the particular numbers are chosen based on the fact that normal reaction times in a simple detection task are around 150 ms. We will use the rnorm function to create simulated reaction times.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Alcohol &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">250</span>, <span class="dt">sd =</span> <span class="dv">100</span>)
Control &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">150</span>, <span class="dt">sd =</span> <span class="dv">100</span>)</code></pre></div>
<p>Reaction times have a lower limit of 0ms, and no upper limit. So, it is important to ensure that none of the numbers in each of the reaction time samples are smaller than zero.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Alcohol[Alcohol &lt;<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
Control[Control &lt;<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="dv">0</span></code></pre></div>
<p>The next step is to conduct the independent samples t-test. This is done again using the t.test function (note: the syntax is slightly different from the one-sample test).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Alcohol,Control)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Alcohol and Control
## t = 3.1488, df = 37.951, p-value = 0.00319
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   31.61263 145.45979
## sample estimates:
## mean of x mean of y 
##  262.6054  174.0692</code></pre>
<p>Note the title of the t-test is called the Welch Two Sample t-test. This is the default t-test in R. If you were to run a t-test on the same scores in excel or SPSS, you find slightly different values. This is because the Welch test involves a statistical correction. It is possible to get the standard student’s t-test by setting the var.equal parameter as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Alcohol,Control, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Alcohol and Control
## t = 3.1488, df = 38, p-value = 0.003187
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   31.61506 145.45736
## sample estimates:
## mean of x mean of y 
##  262.6054  174.0692</code></pre>
<p>As you can see the results of the different versions of the t-tests are small. But, it is still a good idea to know which t-test you are performing. For all future t-tests in this tutorial, we will use the standard version, and always remember to set var.equal = TRUE. The t.test function has several other parameters that can be set (e.g., running a one vs. two-tailed test). These options can be found by looking up t.test in R help.</p>
</div>
<div id="simulating-a-paired-samples-t-test-two-conditions-within-subjects" class="section level3">
<h3><span class="header-section-number">5.3.3</span> Simulating a paired samples t-test (two conditions, within-subjects)</h3>
<p>A paired samples t-test is used for comparing data from two conditions in a within-subjects design (the same subjects contribute data to both of the conditions).</p>
<p>Imagine a learning experiment where 20 participants are asked to learn to type on a new computer keyboard with all of the keys re-arranged. They spend 1 hour practicing on day 1, and then 1 hour practicing on day 2. The prediction is that typing speeds will become faster with practice. So the mean typing speeds should be slower on day 1 than day 2. One measure of typing speed is words per minute. Skilled typists can type on average 65 WPM and up to over 100-200 WPM. The participants in this experiment will be starting from scratch, so let’s assume the mean WPM on day 1 will be around 20, and that they will make modest improvements to around 30 WPM on day 2. First, create two samples of 20 scores reflecting these predictions using rnorm.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">day1&lt;-<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">20</span>, <span class="dt">sd =</span> <span class="dv">5</span>)
day2&lt;-<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">30</span>, <span class="dt">sd =</span> <span class="dv">5</span>)</code></pre></div>
<p>These scores both have a lower limit of 0, so let’s ensure that all negative numbers are set to 0.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">day1[day1&lt;<span class="dv">0</span>]&lt;-<span class="dv">0</span>
day2[day2&lt;<span class="dv">0</span>]&lt;-<span class="dv">0</span></code></pre></div>
<p>Next, look at the means.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(day1)</code></pre></div>
<pre><code>## [1] 19.04195</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(day2)</code></pre></div>
<pre><code>## [1] 29.85374</code></pre>
<p>Finally, compute the paired-samples t-test using the t.test function. This will be the same as before, except the option for a paired test will be set to TRUE.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(day1, day2, <span class="dt">var.equal=</span><span class="ot">TRUE</span>, <span class="dt">paired=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  day1 and day2
## t = -7.2551, df = 19, p-value = 6.934e-07
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -13.930894  -7.692699
## sample estimates:
## mean of the differences 
##                -10.8118</code></pre>
</div>
<div id="generality-of-the-t-test-examples" class="section level3">
<h3><span class="header-section-number">5.3.4</span> Generality of the t-test examples</h3>
<p>The above examples illustrate specific cases of simulating and analyzing data for one-sample, independent sample, and paired-sample t-tests. The code can be extended to simulate data for any kind of experiment or set of data that should be analyzed by these tests. The only changes that need to be made are the names of the variables, and the predictions for the number of subjects, and means, standard deviations, or other parameters of the sampling distribution chosen to model the data.</p>
</div>
</div>
<div id="formatting-data-in-r-for-more-complex-designs" class="section level2">
<h2><span class="header-section-number">5.4</span> Formatting data in R for more complex designs</h2>
<p>The remaining portion of this tutorial covers simulating and analyzing data for between and within-subjects single factor designs, multi-factor designs, and mixed designs. All of these simulations will use the aov function to run ANOVAs on the simulated data. The aov function, like many other statistical functions in R, requires the data to be formatted in a specific fashion known as long-format. The data should also be stored in a particular kind of variable known in R as a data frame. Before continuing, it is worth discussing this kind of data formatting because it is fundamental to all of the remaining simulations. A complete understanding of formatting data in R will allow the user to create simulated data for most any design and conduct appropriate analyses on the simulated data.</p>
<p>Experimental designs involve manipulations and measurements. The manipulations are described by independent variables, and the measurements refer to dependent variables. Every independent variable has at least two levels, and possibly many more. In balanced designs there is one measurement (DV) for each of the levels of the independent variables. Thus, in order to represent the results of an experiment, it is necessary to organize the data so that the measurement for each level of each independent variable can be identified. Data is typically organized either in wide or long-format.</p>
<p>Here is an example of a wide-format organization for a single-factor design with 3 levels. It is a within-subjects design with 5 subjects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subjects  L1    L2  L3
<span class="dv">1</span>       <span class="dv">5</span>   <span class="dv">5</span>   <span class="dv">10</span>
<span class="dv">2</span>       <span class="dv">7</span>   <span class="dv">6</span>   <span class="dv">10</span>
<span class="dv">3</span>       <span class="dv">10</span>  <span class="dv">8</span>   <span class="dv">10</span>
<span class="dv">4</span>       <span class="dv">9</span>   <span class="dv">10</span>  <span class="dv">9</span>
<span class="dv">5</span>       <span class="dv">9</span>   <span class="dv">6</span>   <span class="dv">8</span></code></pre></div>
<p>The wide-format has four columns. The first column is for Subjects, and the remaining columns are for each of the levels of the independent variable. Each of the rows under the Subjects column refer to each of the 5 subjects, and the numbers under the columns Level 1 to 3 represent the measurements or dependent variable. This format perfectly preserves each of the measurements and assigns each measurement to a particular subject in a particular condition.</p>
<p>Here is an example of the same data organized in long-format.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subjects  IV    DV
<span class="dv">1</span>       L1  <span class="dv">5</span>
<span class="dv">2</span>       L1  <span class="dv">7</span>
<span class="dv">3</span>       L1  <span class="dv">10</span>
<span class="dv">4</span>       L1  <span class="dv">9</span>
<span class="dv">5</span>       L1  <span class="dv">9</span>
<span class="dv">1</span>       L2  <span class="dv">5</span>
<span class="dv">2</span>       L2  <span class="dv">6</span>
<span class="dv">3</span>       L2  <span class="dv">8</span>
<span class="dv">4</span>       L2  <span class="dv">10</span>
<span class="dv">5</span>       L2  <span class="dv">6</span>
<span class="dv">1</span>       L3  <span class="dv">10</span>
<span class="dv">2</span>       L3  <span class="dv">10</span>
<span class="dv">3</span>       L3  <span class="dv">6</span>
<span class="dv">4</span>       L3  <span class="dv">9</span>
<span class="dv">5</span>       L3  <span class="dv">8</span></code></pre></div>
<p>A defining feature of long-format data is that the DV is stored down the rows of a single column. This can lead to very long tables of data, especially when the design has many subjects and IVs with numerous levels.</p>
<p>In the above example, there is a single column for the subjects factor, a single column for the IV factor, and a single column for the DV. There is an important difference between the columns representing factors (Subject and IV) and the column representing the data or DV. The difference is that all of the numbers in the DV represent unique observations in each of the conditions. However, notice that terms in the rows of the subject and IV columns repeat. For the subject column, the numbers 1 to 5 are repeated three times. This is necessary because each of the subjects participates in each of the three conditions of the IV. Notice also that the terms for Level1, 2 and 3 are repeated 5 times each (once for each subject).</p>
<p>For each of the following simulations we will be constructing our own sets of data in long format. For each simulation it will be necessary to determine the total number of subjects, the total number of levels for each IV, and the total number of observations of the DV. These constraints will be used to create and organize each of the data sets.</p>
</div>
<div id="single-factor-anovas-data-simulation-and-analysis" class="section level2">
<h2><span class="header-section-number">5.5</span> Single Factor ANOVAs: Data-Simulation and Analysis</h2>
<div id="simulating-data-for-a-one-way-within-subjects-anova-with-3-levels" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Simulating data for a one-way within subjects ANOVA with 3 levels</h3>
<p>Let’s continue with the example of a simple practice study having participants learn to type on a new keyboard. In the paired sample t-test, participants practiced for one hour on day 1 and day 2. Let’s extend this design by including a day 3. Imagine the design involves 20 participants, and the DV is words per minute (WPM).</p>
<p>The first question is to determine the number of observations of the DV. The design has one IV with 3 levels, and 20 participants. Each participant contributes data to each of the levels. Thus, the number of observations is 3 x 20 = 60. This means that the column representing the DV will have 60 total numbers, one for each subject in each condition.</p>
<p>The first step is to simulate the data for each of the days. We can use the same formulas used from the paired sample t-test.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">day1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">20</span>, <span class="dt">sd =</span> <span class="dv">5</span>)
day2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">30</span>, <span class="dt">sd =</span> <span class="dv">5</span>)
day3 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">40</span>, <span class="dt">sd =</span> <span class="dv">5</span>)</code></pre></div>
<p>Don’t forget to set the negative numbers to 0.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">day1[day1 &lt;<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
day2[day2 &lt;<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="dv">0</span>
day3[day3 &lt;<span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="dv">0</span></code></pre></div>
<p>We now have three variables representing the mean words per minute for each subject for each day of practice. We can assume that the first number in each variable represents subject 1, the second number subject 2, and so on.</p>
<p>The next step is to combine each of these variables into a single variable that will eventually become a column representing all of the observations for the DV. This is simple in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">WPM &lt;-<span class="st"> </span><span class="kw">c</span>(day1,day2,day3)</code></pre></div>
<p>If you type the newly created variable WPM into the terminal and press enter, you will see a single list of 60 numbers. As the programmer, you know that the first 20 numbers represent the DV values for subjects 1-20 on day1, the 21-40th numbers represent the DV values for subjects 1-20 on day 2, and the 41-60th numbers represent the DV values for subjects 1-20 on day 3.</p>
<p>The next step is to create a variable that represents the subject factor. This variable should list the numbers 1-20 three times in a row. The R function seq is a convenient tool</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>)</code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20</code></pre>
<p>Use <code>seq</code> to make the list of 1-20 repeat three times.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subjects &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>), <span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>), <span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>))</code></pre></div>
<p>If you type Subjects into the terminal you will see the numbers 1-20 listed three times. Alternatively, you could combine the <code>rep</code> and <code>seq</code> functions.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subjects&lt;-<span class="kw">rep</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>),<span class="dv">3</span>)</code></pre></div>
<p>The Subjects variable is currently composed of 60 numbers. We will eventually be using the aov function to perform an ANOVA on our simulated data, and this function requires that the subject variable be treated as a factor in the ANOVA. This requires that we transform the Subjects variable into a different type of variable, that has the factor class. The current class of Subjects is integer. You can determine the class of a variable by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(Subjects)</code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>We can change Subjects into a factor class by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subjects&lt;-<span class="kw">factor</span>(Subjects)</code></pre></div>
<p>Now if you look at <code>class(Subjects)</code>, you should see that is <code>&quot;factor&quot;</code>. If a variable in R contains numbers it is not automatically given the factor class, so that class must be assigned in the script.</p>
<p>We now have a variable called WPM that represents the DV, and a variable Subjects that represents the subject factor. The remaining factor is the IV for practice. This has three levels, day1, day2, and day3. Given the way we have organized the data in the WPM variable, we know that the first 20 numbers are for day1, the second 20 numbers are for day 2, and the final set of 20 numbers are for day 3. Thus, we need to create a variable with the term day1 listed 20 times, followed by the term day2 listed 20 times, and then the term day3 listed 20 times. It is easy to do this using the function rep.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(<span class="st">&quot;day1&quot;</span>,<span class="dv">20</span>)</code></pre></div>
<pre><code>##  [1] &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot;
## [11] &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot; &quot;day1&quot;</code></pre>
<p>The Practice factor can be created in the following way:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Practice &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;day1&quot;</span>,<span class="dv">20</span>), <span class="kw">rep</span>(<span class="st">&quot;day2&quot;</span>,<span class="dv">20</span>), <span class="kw">rep</span>(<span class="st">&quot;day3&quot;</span>,<span class="dv">20</span>))</code></pre></div>
<p>If you now type Practice into the terminal you should see a list of 60 items, with day1 20 times, day2 20 times, and day3 20 times.</p>
<p>We have now created variables for every aspect of the design (Subjects, Practice, WPM). The next step is to combine these variables into a long-format table. This is done using the data.frame function. Data needs to be converted into a data frame format before using the aov function to compute the ANOVA. Fortunately, this is very easy. Let’s create the data frame and put it into a new variable called AllData</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AllData &lt;-<span class="st"> </span><span class="kw">data.frame</span>(Subjects,Practice,WPM)</code></pre></div>
<p>If you type AllData into the terminal, then you should see all of the simulated data presented in a long-format table. The first column will show the subject variable, with the numbers 1-20 repeated three times. The second column should show the Practice variable, with the names of each of the levels repeated 20 times each, and the third column should show the WPM variable, with 60 total observations.</p>
<p>The final step is to perform the one-way ANOVA. This will provide a test to determine whether there is a significant difference between the levels of the practice factor. Luckily, once the data has been formatted into a data frame, the ANOVA can be computed in one line of code using the aov function. Just like we did with the hist function, let’s store the results of aov function into a variable called ANOVAresults.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ANOVAresults &lt;-<span class="st"> </span><span class="kw">aov</span>(WPM~Practice +<span class="st"> </span><span class="kw">Error</span>(Subjects/Practice), AllData)</code></pre></div>
<p>Next, use the summary function to print the results of ANOVA to the terminal.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(ANOVAresults)</code></pre></div>
<pre><code>## 
## Error: Subjects
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals 19  648.7   34.14               
## 
## Error: Subjects:Practice
##           Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Practice   2   4441  2220.6   120.9 &lt;2e-16 ***
## Residuals 38    698    18.4                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>) </code></pre></div>
<pre><code>## Tables of means
## Grand mean
##          
## 29.31373 
## 
##  Practice 
## Practice
##  day1  day2  day3 
## 18.20 30.59 39.16</code></pre>
<p>Here is all the code for the simulation in one complete script:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">day1&lt;-<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">20</span>, <span class="dt">sd =</span> <span class="dv">5</span>)
day2&lt;-<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">30</span>, <span class="dt">sd =</span> <span class="dv">5</span>)
day3&lt;-<span class="kw">rnorm</span>(<span class="dv">20</span>, <span class="dt">mean =</span> <span class="dv">40</span>, <span class="dt">sd =</span> <span class="dv">5</span>)
day1[day1&lt;<span class="dv">0</span>]&lt;-<span class="dv">0</span>
day2[day2&lt;<span class="dv">0</span>]&lt;-<span class="dv">0</span>
day3[day3&lt;<span class="dv">0</span>]&lt;-<span class="dv">0</span>
WPM&lt;-<span class="kw">c</span>(day1,day2,day3)
Subjects&lt;-<span class="kw">c</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>), <span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>), <span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>))
Subjects&lt;-<span class="kw">factor</span>(Subjects)
Practice&lt;-<span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;day1&quot;</span>,<span class="dv">20</span>), <span class="kw">rep</span>(<span class="st">&quot;day2&quot;</span>,<span class="dv">20</span>), <span class="kw">rep</span>(<span class="st">&quot;day3&quot;</span>,<span class="dv">20</span>))
AllData&lt;-<span class="kw">data.frame</span>(Subjects,Practice,WPM)
ANOVAresults&lt;-<span class="kw">aov</span>(WPM~Practice +<span class="st"> </span><span class="kw">Error</span>(Subjects/Practice), AllData)
<span class="kw">summary</span>(ANOVAresults)
<span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>) </code></pre></div>
<p>This code can also be rewritten in a more compact form, for example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">WPM&lt;-<span class="kw">rnorm</span>(<span class="dv">60</span>,<span class="kw">c</span>(<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>),<span class="dv">5</span>)
WPM[WPM&lt;<span class="dv">0</span>]&lt;-<span class="dv">0</span>
Subjects&lt;-<span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>),<span class="dt">each=</span><span class="dv">3</span>))
Practice&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;day1&quot;</span>,<span class="st">&quot;day2&quot;</span>,<span class="st">&quot;day3&quot;</span>),<span class="dv">20</span>)
AllData&lt;-<span class="kw">data.frame</span>(Subjects,Practice,WPM)
ANOVAresults&lt;-<span class="kw">aov</span>(WPM~Practice +<span class="st"> </span><span class="kw">Error</span>(Subjects/Practice), AllData)
<span class="kw">summary</span>(ANOVAresults)
<span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>) </code></pre></div>
</div>
<div id="simulating-data-for-a-one-way-between-subjects-design-with-3-levels" class="section level3">
<h3><span class="header-section-number">5.5.2</span> Simulating data for a one-way between subjects design with 3 levels</h3>
<p>Consider the following between-subjects design with 60 subjects. The task is a memory experiment. Participants in the encoding phase read a list of 20 words, and are given a later test to recall as many words from the list as possible. The IV is the amount of time between the encoding phase and the test phase, and termed Delay. Group 1 is given the memory test immediately after reading the word list. Group 2 is given the memory test 1 hour after reading the word list. Group 3 is given the memory test 2 hours after reading the word list. Each group is composed of 20 different subjects. The prediction is that memory recall performance should decrease with longer delays. Group 1 should perform better than Group 2. And Group 2 should perform better than Group 3.</p>
<p>The DV could be the number of words recalled, this number would range between 0 and 20. There are 20 subjects and 2 conditions, so the DV should have 60 observations. The variables for the DV, and Subjects and Delay factors can be constructed in a similar manner to the previous example. The major difference being that the Subjects factor will contain the numbers 1-60, reflecting the fact that 60 different subjects completed the experiment. The following code creates the complete data frame and runs the ANOVA.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Recall&lt;-<span class="kw">c</span>(<span class="kw">rnorm</span>(<span class="dv">20</span>,<span class="dt">mean=</span><span class="dv">17</span>,<span class="dt">sd=</span><span class="dv">3</span>),<span class="kw">rnorm</span>(<span class="dv">20</span>,<span class="dt">mean=</span><span class="dv">15</span>,<span class="dt">sd=</span><span class="dv">3</span>),<span class="kw">rnorm</span>(<span class="dv">20</span>,<span class="dt">mean=</span><span class="dv">12</span>, <span class="dt">sd=</span><span class="dv">3</span>))
Recall[Recall&gt;<span class="dv">20</span>]&lt;-<span class="dv">20</span>
Recall[Recall&lt;<span class="dv">0</span>]&lt;-<span class="dv">0</span>
Subjects&lt;-<span class="kw">factor</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">60</span>))
Delay&lt;-<span class="kw">c</span>(<span class="kw">rep</span>(<span class="st">&quot;Immediate&quot;</span>,<span class="dv">20</span>), <span class="kw">rep</span>(<span class="st">&quot;1Hour&quot;</span>,<span class="dv">20</span>), <span class="kw">rep</span>(<span class="st">&quot;2Hour&quot;</span>,<span class="dv">20</span>))
AllData&lt;-<span class="kw">data.frame</span>(Subjects,Recall,Delay)
ANOVAresults&lt;-<span class="kw">aov</span>(Recall~Delay, AllData)
<span class="kw">summary</span>(ANOVAresults)
<span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>)</code></pre></div>
</div>
</div>
<div id="using-the-aov-function-for-within-or-between-subjects-designs" class="section level2">
<h2><span class="header-section-number">5.6</span> Using the aov function for within or between-subjects designs</h2>
<p>The aov function is used for within, between and mixed design ANOVAs. The aov formula has the following syntax:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(formula,dataframe)</code></pre></div>
<p>dataframe refers to the name of the variable containing the data. The formula parameter defines the nature of the ANOVA. Here are some examples of the formula for different single and multi-factor between subject designs. The term DV will refer the name of the dependent variable, and IV for the name of the independent variable.</p>
<div id="between-subjects-anova-formulas" class="section level3">
<h3><span class="header-section-number">5.6.1</span> Between subjects ANOVA formulas</h3>
<div id="single-factor-design" class="section level4">
<h4><span class="header-section-number">5.6.1.1</span> Single-factor design</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IV, dataframe)</code></pre></div>
</div>
<div id="ivs" class="section level4">
<h4><span class="header-section-number">5.6.1.2</span> 2 IVs</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IV1*IV2, dataframe)</code></pre></div>
</div>
<div id="ivs-1" class="section level4">
<h4><span class="header-section-number">5.6.1.3</span> 3 IVs</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IV1*IV2*IV3, dataframe)</code></pre></div>
<p>The main differences between these formulas are the additional IV variables. Each additional variable is multiplied to the others.</p>
<p>The aov formula changes in an important way for within-subjects designs. This is because within-subjects designs use an error term that incorporates the Subjects variable. This error term needs to be explicitly defined in the aov formula. It is also important that the subjects variable in the dataframe is defined as a factor. Here are some examples:</p>
</div>
</div>
<div id="within-subjects-anova-formulas-all-factors-within" class="section level3">
<h3><span class="header-section-number">5.6.2</span> Within subjects ANOVA formulas (all factors within)</h3>
<div id="single-factor-design-1" class="section level4">
<h4><span class="header-section-number">5.6.2.1</span> Single-factor design</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IV +<span class="st"> </span><span class="kw">Error</span>(Subjects/IV), dataframe)</code></pre></div>
</div>
<div id="ivs-2" class="section level4">
<h4><span class="header-section-number">5.6.2.2</span> 2 IVs</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IV1*IV2 +<span class="st"> </span><span class="kw">Error</span>(Subjects/IV1*IV2), dataframe)</code></pre></div>
</div>
<div id="ivs-3" class="section level4">
<h4><span class="header-section-number">5.6.2.3</span> 3 IVs</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IV1*IV2*IV3 +<span class="st"> </span><span class="kw">Error</span>(Subjects/IV1*IV2*IV3), dataframe)</code></pre></div>
</div>
</div>
<div id="mixed-design-anovas-with-between-and-within-factors" class="section level3">
<h3><span class="header-section-number">5.6.3</span> Mixed design ANOVAs with between and within factors</h3>
<p>For these examples IVB will refer to between subject variables, and IVW will refer to within subjects variables</p>
<div id="one-between-iv-and-one-within-iv" class="section level4">
<h4><span class="header-section-number">5.6.3.1</span> One between IV and one within IV</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IVB*IVW +<span class="st"> </span><span class="kw">Error</span>(Subjects/IVW), dataframe)</code></pre></div>
</div>
<div id="one-between-iv-and-two-within-ivs" class="section level4">
<h4><span class="header-section-number">5.6.3.2</span> One between IV and two Within IVs</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IVB*IVW1*IVW2 +<span class="st"> </span><span class="kw">Error</span>(Subjects/(IVW1*IVW2), dataframe)</code></pre></div>
</div>
<div id="two-between-ivs-and-two-within-ivs" class="section level4">
<h4><span class="header-section-number">5.6.3.3</span> Two between IVs and two Within IVs</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aov</span>(DV~IVB1*IVB2*IVW1*IVW2 +<span class="st"> </span><span class="kw">Error</span>(Subjects/(IVW1*IVW2)+(IVB1*IVB2), dataframe)</code></pre></div>
<p>note: in this last example an additional error term is added for the interaction between the two between subject variables.</p>
</div>
</div>
</div>
<div id="simulating-data-for-multi-factor-designs" class="section level2">
<h2><span class="header-section-number">5.7</span> Simulating data for multi-factor designs</h2>
<div id="x2-between-subjects-design" class="section level3">
<h3><span class="header-section-number">5.7.1</span> 2x2 between subjects design</h3>
<p>The following code assumes 20 subjects per group (80 total). IV1 has two levels. IV2 has two levels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">DV&lt;-<span class="kw">rnorm</span>(<span class="dv">80</span>,<span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">300</span>,<span class="dv">400</span>),<span class="dt">sd=</span><span class="dv">10</span>)
IV1&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;level1&quot;</span>,<span class="st">&quot;level2&quot;</span>),<span class="dt">each=</span><span class="dv">2</span>,<span class="dv">20</span>)
IV2&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;level1&quot;</span>,<span class="st">&quot;level2&quot;</span>),<span class="dt">each=</span><span class="dv">1</span>,<span class="dv">40</span>)
AllData&lt;-<span class="kw">data.frame</span>(DV,IV1,IV2)
ANOVAresults&lt;-<span class="kw">aov</span>(DV~IV1*IV2, AllData)
<span class="kw">summary</span>(ANOVAresults)
<span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>)</code></pre></div>
</div>
<div id="x2-within-subjects-designs" class="section level3">
<h3><span class="header-section-number">5.7.2</span> 2x2 within subjects designs</h3>
<p>The following code assumes 20 subjects participating in each condition. IV1 has two levels. IV2 has two levels.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subjects&lt;-<span class="kw">factor</span>(<span class="kw">rep</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>),<span class="dt">each=</span><span class="dv">4</span>))  
DV&lt;-<span class="kw">rnorm</span>(<span class="dv">80</span>,<span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">300</span>,<span class="dv">400</span>),<span class="dt">sd=</span><span class="dv">10</span>)
IV1&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;level1&quot;</span>,<span class="st">&quot;level2&quot;</span>),<span class="dt">each=</span><span class="dv">2</span>,<span class="dv">20</span>)
IV2&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;level1&quot;</span>,<span class="st">&quot;level2&quot;</span>),<span class="dt">each=</span><span class="dv">1</span>,<span class="dv">40</span>)
AllData&lt;-<span class="kw">data.frame</span>(DV,IV1,IV2)
ANOVAresults&lt;-<span class="kw">aov</span>(DV~IV1*IV2 +<span class="st"> </span><span class="kw">Error</span>(Subjects/(IV1*IV2)), AllData)
<span class="kw">summary</span>(ANOVAresults)
<span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>)</code></pre></div>
</div>
<div id="x2-mixed-design-1-within-1-between" class="section level3">
<h3><span class="header-section-number">5.7.3</span> 2x2 mixed design (1 within, 1 between)</h3>
<p>The following code assumes 40 total subjects. 20 participate in each level of IVB, and all participate in each level of IVW. IVB has two levels, IVW has two levels</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subjects&lt;-<span class="kw">factor</span>(<span class="kw">c</span>(<span class="kw">rep</span>(<span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">40</span>),<span class="dt">each=</span><span class="dv">2</span>)))
DV&lt;-<span class="kw">rnorm</span>(<span class="dv">80</span>,<span class="kw">c</span>(<span class="dv">100</span>,<span class="dv">200</span>,<span class="dv">300</span>,<span class="dv">400</span>),<span class="dt">sd=</span><span class="dv">10</span>)
IVB&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;level1&quot;</span>,<span class="st">&quot;level2&quot;</span>),<span class="dt">each=</span><span class="dv">2</span>,<span class="dv">20</span>)
IVW&lt;-<span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;level1&quot;</span>,<span class="st">&quot;level2&quot;</span>),<span class="dt">each=</span><span class="dv">1</span>,<span class="dv">40</span>)
AllData&lt;-<span class="kw">data.frame</span>(DV,IVB,IVW)
ANOVAresults&lt;-<span class="kw">aov</span>(DV~IVB*IVW +<span class="st"> </span><span class="kw">Error</span>(Subjects/(IVW)), AllData)
<span class="kw">summary</span>(ANOVAresults)
<span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>)</code></pre></div>
</div>
</div>
<div id="power-analysis-and-sample-size-planning-by-monte-carlo-simulation" class="section level2">
<h2><span class="header-section-number">5.8</span> Power analysis and sample-size planning by Monte Carlo simulation</h2>
<p>The above code blocks show examples of simulating data in a few different designs, and then analyzing the simulated data with an ANOVA. By repeating this process many times for any given design, we can estimate statistical properties of the design that should hold over the long run. For example, how often does the design produce a ‘significant’ (p&lt;.05) effect? This can be estimated by running 1000s of independent simulations, computing and saving the p-value from each simulation, and then determining the proportion of p-values less than .05 from the distribution of simulated p-values. In principle, long-run expectations for any other statistic of a simulated design could be estimated in this way as well. In addition, design simulations can be constructed down to the level of individual trial data for individual subjects, which can aid in sample-size and cell-size planning. Some example monte-carlo simulations are presented below.</p>
<div id="monte-carlo-one-sample-t-test-simulation" class="section level3">
<h3><span class="header-section-number">5.8.1</span> Monte-Carlo one-sample T-test Simulation</h3>
<p>The following simulates 25 sample means from a normal distribution (mu=100, sd=10), and then conducts a one-sample t-test against the population mean of 100. This is equivalent to simulating the null. The simulation is repeated 1000 times, each time the observed p-value is saved.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sims_to_run&lt;-<span class="dv">1000</span>
save_p &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">length=</span>sims_to_run)

for(i in <span class="dv">1</span>:sims_to_run){
sim_data &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">25</span>,<span class="dv">100</span>,<span class="dv">10</span>)
t.out &lt;-<span class="kw">t.test</span>(sim_data,<span class="dt">mu=</span><span class="dv">100</span>)
save_p[i] &lt;-<span class="st"> </span>t.out$p.value
}

<span class="kw">hist</span>(save_p)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-109-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proportion_sig&lt;-<span class="kw">length</span>(save_p[save_p&lt;.<span class="dv">05</span>])/sims_to_run
proportion_sig</code></pre></div>
<pre><code>## [1] 0.048</code></pre>
<p>As expected, the histogram of simulated p-values is roughly uniform, indicating that all possible p-values are equally likely. In other words, chance would be expected to produce p&lt;.05 about 5% of the time. The calculated proportion of significant values was 0.048. In general, as the number of simulated runs increases toward infinity, the estimated parameter should settle on it’s true expected value.</p>
</div>
<div id="monte-carlo-paired-t-test-simulation" class="section level3">
<h3><span class="header-section-number">5.8.2</span> Monte-Carlo paired T-test Simulation</h3>
<p>25 subjects, with expected mean 100 in Condition 1 and mean 110 in Condition 2, with standard deviation 30. This simulation includes a programmed difference of 10, so there is a true effect.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sims_to_run&lt;-<span class="dv">1000</span>
save_p &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">length=</span>sims_to_run)

for(i in <span class="dv">1</span>:sims_to_run){
condition_1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">25</span>,<span class="dv">100</span>,<span class="dv">30</span>)
condition_2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">25</span>,<span class="dv">110</span>,<span class="dv">30</span>)
t.out &lt;-<span class="kw">t.test</span>(condition_1,condition_2,<span class="dt">paired=</span><span class="ot">TRUE</span>,<span class="dt">var.equal =</span> <span class="ot">TRUE</span>)
save_p[i] &lt;-<span class="st"> </span>t.out$p.value
}

<span class="kw">hist</span>(save_p)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proportion_sig&lt;-<span class="kw">length</span>(save_p[save_p&lt;.<span class="dv">05</span>])/sims_to_run
proportion_sig</code></pre></div>
<pre><code>## [1] 0.199</code></pre>
<p>The histogram of p-values is skewed left, so this design is more likely to produce p&lt;.05 than not, but the statistical power (or proportion of significant simulations) is only 0.199.</p>
<p>To determine the number of subjects needed to achieve power = .8, you could fiddle with the number of subjects until you find the number, or you could add another loop to run multiple monte carlo simulations with difference numbers of subjects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">subject_numbers&lt;-<span class="kw">c</span>(<span class="dv">25</span>,<span class="dv">50</span>,<span class="dv">75</span>,<span class="dv">100</span>,<span class="dv">125</span>,<span class="dv">150</span>,<span class="dv">175</span>,<span class="dv">200</span>)

power&lt;-<span class="kw">vector</span>(<span class="dt">length=</span><span class="kw">length</span>(subject_numbers))
for(subnum in <span class="dv">1</span>:<span class="kw">length</span>(subject_numbers)){

  sims_to_run&lt;-<span class="dv">1000</span>
  save_p &lt;-<span class="st"> </span><span class="kw">vector</span>(<span class="dt">length=</span>sims_to_run)
  
  for(i in <span class="dv">1</span>:sims_to_run){
    condition_1 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(subject_numbers[subnum],<span class="dv">100</span>,<span class="dv">30</span>)
    condition_2 &lt;-<span class="st"> </span><span class="kw">rnorm</span>(subject_numbers[subnum],<span class="dv">110</span>,<span class="dv">30</span>)
    t.out &lt;-<span class="kw">t.test</span>(condition_1,condition_2,<span class="dt">paired=</span><span class="ot">TRUE</span>,<span class="dt">var.equal =</span> <span class="ot">TRUE</span>)
    save_p[i] &lt;-<span class="st"> </span>t.out$p.value
  }
  power[subnum]&lt;-<span class="kw">length</span>(save_p[save_p&lt;.<span class="dv">05</span>])/sims_to_run
}

power_table&lt;-<span class="kw">data.frame</span>(subject_numbers,power)
<span class="kw">kable</span>(power_table)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">subject_numbers</th>
<th align="right">power</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">25</td>
<td align="right">0.210</td>
</tr>
<tr class="even">
<td align="right">50</td>
<td align="right">0.362</td>
</tr>
<tr class="odd">
<td align="right">75</td>
<td align="right">0.525</td>
</tr>
<tr class="even">
<td align="right">100</td>
<td align="right">0.665</td>
</tr>
<tr class="odd">
<td align="right">125</td>
<td align="right">0.741</td>
</tr>
<tr class="even">
<td align="right">150</td>
<td align="right">0.818</td>
</tr>
<tr class="odd">
<td align="right">175</td>
<td align="right">0.887</td>
</tr>
<tr class="even">
<td align="right">200</td>
<td align="right">0.922</td>
</tr>
</tbody>
</table>
</div>
<div id="monte-carlo-one-way-repeated-measures-simulation" class="section level3">
<h3><span class="header-section-number">5.8.3</span> Monte-Carlo One-way Repeated Measures Simulation</h3>
<p>The above simulations estimated individual subject sample means by drawing values directly from distributions. The individual trial data for each subject can also be simulated if desired. This can be useful for design planning as both the number of subjects and cell-size determine the power of the design. Depending on the situation, increasing the number of trials may do more for improving the sensitivity of the design than increasing the number of subjects, or vice-versa. To illustrate, the following example simulates individual trial data for subjects in a Stroop experiment. The retimes package is used to generate RT distributions.</p>
<p>Before simulating an entire experiment it is worth simulating a Stroop effect for a single simulated subject. This shows the variance of Stroop effects given programmed values for the mean difference between congruent and incongruent trials, values of mu, sigma, and tau for the base RT distributions, as well as number of trials.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(retimes)</code></pre></div>
<pre><code>## Reaction Time Analysis (version 0.1-2)</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggplot2)

stroop_effects&lt;-<span class="kw">c</span>()
n_trials &lt;-<span class="st"> </span><span class="dv">144</span>
sim_mu &lt;-<span class="st"> </span><span class="dv">600</span>
sim_sigma &lt;-<span class="st"> </span><span class="dv">80</span>
sim_tau &lt;-<span class="st"> </span><span class="dv">150</span>
congruency_effect &lt;-<span class="st"> </span><span class="dv">100</span>
for(i in <span class="dv">1</span>:<span class="dv">1000</span>){
CongruentRTs &lt;-<span class="st"> </span><span class="kw">rexgauss</span>(n_trials,<span class="dt">mu=</span>sim_mu,<span class="dt">sigma=</span>sim_sigma,<span class="dt">tau=</span>sim_tau)
IncongruentRTs &lt;-<span class="st"> </span><span class="kw">rexgauss</span>(n_trials,<span class="dt">mu=</span>sim_mu+congruency_effect,<span class="dt">sigma=</span>sim_sigma,<span class="dt">tau=</span>sim_tau)
stroop_effects &lt;-<span class="st"> </span><span class="kw">c</span>(stroop_effects,<span class="kw">mean</span>(IncongruentRTs)-<span class="kw">mean</span>(CongruentRTs))
}
<span class="kw">qplot</span>(stroop_effects)+<span class="kw">xlab</span>(<span class="st">&quot;Simulated Stroop Effects&quot;</span>)+<span class="kw">geom_bar</span>(<span class="dt">fill=</span><span class="st">&quot;white&quot;</span>,<span class="dt">color=</span><span class="st">&quot;black&quot;</span>)</code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-112-1.png" width="672" /> The histogram shows that under the simulated parameters, the programmed Stroop effect of 100ms can easily take a value -from 50 to 150. The variance in the simulated Stroop effect for a single subject is determined by the variance in the underlying RT distributions for the congruent and incongruent conditions.</p>
<p>The following simulation expands on the above to model multiple subjects in a Stroop experiment. We start with a minimum number of 10 trials per condition, in an Experiment with 20 subjects, and programmed Stroop effect of 50ms.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sims_to_run&lt;-<span class="dv">100</span>

n_trials &lt;-<span class="st"> </span><span class="dv">10</span>
sim_mu &lt;-<span class="st"> </span><span class="dv">600</span>
sim_sigma &lt;-<span class="st"> </span><span class="dv">80</span>
sim_tau &lt;-<span class="st"> </span><span class="dv">150</span>
congruency_effect &lt;-<span class="st"> </span><span class="dv">50</span>
n_subjects &lt;-<span class="st"> </span><span class="dv">20</span>
save_p&lt;-<span class="kw">vector</span>(<span class="dt">length=</span>sims_to_run)

for(i in <span class="dv">1</span>:sims_to_run){
  all_subjects&lt;-<span class="kw">data.frame</span>()
  for(sub in <span class="dv">1</span>:n_subjects){
    CongruentRTs &lt;-<span class="st"> </span><span class="kw">rexgauss</span>(n_trials,<span class="dt">mu=</span>sim_mu,<span class="dt">sigma=</span>sim_sigma,<span class="dt">tau=</span>sim_tau)
    IncongruentRTs &lt;-<span class="st"> </span><span class="kw">rexgauss</span>(n_trials,<span class="dt">mu=</span>sim_mu+congruency_effect,<span class="dt">sigma=</span>sim_sigma,<span class="dt">tau=</span>sim_tau)
    temp_subject &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">subject=</span><span class="kw">rep</span>(sub,n_trials*<span class="dv">2</span>),
                               <span class="dt">condition=</span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;Congruent&quot;</span>,<span class="st">&quot;Incongruent&quot;</span>),<span class="dt">each=</span>n_trials),
                               <span class="dt">RTs=</span><span class="kw">c</span>(CongruentRTs,IncongruentRTs))
    all_subjects&lt;-<span class="kw">rbind</span>(all_subjects,temp_subject)
  }
mean_subject_data&lt;-<span class="kw">aggregate</span>(RTs~subject*condition,all_subjects,mean)
aov.out&lt;-<span class="kw">summary</span>(<span class="kw">aov</span>(RTs~condition+<span class="kw">Error</span>(subject/condition),mean_subject_data))
save_p[i]&lt;-aov.out[[<span class="dv">3</span>]][[<span class="dv">1</span>]][[<span class="dv">5</span>]][<span class="dv">1</span>]
}

<span class="kw">hist</span>(save_p)</code></pre></div>
<p><img src="Programming_Crump_files/figure-html/unnamed-chunk-113-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">proportion_sig&lt;-<span class="kw">length</span>(save_p[save_p&lt;.<span class="dv">05</span>])/sims_to_run</code></pre></div>
<p>Tith these minimum trial counts, the power is 0.26 to detect the Stroop effect. Estimated power will increase with increasing numbers of subjects and/or trials in the simulated design. The last simulation shows how power increases as function of increasing trial counts.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sims_to_run&lt;-<span class="dv">100</span>

n_trials &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">30</span>,<span class="dv">40</span>,<span class="dv">50</span>,<span class="dv">60</span>,<span class="dv">70</span>)
sim_mu &lt;-<span class="st"> </span><span class="dv">600</span>
sim_sigma &lt;-<span class="st"> </span><span class="dv">80</span>
sim_tau &lt;-<span class="st"> </span><span class="dv">150</span>
congruency_effect &lt;-<span class="st"> </span><span class="dv">50</span>
n_subjects &lt;-<span class="st"> </span><span class="dv">20</span>
save_p&lt;-<span class="kw">vector</span>(<span class="dt">length=</span>sims_to_run)
proportion_sig&lt;-<span class="kw">vector</span>(<span class="dt">length=</span><span class="kw">length</span>(n_trials))

for(trials in <span class="dv">1</span>:<span class="kw">length</span>(n_trials)){
  for(i in <span class="dv">1</span>:sims_to_run){
    all_subjects&lt;-<span class="kw">data.frame</span>()
    for(sub in <span class="dv">1</span>:n_subjects){
      CongruentRTs &lt;-<span class="st"> </span><span class="kw">rexgauss</span>(n_trials[trials],<span class="dt">mu=</span>sim_mu,<span class="dt">sigma=</span>sim_sigma,<span class="dt">tau=</span>sim_tau)
      IncongruentRTs &lt;-<span class="st"> </span><span class="kw">rexgauss</span>(n_trials[trials],<span class="dt">mu=</span>sim_mu+congruency_effect,<span class="dt">sigma=</span>sim_sigma,<span class="dt">tau=</span>sim_tau)
      temp_subject &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">subject=</span><span class="kw">rep</span>(sub,n_trials[trials]*<span class="dv">2</span>),
                                 <span class="dt">condition=</span><span class="kw">rep</span>(<span class="kw">c</span>(<span class="st">&quot;Congruent&quot;</span>,<span class="st">&quot;Incongruent&quot;</span>),<span class="dt">each=</span>n_trials[trials]),
                                 <span class="dt">RTs=</span><span class="kw">c</span>(CongruentRTs,IncongruentRTs))
      all_subjects&lt;-<span class="kw">rbind</span>(all_subjects,temp_subject)
    }
    mean_subject_data&lt;-<span class="kw">aggregate</span>(RTs~subject*condition,all_subjects,mean)
    aov.out&lt;-<span class="kw">summary</span>(<span class="kw">aov</span>(RTs~condition+<span class="kw">Error</span>(subject/condition),mean_subject_data))
    save_p[i]&lt;-aov.out[[<span class="dv">3</span>]][[<span class="dv">1</span>]][[<span class="dv">5</span>]][<span class="dv">1</span>]
  }
  proportion_sig[trials]&lt;-<span class="kw">length</span>(save_p[save_p&lt;.<span class="dv">05</span>])/sims_to_run
}

<span class="kw">kable</span>(<span class="kw">data.frame</span>(n_trials,proportion_sig))</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">n_trials</th>
<th align="right">proportion_sig</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">10</td>
<td align="right">0.33</td>
</tr>
<tr class="even">
<td align="right">20</td>
<td align="right">0.58</td>
</tr>
<tr class="odd">
<td align="right">30</td>
<td align="right">0.65</td>
</tr>
<tr class="even">
<td align="right">40</td>
<td align="right">0.78</td>
</tr>
<tr class="odd">
<td align="right">50</td>
<td align="right">0.82</td>
</tr>
<tr class="even">
<td align="right">60</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="right">70</td>
<td align="right">0.95</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="analysing-data-from-a-file" class="section level2">
<h2><span class="header-section-number">5.9</span> Analysing data from a file</h2>
<p>This tutorial comes with a folder containing several data files. All of these files are .txt files that you can open and view in any text editor. Each of the files has data formatted in a specific way, called long format. The first line of each file contains headers or names for each of the columns of data in the file. For example, The SingleFactor_Between.txt file contains 61 lines of text. The first few lines should like something like this (except the text file will not include the number signs).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AllData[<span class="dv">1</span>:<span class="dv">5</span>,]</code></pre></div>
<pre><code>##   Subjects    IV1       DV
## 1        1 Group1 620.3559
## 2        2 Group1 661.4570
## 3        3 Group1 394.6609
## 4        4 Group1 382.1381
## 5        5 Group1 360.9547</code></pre>
<p>The Subjects column refers to individual subjects in the data file. Each number corresponds to a unique subject. The IV1 column refers to the single independent variable or factor in this data file. There are three levels: Group1, Group2, and Group3. If you scroll down the lines of the data file you will see that subjects 1-20 are associated with Group1, subjects 21-40 are associated with Group2, and subjects 41-60 are associated with Group3. The final column DV stands for the dependent variable, and the numbers in this column represent mean values for each subject in each condition.</p>
</div>
<div id="reading-data-into-r" class="section level2">
<h2><span class="header-section-number">5.10</span> Reading data into R</h2>
<p>There are several ways to import data into R. We focus on using the read.table function (but see also scan). To use read.table you will need to tell R where it can find your data files. In R studio look at the bottom right panel, and find the “Files” tab. When you click on the “Files” tab you should see the current working directory. Use the file section to navigate to the folder on your computer that contains the data files. When you have succesfully done this you will see the data files listed in the bottom-right window. Now you want to set the current working directoy to this folder (that contains the data files). Choose the option “More”, listed underneath the “files” tab. You should see an option to “set as working directory”. Click this option. Now R will be able to find your data files.</p>
<p>The next step is to input the data file into a variable in R. If you have correctly set the working directory then type the second line of code into the R terminal on the bottom left window of R-studio, then press enter. The first line of code shows how the working directory can be set with a script.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AllData&lt;-<span class="kw">read.table</span>(<span class="st">&quot;RFiles/SingleFactor_Between.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)</code></pre></div>
<p>You should now see a variable called AllData appear in the workspace (top right window). If you type AllData into the terminal and press enter, you should see R list your data file in the terminal.</p>
</div>
<div id="running-an-anova-for-a-single-factor-design-between-subjects-design" class="section level2">
<h2><span class="header-section-number">5.11</span> Running an ANOVA for a single-factor design between-subjects design</h2>
<p>We have already used the aov function to conduct ANOVAs on our simulated data sets. The same function is used to anlayse data inputted into R. In this case, the data file that we have inputted is already structured in long-format, and R reads the data in as a dataframe object. So, to conduct the ANOVA we simply need to write the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(DV~IV1,AllData))</code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)  
## IV1          2 101780   50890   4.405 0.0166 *
## Residuals   57 658449   11552                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>In the above print-out, the Df column refers to degrees of freedom, Sum Sq refers to the sum of squares, Mean Sq refers to Mean squared error, F-value is the F-statistic, and Pr(&gt;F) is the p-value.</p>
<p>We can see that the p-value is .0166, indicating significance. This means that at least one of the three groups is significantly different from the others. However, the ANOVA alone does not tell us either the means of each group, or which ones are significantly different from each other. This requires specific comparisons between levels.</p>
<p>The summary function does not provide descriptive statistics, so we are unable to see the means for each condition. One option to view the means is to use thethe aggregate function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aggregate</span>(DV~IV1,AllData,mean)</code></pre></div>
<pre><code>##      IV1       DV
## 1 Group1 489.6141
## 2 Group2 554.9691
## 3 Group3 588.8501</code></pre>
<p>It is worth pointing out that although the summary function does not immediately display the means for each condition, it does create a data structure that represents this information. And, the means can be found using model.tables in the following way.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">aovResults&lt;-<span class="kw">aov</span>(DV~IV1,AllData)
<span class="kw">print</span>(<span class="kw">model.tables</span>(aovResults,<span class="st">&quot;means&quot;</span>),<span class="dt">digits=</span><span class="dv">6</span>)</code></pre></div>
<pre><code>## Tables of means
## Grand mean
##          
## 544.4778 
## 
##  IV1 
## IV1
##  Group1  Group2  Group3 
## 489.614 554.969 588.850</code></pre>
<p>We see that the mean for Group 1 is numerically smaller than the mean for Group 2, which is numerically smaller than the mean for Group 3. We can conclude, based on the ANOVA, that the largest and smallest means are different from each other, so we know that the mean for Group 1 was significantly smaller than the mean for Group 3. We need to perform a follow-up t-test to determine whether Group 1 is different from Group 2, and yet another test to determine if Group 2 is different from Group 3.</p>
<p>The design is between-subjects, so the appropriate t-test is an independent samples t-test. We can conduct this test comparing groups 1 and 2 using the t.test function as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(AllData[AllData$IV1==<span class="st">&quot;Group1&quot;</span>,]$DV,AllData[AllData$IV1==<span class="st">&quot;Group2&quot;</span>,]$DV,<span class="dt">var.equal=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  AllData[AllData$IV1 == &quot;Group1&quot;, ]$DV and AllData[AllData$IV1 == &quot;Group2&quot;, ]$DV
## t = -1.8763, df = 38, p-value = 0.06831
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -135.868485    5.158361
## sample estimates:
## mean of x mean of y 
##  489.6141  554.9691</code></pre>
<p>We see that the p-value is p=0.06831, which is not &lt;.05. So, Group 1 is not significantly different than Group 2.</p>
<p>We can run an additional t-test comparing Group 2 and Group 3 using the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(AllData[AllData$IV1==<span class="st">&quot;Group2&quot;</span>,]$DV,AllData[AllData$IV1==<span class="st">&quot;Group3&quot;</span>,]$DV,<span class="dt">var.equal=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  AllData[AllData$IV1 == &quot;Group2&quot;, ]$DV and AllData[AllData$IV1 == &quot;Group3&quot;, ]$DV
## t = -1.0867, df = 38, p-value = 0.284
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -96.99980  29.23777
## sample estimates:
## mean of x mean of y 
##  554.9691  588.8501</code></pre>
<p>Again, we see that the difference is not significant (p=.284). So Group 2 is not significantly different from Group 3.</p>
<div id="prettier-results-using-kable-and-broom" class="section level3">
<h3><span class="header-section-number">5.11.1</span> Prettier results using kable and broom</h3>
<p>The results of anovas or t-tests aren’t appealing look to at when they are printed to the console, and often look cluttered when printed to a .pdf or .html file using Rmarkdown. The kable function from the package knitr, and the xtable function from the xtable package can help with improving the look and feel of ANOVA and other tables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(knitr)
<span class="kw">library</span>(xtable)
aov.out &lt;-<span class="st"> </span><span class="kw">summary</span>(<span class="kw">aov</span>(DV~IV1,AllData))
<span class="kw">kable</span>(<span class="kw">xtable</span>(aov.out),<span class="dt">format=</span><span class="st">&#39;markdown&#39;</span>)</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Df</th>
<th align="right">Sum Sq</th>
<th align="right">Mean Sq</th>
<th align="right">F value</th>
<th align="right">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">IV1</td>
<td align="right">2</td>
<td align="right">101780.0</td>
<td align="right">50890.02</td>
<td align="right">4.405401</td>
<td align="right">0.0166327</td>
</tr>
<tr class="even">
<td align="left">Residuals</td>
<td align="right">57</td>
<td align="right">658448.8</td>
<td align="right">11551.73</td>
<td align="right">NA</td>
<td align="right">NA</td>
</tr>
</tbody>
</table>
<p>The results from t-tests can be prettified using broom</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(broom)
<span class="kw">kable</span>(<span class="kw">tidy</span>(<span class="kw">t.test</span>(DV~IV1,AllData[AllData$IV1!=<span class="st">&quot;Group1&quot;</span>,], <span class="dt">paired=</span><span class="ot">TRUE</span>)))</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">estimate</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">parameter</th>
<th align="right">conf.low</th>
<th align="right">conf.high</th>
<th align="left">method</th>
<th align="left">alternative</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">-33.88101</td>
<td align="right">-1.06247</td>
<td align="right">0.3013409</td>
<td align="right">19</td>
<td align="right">-100.6253</td>
<td align="right">32.86325</td>
<td align="left">Paired t-test</td>
<td align="left">two.sided</td>
</tr>
</tbody>
</table>
</div>
<div id="writing-up-the-results" class="section level3">
<h3><span class="header-section-number">5.11.2</span> Writing up the results</h3>
<p>The preceding section covered the steps of loading a data-file into R. The data-file was for a single-factor between subjects design with 3 levels, and 20 subjects per level. An ANOVA revealed a significant effect, and the post-hoc t-tests showed that the only significant result was between Group 1 and 2. With all of this information in hand it is now possible to write-up a complete results section for this analysis. Here is an example:</p>
<p>Mean reaction times for each subject in each condition were submitted to a one-way ANOVA. The main effect of group was significant, F(2,57) = 4.405, MSE = 11552, p&lt;.016. The mean reaction times were 490 ms, 555 ms, and 589 ms, for groups one, two, and three, respectively. Follow-up comparisons showed that group one was not significantly different from group two, t(38)=1.876, p=.068. Similarly, group 2 was not significantly different from group 3, t(38)=1.086, p=.284.</p>
</div>
</div>
<div id="running-a-between-subjects-anova-for-a-2x2-factorial-design" class="section level2">
<h2><span class="header-section-number">5.12</span> Running a between subjects ANOVA for a 2x2 Factorial design</h2>
<p>The data file 2x2Factorial_Between.txt contains simulated data for a classic memory experiment performed by Godden &amp; Baddeley (1975). The purpose of their experiment was to test the role of contextual information in guiding memory retrieval. They had different groups of subjects encode a list of words for a later memory test in one of two contexts, either on land or under water (the subjects were expert divers). Thus, the first IV was encoding context (land vs. water). In a later memory test the subjects were asked to recall as many words as possible from the list. For the subjects who encoded the words in the land context, half of the subjects performed the recall test on land, and half performed under water. The same was true for the subjects who encoded the words in the under water context. Thus, the second IV was the context of the memory test (Land vs. Water). The purpose of the experiment was to determine whether memory performance would be better when the encoding and test contexts matched (e.g., encoded and tested on land, or encoded and tested under water), compared to when the encoding and test contexts mismathced (e.g., encoded on land but tested under water, or encoded under water but tested on land).</p>
<p>The file contains simulated data for 80 subjects. There were four total conditions, and twenty subjects completed each condition. For example, 20 subjects encoded on land and tested on land, 20 subjects encoded on land and tested under water, 20 subjects encoded on land tested under water, and 20 subjects encoded under water and tested under water. The design can be described as a 2 (Encoding context: land vs. water) x 2 (Testing context: land vs. water) between subjects experiment. The dependent variable was proportion of words correctly recalled. The proportion ranges from 0 (no words recalled) to 1 (all words correctly recalled).</p>
<p>Let’s load the data file into R, then perform the necessary statistical tests to interpret the results. The final product will be a complete results section.</p>
<p>Load the data into R</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AllData&lt;-<span class="kw">read.table</span>(<span class="st">&quot;RFiles/2x2Factorial_Between.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)</code></pre></div>
<p>Perform a 2x2 ANOVA Note: Accuracy is the name of the column in the data file representing the DV, so it is used in the aov formula. Similarly, TestContext and EncodingContext are the names of the columns representing the IVs, so they are used in the aov formula.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(Accuracy~TestContext*EncodingContext,AllData))</code></pre></div>
<pre><code>##                             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## TestContext                  1 0.0067  0.0067   0.604    0.439    
## EncodingContext              1 0.0132  0.0132   1.190    0.279    
## TestContext:EncodingContext  1 0.8145  0.8145  73.495 8.79e-13 ***
## Residuals                   76 0.8423  0.0111                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We can see the ANOVA produced two main effects and one interaction. The main effect for test context was not signifcant, and the main effect for encoding context was not significant. However, the interaction between encoding and test context was significant. The p-value is expressed in scientific notation, meaning that 8.79e-13 is really 0.000000000000879. This is definetly p&lt; .05.</p>
<p>The next step is to find the means for each main effect, and the means for the interaction.</p>
<p>The means for main effect of test context can be found as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aggregate</span>(Accuracy~TestContext,AllData,mean)</code></pre></div>
<pre><code>##   TestContext Accuracy
## 1        Land 0.717218
## 2       Water 0.698917</code></pre>
<p>The means for the main effect of encoding context can be found as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aggregate</span>(Accuracy~EncodingContext,AllData,mean)</code></pre></div>
<pre><code>##   EncodingContext  Accuracy
## 1            Land 0.7209093
## 2           Water 0.6952257</code></pre>
<p>The means for the interaction between test and encoding context can be found as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">aggregate</span>(Accuracy~TestContext*EncodingContext,AllData,mean)</code></pre></div>
<pre><code>##   TestContext EncodingContext  Accuracy
## 1        Land            Land 0.8309631
## 2       Water            Land 0.6108555
## 3        Land           Water 0.6034729
## 4       Water           Water 0.7869785</code></pre>
<p>The ANOVA shows that the only the interaction is significant. The means for the interaction effect are displayed immediately above. There are four means, corresponding to each of the ways that the encoding context is paired with the test context. The next step is to interpret the pattern of this interaction. In some sense, the question here is the same as interpreting a significant result from ANOVA on a single-factor with 4-levels. A significant result in either case indicates that at least one of the means is different from the other three, but the ANOVA itself does not specify which means are different from each other. That is, the ANOVA alone does not explain the pattern of the means.</p>
<p>Inspecting the numbers we see what is known as a cross-over interaction. If these numbers were graphed in a line chart, we would see that the lines would cross-over. Indeed, the pattern of the cross-over interaction is exactly what was predicted. Remember, the main prediction of the study was that memory accuracy should be better when the encoding and test contexts match than when they mismatch. Memory performance was .83 and .77 in the matching conditions (land/land, water/water). Memory performance was .61 and .60 in the mismatching conditions (water/land, land/water). It is important to keep the predictions in mind when conducting the follow-up tests.</p>
<p>There are 6 possible comparisons that can be made to fully explain the interaction pattern. For example, the means between 1&amp;2, 1&amp;3, 1&amp;4, 2&amp;3, 2&amp;4, and 3&amp;4 can all be submitted to separate t-tests. Sometimes it is necessary to conduct all of the possible comparisons, but usually it is only necessary to conduct the comparisons most relevant to the predictions at hand.</p>
<p>Let’s start with the subjects who encoded words on Land. They should have better memory when they were tested on land than under water. The t-test is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Accuracy~TestContext, <span class="dt">data=</span>AllData[AllData$EncodingContext==<span class="st">&quot;Land&quot;</span>,], <span class="dt">var.equal=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Accuracy by TestContext
## t = 7.0058, df = 38, p-value = 2.415e-08
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.1565051 0.2837100
## sample estimates:
##  mean in group Land mean in group Water 
##           0.8309631           0.6108555</code></pre>
<p>Next, the subjects who encoded words under water. They should have better memory memory when they were tested under water than on land. The t-test is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(Accuracy~TestContext, <span class="dt">data=</span>AllData[AllData$EncodingContext==<span class="st">&quot;Water&quot;</span>,], <span class="dt">var.equal=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  Accuracy by TestContext
## t = -5.2336, df = 38, p-value = 6.387e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.2544873 -0.1125239
## sample estimates:
##  mean in group Land mean in group Water 
##           0.6034729           0.7869785</code></pre>
<p>These two t-test verify the main predictions of the study. If you look at the original paper, you will see that the authors conducted additional tests to show that there were no significant differences between memory performance in the matching conditions (land/land vs. water/water), and no significant differences between memory performance in the non-matching conditions (land/water vs. water/land).</p>
<div id="writing-up-the-results-section" class="section level3">
<h3><span class="header-section-number">5.12.1</span> Writing up the results section</h3>
<p>The preceding section produced ANOVA results for a 2x2 between-subjects design, and means for each main effect and interaction, as well as follow-up tests to explain the significant interaction. With all of this information in place it is possible to write-up a complete results section. Here is an example:</p>
<p>The mean proportions of correctly recalled words for each subject in each condition were submitted to a 2 (encoding context: land vs. water) x 2 (test context: land vs. water) between-subjects ANOVA. The main effect of encoding context was not significant, F&lt;1. The main effect of test context not significant, F(1,76) = 1.190, MSE = .011, p = .279. The two-way interaction between encoding and test context was significant, F(1,76) = 73.495, MSE = .011, p &lt; .001 . Planned comparisons showed that for participants who encoded words on land, proportion recall was higher when they tested on land (.83) than under water (.61), t(38) = 7.00, p&lt; .001. Similarly, for participants who encoded words under water, proportion recall was higher when they tested under water (.79) than on land (.60), t(38) = 5.23, p&lt; .001.</p>
<p>Note: The above results section is written with a few guidelines in mind. When a result is not significant some authors decide to simply state that the result was not significant. Some journals may require the author to fully report the F-value, the MSE, and the p-value for all non-significant effects. In the above example, the full report is not given for the first non-significant effect because the F-value was less than 1. In this case, it is often appropriate to simply report that F was less than one. Also notice that the means for the nonsignificant effects were not given. Some journals may require that these means are listed. At the very least it is important that all of the important means can be reconstructed. In this case, the four means from the interaction effect are individually listed; thus, it is is possible for the reader to reconstruct the means for both of the main effects.</p>
</div>
</div>
<div id="practice-problems" class="section level2">
<h2><span class="header-section-number">5.13</span> Practice Problems</h2>
<div id="single-factor-design-with-a-within-subjects-factor" class="section level3">
<h3><span class="header-section-number">5.13.1</span> Single factor design with a within-subjects factor</h3>
<p>The datafile is titled SingleFactor_Within.txt</p>
<p>The data file contains simulated data for 20 subjects in a sequence learning task. The dependent variable is ReactionTime. The single independent variable is called Practice, and it has four levels, 1, 2, 3, and 4. Each level represents four different blocks of practicing the sequence. The general prediction is that reaction time should decrease across the four practice blocks. Use R to load the data file and conduct a repeated-measures ANOVA, compute the means for each of the practice blocks, and conduct the necessary paired-samples t-tests. Then write a complete results section for the example data.</p>
<p>To get you started the necessary R commands are listed below</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AllData&lt;-<span class="kw">read.table</span>(<span class="st">&quot;RFiles/SingleFactor_Within.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)
<span class="kw">summary</span>(<span class="kw">aov</span>(ReactionTime~Practice +<span class="st"> </span><span class="kw">Error</span>(<span class="kw">as.character</span>(Subjects)/Practice),AllData))
<span class="kw">aggregate</span>(ReactionTime~Practice,AllData,mean)
<span class="kw">t.test</span>(AllData[AllData$Practice==<span class="st">&quot;Block1&quot;</span>,]$ReactionTime,AllData[AllData$Practice==<span class="st">&quot;Block2&quot;</span>,]$ReactionTime, <span class="dt">paired=</span><span class="ot">TRUE</span>,<span class="dt">var.equal=</span><span class="ot">TRUE</span>)</code></pre></div>
<p>note: for the t-test, change the terms Block1 and Block2 to make other comparisons (e.g., Block3 or Block4).</p>
</div>
<div id="x2-within-subjects-design" class="section level3">
<h3><span class="header-section-number">5.13.2</span> 2x2 within-subjects design</h3>
<p>The datafile is titled 2x2Factorial_Within.txt</p>
<p>The data file contains simulated for 20 subjects in a Stroop task. In a Stroop task, participants are presented with color words printed in congruent or incongruent ink-colors. For example, the word blue printed in BLUE color is a congruent item. The word red printed in BLUE is an incongruent item. In the standard task, participants are instructed to identify the ink-color and ignore the word. Typically, reactions are faster for congruent than incongruent items. In this experiment, participants completed the Stroop task with two different instructions. In one phase they were presented with congruent and incongruent items, and were told to identify the ink-color and ignore the word, this is called the NameColor condition. In the other phase, participants were presented with congruent and incongruent items, and were told to identify the word and ignore the ink-color, this is called the NameWord condition. The predictions are that RTs should generally be faster for congruent than incongruent trials. Also, RTs should generally be faster for the word naming task than the color naming task. Finally, there should be an interaction between congruency and task, such that the Stroop effect (difference between incongruent and congruent items) is larger for the name color task than the name word task.</p>
<p>There are two IVS. The first IV is Congruency, with the levels Congruent and Incongruent. The second IV is Task, with the levels NameColor and and Name Word. The DV is ReactionTime. Use R to load the data file, then conduct a repeated-measures ANOVA, compute the means for each of the main effects and the interaction, and conduct any necessary paired-sample t-tests. Then write a complete results section for the example data.</p>
<p>To get you started here are the neccessary R commands:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">AllData&lt;-<span class="kw">read.table</span>(<span class="st">&quot;RFiles/2x2Factorial_Within.txt&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;</span><span class="ch">\t</span><span class="st">&quot;</span>)
<span class="kw">summary</span>(<span class="kw">aov</span>(ReactionTime~Task*Congruency +<span class="st"> </span><span class="kw">Error</span>(<span class="kw">as.character</span>(Subjects)/(Task*Congruency)),AllData))</code></pre></div>
<p>You can also put the results of the aov into a variable</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">aovResult&lt;-<span class="kw">aov</span>(ReactionTime~Task*Congruency +<span class="st"> </span><span class="kw">Error</span>(<span class="kw">as.character</span>(Subjects)/(Task*Congruency)),AllData)</code></pre></div>
<p>Then you can print all of the means for the main effects and interactions using the following:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">model.tables</span>(aovResult,<span class="st">&quot;means&quot;</span>) </code></pre></div>
</div>
</div>
<div id="loading-raw-data-into-r" class="section level2">
<h2><span class="header-section-number">5.14</span> Loading raw-data into R</h2>
<p>Using R to analyze the results from real experiments requires that raw data-files are loaded into R and then transformed into a long-format data frame. Depending on how the raw data is formatted this process can be fairly straightforward, or not. The following provides an example of how to load multiple subjects data files into R and then complete an analysis. The example is taken from a Stroop experiment conducted in PsychoPy. Each subject’s data file is saved as separate .csv files (comma separated value). Each .csv file contains the raw data from a 24 trial Stroop experiment with 12 congruent and 12 incongruent items. The data files are already organized in long-format. The first row contains the columns headers, and each remaining row contains the raw data for each trial. The data files are named Subject1.csv, Subject2.csv, and so on.</p>
<p>The following <code>read.table</code> will load a single file into a datafram. However, the working directory must first be set to the location of the file.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Subject1&lt;-<span class="kw">read.table</span>(<span class="st">&quot;RFiles/PsychoPyStroop.csv&quot;</span>,<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;,&quot;</span>)</code></pre></div>
<p>The ultimate goal here is to load in all 8 subjects worth of data into a single dataframe. This is done using a for loop in R.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fnames&lt;-<span class="kw">c</span>(<span class="st">&quot;RFiles/Subject1.csv&quot;</span>,<span class="st">&quot;RFiles/Subject2.csv&quot;</span>,<span class="st">&quot;RFiles/Subject3.csv&quot;</span>,<span class="st">&quot;RFiles/Subject4.csv&quot;</span>,<span class="st">&quot;RFiles/Subject5.csv&quot;</span>,<span class="st">&quot;RFiles/Subject6.csv&quot;</span>,<span class="st">&quot;RFiles/Subject7.csv&quot;</span>,<span class="st">&quot;RFiles/Subject8.csv&quot;</span>)
AllSubjectData&lt;-<span class="kw">data.frame</span>()
for (i in <span class="dv">1</span>:<span class="kw">length</span>(fnames)){
  SubjectData&lt;-<span class="kw">read.table</span>(fnames[i],<span class="dt">header=</span><span class="ot">TRUE</span>,<span class="dt">sep=</span><span class="st">&quot;,&quot;</span>)
  AllSubjectData&lt;-<span class="kw">rbind</span>(AllSubjectData,SubjectData)
}
CongruencyMeans&lt;-<span class="kw">aggregate</span>(KeypressTime.rt~participant*congruency,<span class="dt">data=</span>AllSubjectData,mean)
ANOVAresults&lt;-<span class="kw">aov</span>(KeypressTime.rt~<span class="kw">factor</span>(congruency) +<span class="st"> </span><span class="kw">Error</span>(<span class="kw">as.character</span>(participant)/<span class="kw">factor</span>(congruency)),CongruencyMeans)
<span class="kw">summary</span>(ANOVAresults)</code></pre></div>
<pre><code>## 
## Error: as.character(participant)
##           Df  Sum Sq  Mean Sq F value Pr(&gt;F)
## Residuals  7 0.03176 0.004537               
## 
## Error: as.character(participant):factor(congruency)
##                    Df  Sum Sq Mean Sq F value   Pr(&gt;F)    
## factor(congruency)  1 0.25155 0.25155   133.8 8.14e-06 ***
## Residuals           7 0.01316 0.00188                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">model.tables</span>(ANOVAresults,<span class="st">&quot;means&quot;</span>)</code></pre></div>
<pre><code>## Tables of means
## Grand mean
##           
## 0.6739342 
## 
##  factor(congruency) 
## factor(congruency)
##      0      1 
## 0.7993 0.5485</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dealing-with-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="visualizing-the-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/CrumpLab/programmingforpsych/blob/master/05-C5.Rmd",
"text": "Edit"
},
"download": ["Programming_Crump.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
