<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Answering questions with data</title>
  <meta name="description" content="An introductory statistics textbook for psychology students">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Answering questions with data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An introductory statistics textbook for psychology students" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Answering questions with data" />
  
  <meta name="twitter:description" content="An introductory statistics textbook for psychology students" />
  

<meta name="author" content="Author List, TBD">
<meta name="author" content="Current Contributions, Matthew J. C. Crump">
<meta name="author" content="Adapted work so far from Navarro, D., Diaz, Barr, &amp; Cetinkaya-Rundel">
<meta name="author" content="In Draft subject to change, we will get all attributions and licenses done correctly">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="sampling-and-estimation.html">
<link rel="next" href="inferenceForNumericalDataANOVA.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-79429674-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-79429674-3');
</script>


<script type="text/javascript">
mattcrump=1;
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="tufte.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#important-notes"><i class="fa fa-check"></i><b>0.1</b> Important notes</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="why-statistics.html"><a href="why-statistics.html"><i class="fa fa-check"></i><b>1</b> Why Statistics?</a><ul>
<li class="chapter" data-level="1.1" data-path="why-statistics.html"><a href="why-statistics.html#on-the-psychology-of-statistics"><i class="fa fa-check"></i><b>1.1</b> On the psychology of statistics</a><ul>
<li class="chapter" data-level="1.1.1" data-path="why-statistics.html"><a href="why-statistics.html#the-curse-of-belief-bias"><i class="fa fa-check"></i><b>1.1.1</b> The curse of belief bias</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="why-statistics.html"><a href="why-statistics.html#the-cautionary-tale-of-simpsons-paradox"><i class="fa fa-check"></i><b>1.2</b> The cautionary tale of Simpson’s paradox</a></li>
<li class="chapter" data-level="1.3" data-path="why-statistics.html"><a href="why-statistics.html#statistics-in-psychology"><i class="fa fa-check"></i><b>1.3</b> Statistics in psychology</a></li>
<li class="chapter" data-level="1.4" data-path="why-statistics.html"><a href="why-statistics.html#statistics-in-everyday-life"><i class="fa fa-check"></i><b>1.4</b> Statistics in everyday life</a></li>
<li class="chapter" data-level="1.5" data-path="why-statistics.html"><a href="why-statistics.html#theres-more-to-research-methods-than-statistics"><i class="fa fa-check"></i><b>1.5</b> There’s more to research methods than statistics</a></li>
<li class="chapter" data-level="1.6" data-path="why-statistics.html"><a href="why-statistics.html#a-brief-introduction-to-research-designchstudydesign"><i class="fa fa-check"></i><b>1.6</b> A brief introduction to research design[ch:studydesign]</a><ul>
<li class="chapter" data-level="1.6.1" data-path="why-statistics.html"><a href="why-statistics.html#introduction-to-psychological-measurementsecmeasurement"><i class="fa fa-check"></i><b>1.6.1</b> Introduction to psychological measurement [sec:measurement]</a></li>
<li class="chapter" data-level="1.6.2" data-path="why-statistics.html"><a href="why-statistics.html#scales-of-measurementsecscales"><i class="fa fa-check"></i><b>1.6.2</b> Scales of measurement[sec:scales]</a></li>
<li class="chapter" data-level="1.6.3" data-path="why-statistics.html"><a href="why-statistics.html#assessing-the-reliability-of-a-measurementsecreliability"><i class="fa fa-check"></i><b>1.6.3</b> Assessing the reliability of a measurement [sec:reliability]</a></li>
<li class="chapter" data-level="1.6.4" data-path="why-statistics.html"><a href="why-statistics.html#the-role-of-variables-predictors-and-outcomes-secivdv"><i class="fa fa-check"></i><b>1.6.4</b> The “role” of variables: predictors and outcomes [sec:ivdv]</a></li>
<li class="chapter" data-level="1.6.5" data-path="why-statistics.html"><a href="why-statistics.html#experimental-and-non-experimental-researchsecresearchdesigns"><i class="fa fa-check"></i><b>1.6.5</b> Experimental and non-experimental research [sec:researchdesigns]</a></li>
<li class="chapter" data-level="1.6.6" data-path="why-statistics.html"><a href="why-statistics.html#assessing-the-validity-of-a-studysecvalidity"><i class="fa fa-check"></i><b>1.6.6</b> Assessing the validity of a study [sec:validity]</a></li>
<li class="chapter" data-level="1.6.7" data-path="why-statistics.html"><a href="why-statistics.html#confounds-artifacts-and-other-threats-to-validity"><i class="fa fa-check"></i><b>1.6.7</b> Confounds, artifacts and other threats to validity</a></li>
<li class="chapter" data-level="1.6.8" data-path="why-statistics.html"><a href="why-statistics.html#summary"><i class="fa fa-check"></i><b>1.6.8</b> Summary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="DescribingData.html"><a href="DescribingData.html"><i class="fa fa-check"></i><b>2</b> Describing Data</a><ul>
<li class="chapter" data-level="2.1" data-path="DescribingData.html"><a href="DescribingData.html#this-is-what-too-many-numbers-looks-like"><i class="fa fa-check"></i><b>2.1</b> This is what too many numbers looks like</a></li>
<li class="chapter" data-level="2.2" data-path="DescribingData.html"><a href="DescribingData.html#look-at-the-data"><i class="fa fa-check"></i><b>2.2</b> Look at the data</a><ul>
<li class="chapter" data-level="2.2.1" data-path="DescribingData.html"><a href="DescribingData.html#stop-plotting-time-o-o-oh-u-can-plot-this"><i class="fa fa-check"></i><b>2.2.1</b> Stop, plotting time (o o oh) U can plot this</a></li>
<li class="chapter" data-level="2.2.2" data-path="DescribingData.html"><a href="DescribingData.html#histograms"><i class="fa fa-check"></i><b>2.2.2</b> Histograms</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="DescribingData.html"><a href="DescribingData.html#important-ideas-distribution-central-tendency-and-variance"><i class="fa fa-check"></i><b>2.3</b> Important Ideas: Distribution, Central Tendency, and Variance</a></li>
<li class="chapter" data-level="2.4" data-path="DescribingData.html"><a href="DescribingData.html#measures-of-central-tendency-sameness"><i class="fa fa-check"></i><b>2.4</b> Measures of Central Tendency (Sameness)</a><ul>
<li class="chapter" data-level="2.4.1" data-path="DescribingData.html"><a href="DescribingData.html#from-many-numbers-to-one"><i class="fa fa-check"></i><b>2.4.1</b> From many numbers to one</a></li>
<li class="chapter" data-level="2.4.2" data-path="DescribingData.html"><a href="DescribingData.html#mode"><i class="fa fa-check"></i><b>2.4.2</b> Mode</a></li>
<li class="chapter" data-level="2.4.3" data-path="DescribingData.html"><a href="DescribingData.html#median"><i class="fa fa-check"></i><b>2.4.3</b> Median</a></li>
<li class="chapter" data-level="2.4.4" data-path="DescribingData.html"><a href="DescribingData.html#mean"><i class="fa fa-check"></i><b>2.4.4</b> Mean</a></li>
<li class="chapter" data-level="2.4.5" data-path="DescribingData.html"><a href="DescribingData.html#what-does-the-mean-mean"><i class="fa fa-check"></i><b>2.4.5</b> What does the mean mean?</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="DescribingData.html"><a href="DescribingData.html#measures-of-variation-differentness"><i class="fa fa-check"></i><b>2.5</b> Measures of Variation (Differentness)</a><ul>
<li class="chapter" data-level="2.5.1" data-path="DescribingData.html"><a href="DescribingData.html#the-range"><i class="fa fa-check"></i><b>2.5.1</b> The Range</a></li>
<li class="chapter" data-level="2.5.2" data-path="DescribingData.html"><a href="DescribingData.html#the-difference-scores"><i class="fa fa-check"></i><b>2.5.2</b> The Difference Scores</a></li>
<li class="chapter" data-level="2.5.3" data-path="DescribingData.html"><a href="DescribingData.html#the-variance"><i class="fa fa-check"></i><b>2.5.3</b> The Variance</a></li>
<li class="chapter" data-level="2.5.4" data-path="DescribingData.html"><a href="DescribingData.html#the-standard-deviation"><i class="fa fa-check"></i><b>2.5.4</b> The Standard Deviation</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="DescribingData.html"><a href="DescribingData.html#using-descriptive-statistics-with-data"><i class="fa fa-check"></i><b>2.6</b> Using Descriptive Statistics with data</a></li>
<li class="chapter" data-level="2.7" data-path="DescribingData.html"><a href="DescribingData.html#rolling-your-own-descriptive-statistics"><i class="fa fa-check"></i><b>2.7</b> Rolling your own descriptive statistics</a><ul>
<li class="chapter" data-level="2.7.1" data-path="DescribingData.html"><a href="DescribingData.html#absolute-deviations"><i class="fa fa-check"></i><b>2.7.1</b> Absolute deviations</a></li>
<li class="chapter" data-level="2.7.2" data-path="DescribingData.html"><a href="DescribingData.html#other-sign-inverting-operations"><i class="fa fa-check"></i><b>2.7.2</b> Other sign-inverting operations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Correlation.html"><a href="Correlation.html"><i class="fa fa-check"></i><b>3</b> Correlation</a><ul>
<li class="chapter" data-level="3.1" data-path="Correlation.html"><a href="Correlation.html#if-something-caused-something-else-to-change-what-would-that-look-like"><i class="fa fa-check"></i><b>3.1</b> If something caused something else to change, what would that look like?</a><ul>
<li class="chapter" data-level="3.1.1" data-path="Correlation.html"><a href="Correlation.html#charlie-and-the-chocolate-factory"><i class="fa fa-check"></i><b>3.1.1</b> Charlie and the Chocolate factory</a></li>
<li class="chapter" data-level="3.1.2" data-path="Correlation.html"><a href="Correlation.html#scatterplots"><i class="fa fa-check"></i><b>3.1.2</b> Scatterplots</a></li>
<li class="chapter" data-level="3.1.3" data-path="Correlation.html"><a href="Correlation.html#positive-negative-and-no-correlation"><i class="fa fa-check"></i><b>3.1.3</b> Positive, Negative, and No-Correlation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="Correlation.html"><a href="Correlation.html#pearsons-r"><i class="fa fa-check"></i><b>3.2</b> Pearson’s r</a><ul>
<li class="chapter" data-level="3.2.1" data-path="Correlation.html"><a href="Correlation.html#the-idea-of-co-variance"><i class="fa fa-check"></i><b>3.2.1</b> The idea of co-variance</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="Correlation.html"><a href="Correlation.html#turning-the-numbers-into-a-measure-of-co-variance"><i class="fa fa-check"></i><b>3.3</b> Turning the numbers into a measure of co-variance</a><ul>
<li class="chapter" data-level="3.3.1" data-path="Correlation.html"><a href="Correlation.html#co-variance-the-measure"><i class="fa fa-check"></i><b>3.3.1</b> Co-variance, the measure</a></li>
<li class="chapter" data-level="3.3.2" data-path="Correlation.html"><a href="Correlation.html#pearsons-r-we-there-yet"><i class="fa fa-check"></i><b>3.3.2</b> Pearson’s r we there yet</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="Correlation.html"><a href="Correlation.html#examples-with-data"><i class="fa fa-check"></i><b>3.4</b> Examples with Data</a></li>
<li class="chapter" data-level="3.5" data-path="Correlation.html"><a href="Correlation.html#regression-a-mini-intro"><i class="fa fa-check"></i><b>3.5</b> Regression: A mini intro</a><ul>
<li class="chapter" data-level="3.5.1" data-path="Correlation.html"><a href="Correlation.html#the-best-fit-line"><i class="fa fa-check"></i><b>3.5.1</b> The best fit line</a></li>
<li class="chapter" data-level="3.5.2" data-path="Correlation.html"><a href="Correlation.html#lines"><i class="fa fa-check"></i><b>3.5.2</b> Lines</a></li>
<li class="chapter" data-level="3.5.3" data-path="Correlation.html"><a href="Correlation.html#computing-the-best-fit-line"><i class="fa fa-check"></i><b>3.5.3</b> Computing the best fit line</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="Correlation.html"><a href="Correlation.html#interpreting-correlations"><i class="fa fa-check"></i><b>3.6</b> Interpreting Correlations</a><ul>
<li class="chapter" data-level="3.6.1" data-path="Correlation.html"><a href="Correlation.html#correlation-does-not-equal-causation"><i class="fa fa-check"></i><b>3.6.1</b> Correlation does not equal causation</a></li>
<li class="chapter" data-level="3.6.2" data-path="Correlation.html"><a href="Correlation.html#correlation-and-random-chance"><i class="fa fa-check"></i><b>3.6.2</b> Correlation and Random chance</a></li>
<li class="chapter" data-level="3.6.3" data-path="Correlation.html"><a href="Correlation.html#some-more-movies"><i class="fa fa-check"></i><b>3.6.3</b> Some more movies</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html"><i class="fa fa-check"></i><b>4</b> Sampling and estimation</a><ul>
<li class="chapter" data-level="4.1" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#samples-populations-and-sampling"><i class="fa fa-check"></i><b>4.1</b> Samples, populations and sampling</a><ul>
<li class="chapter" data-level="4.1.1" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#defining-a-population"><i class="fa fa-check"></i><b>4.1.1</b> Defining a population</a></li>
<li class="chapter" data-level="4.1.2" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#simple-random-samples"><i class="fa fa-check"></i><b>4.1.2</b> Simple random samples</a></li>
<li class="chapter" data-level="4.1.3" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#most-samples-are-not-simple-random-samples"><i class="fa fa-check"></i><b>4.1.3</b> Most samples are not simple random samples</a></li>
<li class="chapter" data-level="4.1.4" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#how-much-does-it-matter-if-you-dont-have-a-simple-random-sample"><i class="fa fa-check"></i><b>4.1.4</b> How much does it matter if you don’t have a simple random sample?</a></li>
<li class="chapter" data-level="4.1.5" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#population-parameters-and-sample-statistics"><i class="fa fa-check"></i><b>4.1.5</b> Population parameters and sample statistics</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#the-law-of-large-numbers"><i class="fa fa-check"></i><b>4.2</b> The law of large numbers</a></li>
<li class="chapter" data-level="4.3" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#sampling-distributions-and-the-central-limit-theorem"><i class="fa fa-check"></i><b>4.3</b> Sampling distributions and the central limit theorem</a><ul>
<li class="chapter" data-level="4.3.1" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#sampling-distribution-of-the-sample-means"><i class="fa fa-check"></i><b>4.3.1</b> Sampling distribution of the sample means</a></li>
<li class="chapter" data-level="4.3.2" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#chance-can-produce-differences"><i class="fa fa-check"></i><b>4.3.2</b> Chance can produce differences</a></li>
<li class="chapter" data-level="4.3.3" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#differences-due-to-chance-can-be-simulated"><i class="fa fa-check"></i><b>4.3.3</b> Differences due to chance can be simulated</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#chance-makes-some-differences-more-likely-than-others"><i class="fa fa-check"></i><b>4.4</b> Chance makes some differences more likely than others</a></li>
<li class="chapter" data-level="4.5" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#the-crump-test"><i class="fa fa-check"></i><b>4.5</b> The Crump Test</a><ul>
<li class="chapter" data-level="4.5.1" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#intuitive-methods"><i class="fa fa-check"></i><b>4.5.1</b> Intuitive methods</a></li>
<li class="chapter" data-level="4.5.2" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#part-1-frequency-based-intuition-about-occurence"><i class="fa fa-check"></i><b>4.5.2</b> Part 1: Frequency based intuition about occurence</a></li>
<li class="chapter" data-level="4.5.3" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#part-2-simulating-chance"><i class="fa fa-check"></i><b>4.5.3</b> Part 2: Simulating chance</a></li>
<li class="chapter" data-level="4.5.4" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#part-3-judgment-and-decision-making"><i class="fa fa-check"></i><b>4.5.4</b> Part 3: Judgment and Decision-making</a></li>
<li class="chapter" data-level="4.5.5" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#part-4-experiment-design"><i class="fa fa-check"></i><b>4.5.5</b> Part 4: Experiment Design</a></li>
<li class="chapter" data-level="4.5.6" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#part-5-i-have-the-power"><i class="fa fa-check"></i><b>4.5.6</b> Part 5: I have the power</a></li>
<li class="chapter" data-level="4.5.7" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#summary-of-crump-test"><i class="fa fa-check"></i><b>4.5.7</b> Summary of Crump Test</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#the-randomization-test-permutation-test"><i class="fa fa-check"></i><b>4.6</b> The randomization test (permutation test)</a><ul>
<li class="chapter" data-level="4.6.1" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#pretend-example-does-chewing-gum-improve-your-grades"><i class="fa fa-check"></i><b>4.6.1</b> Pretend example does chewing gum improve your grades?</a></li>
<li class="chapter" data-level="4.6.2" data-path="sampling-and-estimation.html"><a href="sampling-and-estimation.html#take-homes-so-far"><i class="fa fa-check"></i><b>4.6.2</b> Take homes so far</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="t-tests.html"><a href="t-tests.html"><i class="fa fa-check"></i><b>5</b> t-Tests</a><ul>
<li class="chapter" data-level="5.1" data-path="t-tests.html"><a href="t-tests.html#check-your-confidence-in-your-mean"><i class="fa fa-check"></i><b>5.1</b> Check your confidence in your mean</a></li>
<li class="chapter" data-level="5.2" data-path="t-tests.html"><a href="t-tests.html#one-sample-t-test-a-new-t-test"><i class="fa fa-check"></i><b>5.2</b> One-sample t-test: A new t-test</a><ul>
<li class="chapter" data-level="5.2.1" data-path="t-tests.html"><a href="t-tests.html#formulas-for-one-sample-t-test"><i class="fa fa-check"></i><b>5.2.1</b> Formulas for one-sample t-test</a></li>
<li class="chapter" data-level="5.2.2" data-path="t-tests.html"><a href="t-tests.html#what-does-t-represent"><i class="fa fa-check"></i><b>5.2.2</b> What does t represent?</a></li>
<li class="chapter" data-level="5.2.3" data-path="t-tests.html"><a href="t-tests.html#calculating-t-from-data"><i class="fa fa-check"></i><b>5.2.3</b> Calculating t from data</a></li>
<li class="chapter" data-level="5.2.4" data-path="t-tests.html"><a href="t-tests.html#how-does-t-behave"><i class="fa fa-check"></i><b>5.2.4</b> How does <span class="math inline">\(t\)</span> behave?</a></li>
<li class="chapter" data-level="5.2.5" data-path="t-tests.html"><a href="t-tests.html#making-a-decision"><i class="fa fa-check"></i><b>5.2.5</b> Making a decision</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="t-tests.html"><a href="t-tests.html#paired-samples-t-test"><i class="fa fa-check"></i><b>5.3</b> Paired-samples <span class="math inline">\(t\)</span>-test</a><ul>
<li class="chapter" data-level="5.3.1" data-path="t-tests.html"><a href="t-tests.html#mehr-song-and-spelke-2016"><i class="fa fa-check"></i><b>5.3.1</b> Mehr, Song, and Spelke (2016)</a></li>
<li class="chapter" data-level="5.3.2" data-path="t-tests.html"><a href="t-tests.html#the-data"><i class="fa fa-check"></i><b>5.3.2</b> The data</a></li>
<li class="chapter" data-level="5.3.3" data-path="t-tests.html"><a href="t-tests.html#the-difference-scores-1"><i class="fa fa-check"></i><b>5.3.3</b> The difference scores</a></li>
<li class="chapter" data-level="5.3.4" data-path="t-tests.html"><a href="t-tests.html#the-mean-difference"><i class="fa fa-check"></i><b>5.3.4</b> The mean difference</a></li>
<li class="chapter" data-level="5.3.5" data-path="t-tests.html"><a href="t-tests.html#calculate-t"><i class="fa fa-check"></i><b>5.3.5</b> Calculate <span class="math inline">\(t\)</span></a></li>
<li class="chapter" data-level="5.3.6" data-path="t-tests.html"><a href="t-tests.html#interpreting-ts"><i class="fa fa-check"></i><b>5.3.6</b> Interpreting <span class="math inline">\(t\)</span>s</a></li>
<li class="chapter" data-level="5.3.7" data-path="t-tests.html"><a href="t-tests.html#getting-the-p-values-for-t-values"><i class="fa fa-check"></i><b>5.3.7</b> Getting the p-values for t-values</a></li>
<li class="chapter" data-level="5.3.8" data-path="t-tests.html"><a href="t-tests.html#one-tailed-tests"><i class="fa fa-check"></i><b>5.3.8</b> One-tailed tests</a></li>
<li class="chapter" data-level="5.3.9" data-path="t-tests.html"><a href="t-tests.html#two-tailed-tests"><i class="fa fa-check"></i><b>5.3.9</b> Two-tailed tests</a></li>
<li class="chapter" data-level="5.3.10" data-path="t-tests.html"><a href="t-tests.html#one-or-two-tailed-which-one"><i class="fa fa-check"></i><b>5.3.10</b> One or two tailed, which one?</a></li>
<li class="chapter" data-level="5.3.11" data-path="t-tests.html"><a href="t-tests.html#degrees-of-freedom"><i class="fa fa-check"></i><b>5.3.11</b> Degrees of freedom</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="t-tests.html"><a href="t-tests.html#the-paired-samples-t-test-strikes-back"><i class="fa fa-check"></i><b>5.4</b> The paired samples t-test strikes back</a></li>
<li class="chapter" data-level="5.5" data-path="t-tests.html"><a href="t-tests.html#independent-samples-t-test-the-return-of-the-t-test"><i class="fa fa-check"></i><b>5.5</b> Independent samples t-test: The return of the t-test?</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferenceForNumericalDataANOVA.html"><a href="inferenceForNumericalDataANOVA.html"><i class="fa fa-check"></i><b>6</b> ANOVA</a></li>
<li class="chapter" data-level="7" data-path="repeated-measures-anova.html"><a href="repeated-measures-anova.html"><i class="fa fa-check"></i><b>7</b> Repeated Measures ANOVA</a></li>
<li class="chapter" data-level="8" data-path="factorial-anova.html"><a href="factorial-anova.html"><i class="fa fa-check"></i><b>8</b> Factorial ANOVA</a></li>
<li class="chapter" data-level="9" data-path="mixed-design-anova.html"><a href="mixed-design-anova.html"><i class="fa fa-check"></i><b>9</b> Mixed Design ANOVA</a></li>
<li class="chapter" data-level="10" data-path="linRegrForTwoVar.html"><a href="linRegrForTwoVar.html"><i class="fa fa-check"></i><b>10</b> Introduction to linear regression</a></li>
<li class="chapter" data-level="11" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html"><i class="fa fa-check"></i><b>11</b> Multiple and logistic regression</a><ul>
<li class="chapter" data-level="11.1" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#introductionToMultipleRegression"><i class="fa fa-check"></i><b>11.1</b> Introduction to multiple regression</a><ul>
<li class="chapter" data-level="11.1.1" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#twoSingleVariableModelsForMarioKartData"><i class="fa fa-check"></i><b>11.1.1</b> A single-variable model for the Mario Kart data</a></li>
<li class="chapter" data-level="11.1.2" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#includingAndAssessingManyVariablesInAModel"><i class="fa fa-check"></i><b>11.1.2</b> Including and assessing many variables in a model</a></li>
<li class="chapter" data-level="11.1.3" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#adjusted-r2-as-a-better-estimate-of-explained-variance"><i class="fa fa-check"></i><b>11.1.3</b> Adjusted <span class="math inline">\(R^2\)</span> as a better estimate of explained variance</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#modelSelection"><i class="fa fa-check"></i><b>11.2</b> Model selection</a><ul>
<li class="chapter" data-level="11.2.1" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#identifying-variables-in-the-model-that-may-not-be-helpful"><i class="fa fa-check"></i><b>11.2.1</b> Identifying variables in the model that may not be helpful</a></li>
<li class="chapter" data-level="11.2.2" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#two-model-selection-strategies"><i class="fa fa-check"></i><b>11.2.2</b> Two model selection strategies</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#multipleRegressionModelAssumptions"><i class="fa fa-check"></i><b>11.3</b> Checking model assumptions using graphs</a></li>
<li class="chapter" data-level="11.4" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#logisticRegression"><i class="fa fa-check"></i><b>11.4</b> Logistic regression</a><ul>
<li class="chapter" data-level="11.4.1" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#email-data"><i class="fa fa-check"></i><b>11.4.1</b> Email data</a></li>
<li class="chapter" data-level="11.4.2" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#modelingTheProbabilityOfAnEvent"><i class="fa fa-check"></i><b>11.4.2</b> Modeling the probability of an event</a></li>
<li class="chapter" data-level="11.4.3" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#practical-decisions-in-the-email-application"><i class="fa fa-check"></i><b>11.4.3</b> Practical decisions in the email application</a></li>
<li class="chapter" data-level="11.4.4" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#diagnostics-for-the-email-classifier"><i class="fa fa-check"></i><b>11.4.4</b> Diagnostics for the email classifier</a></li>
<li class="chapter" data-level="11.4.5" data-path="multipleRegressionAndANOVA.html"><a href="multipleRegressionAndANOVA.html#improvingTheSetOfVariablesForASpamFilter"><i class="fa fa-check"></i><b>11.4.5</b> Improving the set of variables for a spam filter</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html"><i class="fa fa-check"></i><b>12</b> Inference for categorical data</a><ul>
<li class="chapter" data-level="12.1" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#singleProportion"><i class="fa fa-check"></i><b>12.1</b> Inference for a single proportion</a><ul>
<li class="chapter" data-level="12.1.1" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#when-the-sample-proportion-is-nearly-normal"><i class="fa fa-check"></i><b>12.1.1</b> When the sample proportion is nearly normal</a></li>
<li class="chapter" data-level="12.1.2" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#confIntForPropSection"><i class="fa fa-check"></i><b>12.1.2</b> Confidence intervals for a proportion</a></li>
<li class="chapter" data-level="12.1.3" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#htForPropSection"><i class="fa fa-check"></i><b>12.1.3</b> Hypothesis testing for a proportion</a></li>
<li class="chapter" data-level="12.1.4" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#choosing-a-sample-size-when-estimating-a-proportion"><i class="fa fa-check"></i><b>12.1.4</b> Choosing a sample size when estimating a proportion</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#differenceOfTwoProportions"><i class="fa fa-check"></i><b>12.2</b> Difference of two proportions</a><ul>
<li class="chapter" data-level="12.2.1" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#SampleDistributionOfTheDiffOfTwoProportions"><i class="fa fa-check"></i><b>12.2.1</b> Sample distribution of the difference of two proportions</a></li>
<li class="chapter" data-level="12.2.2" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#intervals-and-tests-for-p_1--p_2"><i class="fa fa-check"></i><b>12.2.2</b> Intervals and tests for <span class="math inline">\(p_1 -p_2\)</span></a></li>
<li class="chapter" data-level="12.2.3" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#pooledHTForProportionsSection"><i class="fa fa-check"></i><b>12.2.3</b> Hypothesis testing when <span class="math inline">\(H_0: p_1=p_2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#oneWayChiSquare"><i class="fa fa-check"></i><b>12.3</b> Testing for goodness of fit using chi-square (special topic)</a><ul>
<li class="chapter" data-level="12.3.1" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#creating-a-test-statistic-for-one-way-tables"><i class="fa fa-check"></i><b>12.3.1</b> Creating a test statistic for one-way tables</a></li>
<li class="chapter" data-level="12.3.2" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#chiSquareTestStatistic"><i class="fa fa-check"></i><b>12.3.2</b> The chi-square test statistic</a></li>
<li class="chapter" data-level="12.3.3" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#the-chi-square-distribution-and-finding-areas"><i class="fa fa-check"></i><b>12.3.3</b> The chi-square distribution and finding areas</a></li>
<li class="chapter" data-level="12.3.4" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#pValueForAChiSquareTest"><i class="fa fa-check"></i><b>12.3.4</b> Finding a p-value for a chi-square distribution</a></li>
<li class="chapter" data-level="12.3.5" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#evaluating-goodness-of-fit-for-a-distribution"><i class="fa fa-check"></i><b>12.3.5</b> Evaluating goodness of fit for a distribution</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#twoWayTablesAndChiSquare"><i class="fa fa-check"></i><b>12.4</b> Testing for independence in two-way tables (special topic)</a><ul>
<li class="chapter" data-level="12.4.1" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#expected-counts-in-two-way-tables"><i class="fa fa-check"></i><b>12.4.1</b> Expected counts in two-way tables</a></li>
<li class="chapter" data-level="12.4.2" data-path="inferenceForCategoricalData.html"><a href="inferenceForCategoricalData.html#the-chi-square-test-for-two-way-tables"><i class="fa fa-check"></i><b>12.4.2</b> The chi-square test for two-way tables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="gifs.html"><a href="gifs.html"><i class="fa fa-check"></i><b>13</b> GIFs</a><ul>
<li class="chapter" data-level="13.1" data-path="gifs.html"><a href="gifs.html#correlation-gifs"><i class="fa fa-check"></i><b>13.1</b> Correlation GIFs</a><ul>
<li class="chapter" data-level="13.1.1" data-path="gifs.html"><a href="gifs.html#n10-both-variables-drawn-from-a-uniform-distribution"><i class="fa fa-check"></i><b>13.1.1</b> N=10, both variables drawn from a uniform distribution</a></li>
<li class="chapter" data-level="13.1.2" data-path="gifs.html"><a href="gifs.html#correlation-between-random-deviates-from-uniform-distribution-across-four-sample-sizes"><i class="fa fa-check"></i><b>13.1.2</b> Correlation between random deviates from uniform distribution across four sample sizes</a></li>
<li class="chapter" data-level="13.1.3" data-path="gifs.html"><a href="gifs.html#correlation-between-random-deviates-from-normal-distribution-across-four-sample-sizes"><i class="fa fa-check"></i><b>13.1.3</b> Correlation between random deviates from normal distribution across four sample sizes</a></li>
<li class="chapter" data-level="13.1.4" data-path="gifs.html"><a href="gifs.html#type-i-errors-sampling-random-deviates-from-normal-distribution-with-regression-lines"><i class="fa fa-check"></i><b>13.1.4</b> Type I errors, sampling random deviates from normal distribution with regression lines</a></li>
<li class="chapter" data-level="13.1.5" data-path="gifs.html"><a href="gifs.html#cell-size-and-correlation"><i class="fa fa-check"></i><b>13.1.5</b> Cell-size and correlation</a></li>
<li class="chapter" data-level="13.1.6" data-path="gifs.html"><a href="gifs.html#regression"><i class="fa fa-check"></i><b>13.1.6</b> Regression</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="gifs.html"><a href="gifs.html#sampling-distributions"><i class="fa fa-check"></i><b>13.2</b> Sampling distributions</a><ul>
<li class="chapter" data-level="13.2.1" data-path="gifs.html"><a href="gifs.html#sampling-from-a-uniform-distribution"><i class="fa fa-check"></i><b>13.2.1</b> Sampling from a uniform distribution</a></li>
<li class="chapter" data-level="13.2.2" data-path="gifs.html"><a href="gifs.html#sampling-distribution-of-the-mean-normal-population-distribution-and-sample-histograms"><i class="fa fa-check"></i><b>13.2.2</b> Sampling distribution of the mean, Normal population distribution and sample histograms</a></li>
<li class="chapter" data-level="13.2.3" data-path="gifs.html"><a href="gifs.html#null-and-true-effect-samples-and-sampling-means"><i class="fa fa-check"></i><b>13.2.3</b> Null and True effect samples and sampling means</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="gifs.html"><a href="gifs.html#statistical-inference"><i class="fa fa-check"></i><b>13.3</b> Statistical Inference</a><ul>
<li class="chapter" data-level="13.3.1" data-path="gifs.html"><a href="gifs.html#randomization-test"><i class="fa fa-check"></i><b>13.3.1</b> Randomization Test</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Answering questions with data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="t-tests" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> t-Tests</h1>
<p>One day, many moons ago, William Sealy Gosset got a job working for Guinness Breweries. They make that really dark and famous Irish beer called Guinness. What happens next went something like this (total fabrication, but mostly on point).</p>
<p>Guinness wanted all of its beers to the best beers. No mistakes, No bad beers. They wanted to improve their quality control, so that wherever you pour a Guiness, anywhere in the world, it always comes out just fantastic, let’s say 5 stars out of 5 every time. They want to be the best.</p>
<p>Guiness had some beer tasters, who were super-experts. Everytime they tasted a Guiness from the factor that wasn’t 5 out of 5, they knew right away.</p>
<p>But, Guiness had a big problem. They would make a keg of beer, and they would want to know if every single pint that would come out would be a 5 out of 5. So, the beer tasters drank pint after pint out of the keg, until it was gone. Some kegs were all 5 out of 5s. Some weren’t, Guiness needed to fix that. But, the biggest problem was that, after the testing, there <strong>was no beer left to sell</strong>, the testers drank it all (remember I’m kind of making this part up to illustrate a point, they probably still had beer to sell).</p>
<p>Guiness had a sampling and population problem. They wanted to know that the entire population of the beers they made were all 5 out of 5 stars. But, if they sampled the entire population, they would drink all of their beer, and wouldn’t have any left to sell.</p>
<p>Enter William Sealy Gosset. Gosset figured out the solution to the problem. He asked questions like this:</p>
<ol style="list-style-type: decimal">
<li>How many samples do I really need to take to know the whole population is 5 out of 5?</li>
<li>What’s the fewest amount of samples I need to take to know the above, that would mean Guiness could test fewer beers for quality, and sell more beers for profit, and making the product testing time shorter.</li>
</ol>
<p>Gosset solved those questions, and he invented something called the <em>Student’s t-test</em>. Gosset was working for Guinness, and could be fired for releasing trade-secrets that he invented (the t-test). But, Gosset published the work anyways, under a pseudonym. He called himself Student, hence Student’s t-test. Now you know the rest of the story.</p>
<p>It turns out this was a very nice thing for Gosset to have done. t-tests are used all the time, and they are useful, that’s why they are used. In this chapter we learn how they work.</p>
<p>You’ll be surprised to learn that what we’ve already talked about, (the Crump Test, and the Randomization Test), are both very very similar to the t-test. So, in general, you have already been thinking about the things you need to think about to understand t-tests. You’re probably wondering what is this <span class="math inline">\(t\)</span>, what does <span class="math inline">\(t\)</span> mean? We will tell you. Before we tell what it means, we first tell you about one more idea.</p>
<div id="check-your-confidence-in-your-mean" class="section level2">
<h2><span class="header-section-number">5.1</span> Check your confidence in your mean</h2>
<p>We’ve talked about getting a sample of data. We know we can find the mean, we know can find the standard deviation. We know we can look at the data in a histogram. These are all useful things to do for us to learn something about the properties of our data.</p>
<p>You might be thinking about these things, like mean and standard deviation, as very different things. The mean is about central tendency (where most of the data is), and the standard deviation is about variance (where most of the data isn’t). Yes, they are different things, but we can use them together to create useful new things.</p>
<p>What if I told you my sample mean was 50, and I told you nothing else about my sample. Would you be confident that most of the numbers were near 50? Would you wonder if there was a lot of variability in the sample, and many of the numbers were very different from 50. You should wonder all of those things. The mean alone, just by itself, doesn’t tell you anything about how confident you should be that the number represents all of the numbers in the sample.</p>
<p>It could be a representative number, when the standard deviation is very small, and all the numbers are close to 50. It could be a non-representative number, when the standard deviation is large, and many of the numbers are not near 50. You need to know the standard deviation in order to be confident in how well the mean represents the data.</p>
<p>How can we put the mean and the standard deviation together, to give us a new number that tells us about confidence in the mean?</p>
<p>We can do this using a ratio:</p>
<p><span class="math inline">\(\frac{mean}{\text{standard deviation}}\)</span></p>
<p>Think about what happens here. We are dividing a number by a number. Look at what happens:</p>
<p><span class="math inline">\(\frac{number}{\text{same number}} = 1\)</span></p>
<p><span class="math inline">\(\frac{number}{\text{smaller number}} = \text{big number}\)</span></p>
<p>compared to:</p>
<p><span class="math inline">\(\frac{number}{\text{bigger number}} = \text{smaller number}\)</span></p>
<p>Imagine we have a mean of 50, and a truly small standard deviation of 1. What do we get with our formula?</p>
<p>$ = 50 $</p>
<p>Imgaine we have a mean of 50, and a big standard deviation of 100. What do we get with our formula?</p>
<p>$ = 0.5 $</p>
<p>Notice, when we have a mean paired with a small standard deviation, our formula gives us a big number, like 50. When we have a mean paired with a large standard deviation, our formula gives us a small number, like 0.5. These numbers can tell us something about confidence in our mean, in a general way. We can be 50 confident in our mean in the first case, and only 0.5 (not at a lot) confident in the second case.</p>
<p>What did we do here? We created a descriptive statistic by dividing the mean by the standard deviation. And, we have a sense of how to interpet this number, when it’s big we’re more confident that the mean represents all of the numbers, when it’s small we are less confident. This is a useful kind of number, a ratio between what we think about our sample (the mean), and the variability in our sample (the standard deviation). Get used to this idea. Almost everything that follows in this textbook is based on this kind of ratio. We will see that our ratio becomes different kinds of “statistics”, and the ratios will look like this in general:</p>
<p><span class="math inline">\(\text{name of statistic} = \frac{\text{measure of what we know}}{\text{measure of what we don&#39;t know}}\)</span></p>
<p>or, to say it using different words:</p>
<p><span class="math inline">\(\text{name of statistic} = \frac{\text{measure of effect}}{\text{measure of error}}\)</span></p>
<p>In fact, this is the general formula for the t-test. Big surprise!</p>
</div>
<div id="one-sample-t-test-a-new-t-test" class="section level2">
<h2><span class="header-section-number">5.2</span> One-sample t-test: A new t-test</h2>
<p>Now we are ready to talk about t-test. We will talk about three of them. We start with the one-sample t-test.</p>
<p>Commonly, the one-sample t-test is used to estimate the chances that your sample came from a particular popualtion. Specifically, you might want to know whether the mean that you found from your sample, could have come from a particular population having a particular mean.</p>
<p>Straight away, the one-sample t-test becomes a little confusing (and I haven’t even described it yet). Offically, the uses known parameters from the population, like the mean of the population and the standard deviation of the population. However, most times you don’t know those parameters of the population! So, you have to estimate them from your sample. Remember, from the chapter on descriptive statistics, our sample mean is an unbiased estimate of the population mean. And, our sample standard deviation (the one where we divide by n-1) is an unbiased estimate of the population standard deviation. When Gosset developed the t-test, he recognized that he could use these estimates from his samples, to make the t-test. Here is the formula for the one sample t-test, we first use words, and then become more specific:</p>
<div id="formulas-for-one-sample-t-test" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Formulas for one-sample t-test</h3>
<p><span class="math inline">\(\text{name of statistic} = \frac{\text{measure of effect}}{\text{measure of error}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\text{measure of effect}}{\text{measure of error}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\text{Mean difference}}{\text{standard error}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\bar{X}-u}{S_{\bar{X}}}\)</span></p>
<p><span class="math inline">\(\text{t} = \frac{\text{Sample Mean  - Population Mean}}{\text{Sample Standard Error}}\)</span></p>
<p><span class="math inline">\(\text{Estimated Standard Error} = \text{Standard Error of Sample} = \frac{s}{\sqrt{N}}\)</span></p>
<p>Where, s is the sample standard deviation.</p>
<p>Some of you may have gone cross-eyed looking at all of this. Remember, we’ve seen it before when we divided our mean by the standard deviation in the first bit. The t-test is just a measure of a sample mean, divided by the standard error of the sample mean. That is it.</p>
</div>
<div id="what-does-t-represent" class="section level3">
<h3><span class="header-section-number">5.2.2</span> What does t represent?</h3>
<p><span class="math inline">\(t\)</span> gives us a measure of confidence, just like our previous ratio for dividing the mean by a standard deviations.</p>
<div class="marginnote">
<p>What does the t in t-test stand for? Apparently nothing. Gosset originally labelled it z. And, Fisher later called it t, perhaps because t comes after s, which is often used for the sample standard deviation.</p>
</div>
<p><span class="math inline">\(t\)</span> is a property of the data that you collect. You compute it with a sample mean, and a sample standard error (there’s one more thing in the one-sample formula, the population mean, which we get to in a moment). This is why we call <span class="math inline">\(t\)</span>, a sample-statistic. It’s a statistic we compute from the sample.</p>
<p>What kinds of numbers should we expect to find for these <span class="math inline">\(ts\)</span>? Well, wouldn’t that depend on a lot of things, how could we know that?</p>
<p>Let’s start small, and work through some examples. Imagine your sample mean is 5. You want to know if it came from a population that also has a mean of 5. In this case, what would t be? It would be zero, because we first subtract sample mean from the population mean, 5-5=0. So, t can be zero, when there is no difference.</p>
<p>Let’s say you take another sample, do you think the mean will be 5 every time, probably not. Let’s say the mean is 6. So, what can t be here? It will be a positive number, because 6-5= +1. But, will t be +1? That depends on the standard error of the sample. If the standard error of the sample is 1, then t could be 1, because 1/1 = 1.</p>
<p>If the sample standard error is smaller than 1, what happens to <span class="math inline">\(t\)</span>? It get’s bigger right? For example, 1 divided by 0.5 = 2. If the sample standard error was 0.5, t would be 2. And, what could we do with this information? Well, it be like a measure of confidence. As t get’s bigger we could be more confident in the mean difference we are measuring.</p>
<p>Can <span class="math inline">\(t\)</span> be smaller than 1? Sure, it can. If the sample standard error is big, say like 2, then <span class="math inline">\(t\)</span> will be smaller than one (in our case), e.g., 1/2 = .5. The direction of the difference between the sample mean and population mean, can also make the <span class="math inline">\(t\)</span> become negative. What if our sample mean was 4. Well, then <span class="math inline">\(t\)</span> will be negative, because the mean difference in the numerator will be negative, and the number in the bottom (denominator) will always be positive (remember why, it’s the standard error, computed from the sample standard deviation, which is always positive because of the squaring that we did.).</p>
<p>So, that is some intutions about what the kinds of values t can take. <span class="math inline">\(t\)</span> can be positive or negative, and big or small. Fine then, what can we do with this?</p>
</div>
<div id="calculating-t-from-data" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Calculating t from data</h3>
<p>Let’s briefly calculate a t-value from a small sample. Let’s say we had 10 students do a true/false quiz 5 questions on it. There’s a 50% chance of getting each answer correct.</p>
<p>Every student completes the 5 questions, we grade them, and then we find their performance (mean percent correct). Want we want to know is whether the students were guessing. If they were all guessing, then the sample mean should be about 50%, it shouldn’t be different from chance, which is 50%. Let’s look at the table:</p>
<table>
<thead>
<tr class="header">
<th align="left">students</th>
<th align="left">scores</th>
<th align="left">mean</th>
<th align="left">Difference_from_Mean</th>
<th align="left">Squared_Deviations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">50</td>
<td align="left">61</td>
<td align="left">-11</td>
<td align="left">121</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">70</td>
<td align="left">61</td>
<td align="left">9</td>
<td align="left">81</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">60</td>
<td align="left">61</td>
<td align="left">-1</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">40</td>
<td align="left">61</td>
<td align="left">-21</td>
<td align="left">441</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">80</td>
<td align="left">61</td>
<td align="left">19</td>
<td align="left">361</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">30</td>
<td align="left">61</td>
<td align="left">-31</td>
<td align="left">961</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="left">90</td>
<td align="left">61</td>
<td align="left">29</td>
<td align="left">841</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left">60</td>
<td align="left">61</td>
<td align="left">-1</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="left">70</td>
<td align="left">61</td>
<td align="left">9</td>
<td align="left">81</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="left">60</td>
<td align="left">61</td>
<td align="left">-1</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">Sums</td>
<td align="left">610</td>
<td align="left">610</td>
<td align="left">0</td>
<td align="left">2890</td>
</tr>
<tr class="even">
<td align="left">Means</td>
<td align="left">61</td>
<td align="left">61</td>
<td align="left">0</td>
<td align="left">289</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">sd</td>
<td align="left">17.92</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">SEM</td>
<td align="left">5.67</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">t</td>
<td align="left">1.94003527336861</td>
</tr>
</tbody>
</table>
<p>You can see the column column has all of the test scores for each of the 10 students. We did the things we need to do to compute the standard deviation.</p>
<p>Remember the sample standard deviation is the square root of the sample variance, or:</p>
<p><span class="math inline">\(\text{sample standard deviation} = \sqrt{\frac{\sum_{i}^{n}({x_{i}-\bar{x})^2}}{N-1}}\)</span></p>
<p><span class="math inline">\(\text{sd} = \sqrt{\frac{2890}{10-1}} = 17.92\)</span></p>
<p>The standard error of the mean, is the standard deviation divided by the square root of N</p>
<p>$ =  =  = 5.67 $</p>
<p><span class="math inline">\(t\)</span> is the difference between our sample mean (61), and our population mean (50, assuming chance), divided by the standard error of the mean.</p>
<p><span class="math inline">\(\text{t} = \frac{\bar{X}-u}{S_{\bar{X}}} = \frac{\bar{X}-u}{SEM} = \frac{61-50}{5.67} = 1.94\)</span></p>
<p>And, that is you how calculate <span class="math inline">\(t\)</span>, by hand. It’s a pain. I was annoyed doing it this way. In the lab, you learn how to calculate <span class="math inline">\(t\)</span> using software, so it will just spit out <span class="math inline">\(t\)</span>. For example in R, all you have to do is this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">t.test</span>(scores, <span class="dt">mu=</span><span class="dv">50</span>)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  scores
## t = 1.9412, df = 9, p-value = 0.08415
## alternative hypothesis: true mean is not equal to 50
## 95 percent confidence interval:
##  48.18111 73.81889
## sample estimates:
## mean of x 
##        61</code></pre>
</div>
<div id="how-does-t-behave" class="section level3">
<h3><span class="header-section-number">5.2.4</span> How does <span class="math inline">\(t\)</span> behave?</h3>
<p>If <span class="math inline">\(t\)</span> is just a number that we can from our sample (it is), what can we do with it? How can we use <span class="math inline">\(t\)</span> for statistical inference?</p>
<p>Remember back to the chapter on sampling and distributions, that’s where we discussed the sampling distribution of the sample mean. Remember, we made a lot of samples, then computed the mean for each sample, then we plotted a histogram of the sample means. Later, in that same section, we mentioned that we could generate sampling distributions for any statistic. That, for each sample, we could compute the mean, the standard deviation, the standard error, and now even <span class="math inline">\(t\)</span>, if we wanted to. We could generate 10,000 samples, and draw four histograms, one for each sampling distribution for each statistic.</p>
<p>This is exactly what I did, and the results are shown in the four figures below. I used a sample size of 20, and drew random observations for each sample from a normal distribution, with mean = 0, and standard deviation = 1. Let’s look at the sampling distributions for each of the statistics. <span class="math inline">\(t\)</span> was computed assuming with the population mean assumed to be 0.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-82-1.png" width="672" /></p>
<p>We see four sampling distributions. This is how statistical summaries of these summaries behave. We have used the word chance windows before. These are four chance windows, measuring different aspects of the sample. In this case, all of the samples came from the same normal distribution. Because of sampling error, each sample is not identical. The means are not identical, the standard deviations are not identical, sample standard error of the means are not identical, and the <span class="math inline">\(t\)</span>s of the samples are not identical. They all have some variation, as shown by the histograms. This is how samples, of size 20 behave.</p>
<p>We can see straight away, that in this case, we are unlikely to get a sample mean of 2. That’s way outside the window. The range for the sampling distribution of the mean is around -.5 to +.5, and is centered on 0 (the population mean, would you believe!).</p>
<p>We are unlikely to get sample standard deviations of between .6 and 1.5, that is a different range, specific to the sample standard deviation.</p>
<p>Same thing with the sample standard error of the mean, the range here is even smaller, mostly between .1, and .3. You would rarely find a sample with a standard error of the mean greater than .3. Virtually never would you find one of say 1 (for this situation).</p>
<p>Now, look at <span class="math inline">\(t\)</span>. It’s range is basically between -3 and +3 here. 3s barely happen at all. you pretty much never see a 5 or -5 in this situation.</p>
<p>All of these sampling windows are chance windows, and they can all be used in the same way as we have used similar sampling distributions before (e.g., Crump Test, and Randomization Test) for statistical inference. For all of them we would follow the same process:</p>
<ol style="list-style-type: decimal">
<li>Generate these distributions</li>
<li>Look at your sample statistics for the dat you have (mean, sd, sem, and <span class="math inline">\(t\)</span>)</li>
<li>Find out how likely each value (or greater than that value) is</li>
<li>Obtain that probability</li>
<li>See if you think your sample statistics were probable or improbable.</li>
</ol>
<p>We’ll formalize this in a second. I just want you to know that what you will be doing is something that you have already done before. For example, in the Crump test and the Randomization test we focused on the distribution of mean differences. We could do that again here, but instead, we will focus on the distribution of <span class="math inline">\(t\)</span> values. We then apply the same kinds of decision rules to the <span class="math inline">\(t\)</span> distribution, as we did for the other distributions. Below you will see a graph you have already seen, except this time it is a distribution of <span class="math inline">\(t\)</span>s, not mean differences:</p>
<p>Remember, if we obtained a single <span class="math inline">\(t\)</span> from one sample we collected, we could consult this chance window below to find out the <span class="math inline">\(t\)</span> we obtained from the sample was likely or unlikely to occur by chance.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
</div>
<div id="making-a-decision" class="section level3">
<h3><span class="header-section-number">5.2.5</span> Making a decision</h3>
<p>From our early example involving the TRUE/FALSE quizzes, we are not ready to make some kind of decision about what happended there. We found a mean difference of 11. We found a <span class="math inline">\(t\)</span> = 1.9411765. The probability of this <span class="math inline">\(t\)</span> or larger occuring is <span class="math inline">\(p\)</span> = 0.0841503. We were testing the idea that our sample mean of 61 could have come from a normal distribution with mean = 50. The <span class="math inline">\(t\)</span> test tells us that the <span class="math inline">\(t\)</span> for our sample, or a larger one, would happen with p = 0.0841503. In other words, chance can do it a kind of small amount of time, but not often. In english, this means that all of the students could have been, guessing, but it wasn’t that likely that were just guessing.</p>
<p>We’re guessing that you are still a little bit confused about <span class="math inline">\(t\)</span> values, and what we are doing here. We are going to skip ahead to the next <span class="math inline">\(t\)</span>-test, called a <strong>paired samples t-test</strong>. We will also fill in some more things about <span class="math inline">\(t\)</span>-tests that are more obvious when discussing paired samples t-test. In fact, spoiler alert, we will find out that paired samples t-test is actually a one-sample t-test in disguise (WHAT!), yes it is. If the one-sample <span class="math inline">\(t\)</span>-test didn’t make sense to you, read the next section.</p>
</div>
</div>
<div id="paired-samples-t-test" class="section level2">
<h2><span class="header-section-number">5.3</span> Paired-samples <span class="math inline">\(t\)</span>-test</h2>
<p>For me (Crump), many analyses often boil down to a paired samples t-test. It just happens that many things I do reduce down to a test like this.</p>
<p>I am a cognitive psychologist, I conduct research learn how people do things like remember, pay attention, and learn skills. There are lots of Psychologists like me, who do very similar things.</p>
<p>We all often conduct the same kinds of experiments. They go like this, and they are called <strong>repeated measures</strong> designs. They are called <strong>repeated measures</strong> designs, because we measure how one person does something more than once, we <strong>repeat</strong> the measure.</p>
<p>So, I might measure somebody doing something in condition A, and measure somebody doing something in Condition B, and then I see that same person does different things in the two conditions. I <strong>repeatedly measure</strong> the same person in both conditions. I am interested in whether the experimental manipulation changes something about how people perform the task in question.</p>
<div id="mehr-song-and-spelke-2016" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Mehr, Song, and Spelke (2016)</h3>
<p>We will introduce the paired-samples t-test with an example using real data, from a real study. Mehr, Song, and Spelke (2016) were interested in whether singing songs to infants helps infants become more sensitive to social cues. For example, infants might need to learn to direct their attention toward people, as a part of learning how to interact socially with people. Perhaps singing songs to infants aids this process of directing attention. When an infant hears a familiar song, they might start to pay more attention to the person singing that song, even after they are done singing the song. The person who sang the song, might become more socially important to the infant. You will learn more about this study in the lab for this week. This example, prepares you for the lab activities. Here is a brief summary of what they did:</p>
<p>First, parents were trained to sing a song to their infants. After many days of singing this song to the infants, the parent came into the lab with their infants. In the first session, parents sat with their infants on their knees, so the infant could watch two video presentations. There were two videos. Each video involved two unfamiliar new people the infant had never seen before. Each new person in the video (the singers) sang one song to the infant. One singer sang the “familiar” song the infant had learned from their parents. The other singer sang an “unfamiliar” song the infant had not hear before.</p>
<p>There were two really important measurement phases, the baseline phase, and the test phase. The baseline phase occured before the infants saw and heard each singer sing a song. During the baseline phase, the infants watched a video of both singers at the same time. The researchers recorded the proportion of time that the infant looked at each singer. The baseline phase was conducted to determine whether infants had a preference to look at either person (who would later sing them a song).</p>
<p>The test phase occurred after infants saw and heard each song, sung by each singer. During the test phase, each infant had an opportunity to watch silent videos of both singers. The researchers measured the proportion of time the infants spent looking at each person. The question of interest, was whether the infants would spend a greater proportion of time looking at the singer who sang the familiar song, compared to the singer who sang the unfamiliar song.</p>
<p>There is more than one way to describe the design of this study. We will describe it like this. It was a repeated measures design, with one independent (manipulation) variable called Viewing phase: Baseline versus Test. There was one dependent variable (the measurement), which was proportion looking time (to singer who sung familiar song). This was a repeated measures design because the researchers measured proportion looking time twice (they repeated the measure), once during baseline (before infants heard each singer sing a song), and again during test (after infants head each singer sing a song).</p>
<p>The important question was whether infants would change their looking time, and look more at the singer who sang the familiar song during the test phase, than they did during the baseline phase. This is a question about a change within individual infants. In general, the possible outcomes for the study are:</p>
<ol style="list-style-type: decimal">
<li><p>No change: The difference between looking time toward the singer of the familiar song during baseline and test is zero, no difference.</p></li>
<li><p>Positive change: Infants will look longer toward the singer of the familiar song during the test phase (after they saw and heard the singers), compared to the baseline phase (before they saw and heard the singers). This is a positive difference if we use the formula: Test Phase Looking time - Baseline phase looking time (to familiar song singer).</p></li>
<li><p>Negative change: Infants will look longer toward the singer of the unfamiliar song during the test phase (after they saw and heard the singers), compared to the baseline phase (before they saw and heard the singers). This is a negative difference if we use the same formula: Test Phase Looking time - Baseline phase looking time (to familiar song singer).</p></li>
</ol>
</div>
<div id="the-data" class="section level3">
<h3><span class="header-section-number">5.3.2</span> The data</h3>
<p>Let’s take a look at the data for the first 5 infants in the study. This will help us better understand some properties of the data before we anlayze it. We will see that the data is stuctured in a particular way, that we can take advantage of with a paired samples t-test. Note, we look at the first 5 infants to show how the computations work. The results of the paired-samples t-test change when we use all of the data from the study.</p>
<p>Here is a table of the data:</p>
<table>
<thead>
<tr class="header">
<th align="right">infant</th>
<th align="right">Baseline</th>
<th align="right">Test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">0.44</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">0.41</td>
<td align="right">0.68</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">0.75</td>
<td align="right">0.72</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">0.44</td>
<td align="right">0.28</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">0.47</td>
<td align="right">0.50</td>
</tr>
</tbody>
</table>
<p>The table shows proportion looking times toward the singer of the familiar song during the Baseline and Test phases. Notice there are five different infants, (1 to 5). Each infant is measured twice, once during the Baseline phase, and once during the Test phase. To repeat from before, this is a repeated-measures design, because the infants are measured repeatedly (twice in this case). Or, this kind of design is also called a <strong>paired-samples</strong> design. Why? because each participant comes with a pair of samples (two samples), one for each level of the design.</p>
<p>Great, so what are we really interested in here? We want to know if the mean looking time toward the singer of the familiar song for the Test phase is higher than the Baseline phase. We are comparing the two sample means against each other and looking for a difference. We already know that differences could be obtained by chance alone, simply because we took two sets of samples, and we know that samples can be different. So, we are interested in knowing whether chance was likely or unlikely to have produced any difference we might observe. .</p>
<p>In other words, we are interested in looking at the difference scores between the baseline and test phase for each infant. The question here is, for each infant, did their proportion looking time to the singer of the familiar song, increase during the test phase as compared to the baseline phase.</p>
</div>
<div id="the-difference-scores-1" class="section level3">
<h3><span class="header-section-number">5.3.3</span> The difference scores</h3>
<p>Let’s look add the difference scores to the table of data so it is easier to see what we are talking about. The first step in creating difference scores is to decide how you will take the difference, there are two options:</p>
<ol style="list-style-type: decimal">
<li>Test phase score - Baseline Phase Score</li>
<li>Baseline phase score - Test Phase score</li>
</ol>
<p>Let’s use the first formula. Why? Because it will give us positive differences when the test phase score is higher than the baseline phsae score. This makes a positive score meaningful with respect to the study design, we know (because we defined it to be this way), that positive scores will mean longer proportion looking times (to singer of familiar song) during the test phase compared to the baseline phase.</p>
<table>
<thead>
<tr class="header">
<th align="right">infant</th>
<th align="right">Baseline</th>
<th align="right">Test</th>
<th align="right">differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">0.44</td>
<td align="right">0.60</td>
<td align="right">0.16</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">0.41</td>
<td align="right">0.68</td>
<td align="right">0.27</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">0.75</td>
<td align="right">0.72</td>
<td align="right">-0.03</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">0.44</td>
<td align="right">0.28</td>
<td align="right">-0.16</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">0.47</td>
<td align="right">0.50</td>
<td align="right">0.03</td>
</tr>
</tbody>
</table>
<p>There we have it, the difference scores. The first thing we can do here is look at the difference scores, and ask how many infants showed the effect of interest. Specifically, how many infants showed a positive difference score. We can see that three of five infants showed a positive difference (they looked more at the singer of the familiar song during the test than baseline phase), and two the infants showed the opposite effect (negative difference, they looked more at the singer of the familiar song during baseline than test).</p>
</div>
<div id="the-mean-difference" class="section level3">
<h3><span class="header-section-number">5.3.4</span> The mean difference</h3>
<p>As we have been discussing, the effect of interest in this study is the mean difference between the baseline and test phase proportion looking times. We can calculate the mean difference, by finding the mean of the difference scores. Let’s do that, in fact, for fun let’s calculate the mean of the baseline scores, the test scores, and the difference scores.</p>
<table>
<thead>
<tr class="header">
<th align="left">infant</th>
<th align="left">Baseline</th>
<th align="left">Test</th>
<th align="left">differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">0.44</td>
<td align="left">0.6</td>
<td align="left">0.16</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">0.41</td>
<td align="left">0.68</td>
<td align="left">0.27</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">0.75</td>
<td align="left">0.72</td>
<td align="left">-0.03</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">0.44</td>
<td align="left">0.28</td>
<td align="left">-0.16</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">0.47</td>
<td align="left">0.5</td>
<td align="left">0.03</td>
</tr>
<tr class="even">
<td align="left">Sums</td>
<td align="left">2.51</td>
<td align="left">2.78</td>
<td align="left">0.27</td>
</tr>
<tr class="odd">
<td align="left">Means</td>
<td align="left">0.502</td>
<td align="left">0.556</td>
<td align="left">0.054</td>
</tr>
</tbody>
</table>
<p>We can see there was a positive mean difference of 0.054, between the test and baseline phases.</p>
<p>Now, can we rush to judgment and conclude that infants are more socially attracted to individuals who have sung them a familiar song? I would hope not based on this very small sample. First, the difference in proportion looking isn’t very large, and of course we recognize that this difference could have been produced by chance.</p>
<p>We will more formally evaluate whether this difference could have been caused by chance with the paired-samples t-test. But, before we do that, let’s again calculate <span class="math inline">\(t\)</span> and discuss what <span class="math inline">\(t\)</span> tells us over and above what our measure of the mean of the difference scores tells us.</p>
</div>
<div id="calculate-t" class="section level3">
<h3><span class="header-section-number">5.3.5</span> Calculate <span class="math inline">\(t\)</span></h3>
<p>Ok, so how do we calculate <span class="math inline">\(t\)</span> for a paired-samples <span class="math inline">\(t\)</span>-test? Surprise, we use the one-sample t-test formula that you already learned about! Specifically, we use the one-sample <span class="math inline">\(t\)</span>-test formula on the difference scores. We have one sample of difference scores (you can see they are in one column), so we can use the one-sample <span class="math inline">\(t\)</span>-test on the difference scores. Specifically, we are interested in comparing whether the mean of our difference scores came from a distibrution with mean difference = 0. This is a special distribution we refer to as the <strong>null distribution</strong>. It is the distribution no differences. Of course, this <strong>null distribution</strong> can produce differences due to to sampling error, but those differences are not caused by any experimental manipulation, they caused by the random sampling process.</p>
<p>We calculate <span class="math inline">\(t\)</span> in a moment. Let’s now consider again why we want to calculate <span class="math inline">\(t\)</span>? Why don’t we just stick with the mean difference we already have?</p>
<p>Remember, the whole concept behind <span class="math inline">\(t\)</span>, is that it gives an indication of how confident we should be in our mean. Remember, <span class="math inline">\(t\)</span> involves a measure of the mean in the numerator, divided by a measure of variation (standard error of the sample mean) in the denonimator. The resulting <span class="math inline">\(t\)</span> value is small when the mean difference is small, or when the variation is large. So small <span class="math inline">\(t\)</span>-values tell us that we shouldn’t be that confident in the estimate of our mean difference. Large <span class="math inline">\(t\)</span>-values occur when the mean difference is large and/or when the measure of variation is small. So, large <span class="math inline">\(t\)</span>-values tell us that we can be more confident in the estimate of our mean difference. Let’s find <span class="math inline">\(t\)</span> for the mean difference scores. We use the same formulas as we did last time:</p>
<table>
<thead>
<tr class="header">
<th align="left">infant</th>
<th align="left">Baseline</th>
<th align="left">Test</th>
<th align="left">differences</th>
<th align="left">diff_from_mean</th>
<th align="left">Squared_differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">0.44</td>
<td align="left">0.6</td>
<td align="left">0.16</td>
<td align="left">0.106</td>
<td align="left">0.011236</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">0.41</td>
<td align="left">0.68</td>
<td align="left">0.27</td>
<td align="left">0.216</td>
<td align="left">0.046656</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">0.75</td>
<td align="left">0.72</td>
<td align="left">-0.03</td>
<td align="left">-0.084</td>
<td align="left">0.00705600000000001</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">0.44</td>
<td align="left">0.28</td>
<td align="left">-0.16</td>
<td align="left">-0.214</td>
<td align="left">0.045796</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">0.47</td>
<td align="left">0.5</td>
<td align="left">0.03</td>
<td align="left">-0.024</td>
<td align="left">0.000575999999999999</td>
</tr>
<tr class="even">
<td align="left">Sums</td>
<td align="left">2.51</td>
<td align="left">2.78</td>
<td align="left">0.27</td>
<td align="left">0</td>
<td align="left">0.11132</td>
</tr>
<tr class="odd">
<td align="left">Means</td>
<td align="left">0.502</td>
<td align="left">0.556</td>
<td align="left">0.054</td>
<td align="left">0</td>
<td align="left">0.022264</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">sd</td>
<td align="left">0.167</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">SEM</td>
<td align="left">0.075</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">t</td>
<td align="left">0.72</td>
</tr>
</tbody>
</table>
<p>If we did this test using R, we would obtain almost the same numbers (there is a little bit of rounding in the table).</p>
<pre><code>## 
##  One Sample t-test
## 
## data:  differences
## t = 0.72381, df = 4, p-value = 0.5092
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.1531384  0.2611384
## sample estimates:
## mean of x 
##     0.054</code></pre>
<p>Here is a quick write up of our t-test results, t(4) = .72, p = .509.</p>
<p>What does all of that tell us? There’s a few things we haven’t gotten into much yet. For example, the 4 represents degrees of freedom, which we discuss later. The important part, the <span class="math inline">\(t\)</span> value should start to be a little bit more meaningful. We got a kind of small t-value didn’t we. It’s .72. What can we tell from this value? First, it is positive, so we know the mean difference is positive. The sign of the <span class="math inline">\(t\)</span>-value is always the same as the sign of the mean difference (ours was +0.054). We can also see that the p-value was .509. We’ve seen p-values before. This tells us that our <span class="math inline">\(t\)</span> value or larger, occurs about 50.9% of the time… Actually it means more than this. And, to understand it, we need to talk about the concept of two-tailed and one-tailed tests.</p>
</div>
<div id="interpreting-ts" class="section level3">
<h3><span class="header-section-number">5.3.6</span> Interpreting <span class="math inline">\(t\)</span>s</h3>
<p>Remember what it is we are doing here. We are evaluating whether our sample data could have come from a particular kind of distribution. The null distribution of no differences. This is the distribution of <span class="math inline">\(t\)</span>-values that would occur for samples of size 5, with a mean difference of 0, and a standard error of the sample mean of .075 (this is the SEM that we calculated from our sample). We can see what this particular null-distribution looks like by plotting it like this:</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<p>The <span class="math inline">\(t\)</span>-distribution above shows us the kinds of values <span class="math inline">\(t\)</span> will will take by chance alone, when we measure the mean differences for pairs of 5 samples (like our current). <span class="math inline">\(t\)</span> is most likely to be zero, which is good, because we are looking at the distribution of no-differences, which should most often be 0! But, sometimes, due to sampling error, we can get <span class="math inline">\(t\)</span>s that are bigger than 0, either in the positive or negative direction. Notice the distribution is symmetrical, a <span class="math inline">\(t\)</span> from the null-distribution will be positive half of the time, and negative half of the time, that is what we would expect by chance.</p>
<p>So, what kind of information do we want know when we find a particular <span class="math inline">\(t\)</span> value from our sample? We want to know how likely the <span class="math inline">\(t\)</span> value like the one we found occurs just by chance. This is actually a subtly nuanced kind of question. For example, any particular <span class="math inline">\(t\)</span> value doesn’t have a specific probability of occuring. When we talk about probabilities, we are talking about ranged of probabilities. Let’s consider some probabilities. We will use the letter <span class="math inline">\(p\)</span>, to talk about the probabilites of particulat <span class="math inline">\(t\)</span> values.</p>
<ol style="list-style-type: decimal">
<li><p>What is the probability that <span class="math inline">\(t\)</span> is zero or positive or negative? The answer is p=1, or 100%. We will always have a <span class="math inline">\(t\)</span> value that is zero or non-zero…Actually, if we can’t compute the t-value, for example when the standard deviaion is undefined, I guess then we would have a non-number. But, assuming we can calculate <span class="math inline">\(t\)</span>, then it will always be 0 or positive or negative.</p></li>
<li><p>What is the probability of <span class="math inline">\(t\)</span> = 0 or greater than 0? The answer is p=.5, or 50%. 50% of <span class="math inline">\(t\)</span>-values are 0 or greater.</p></li>
<li><p>What is the of <span class="math inline">\(t\)</span> = 0 or smaller than 0? The answer is p=.5, or 50%. 50% of <span class="math inline">\(t\)</span>-values are 0 or smaller.</p></li>
</ol>
<p>We can answer all of those questions just by looking at our t-distribution, an dividing it into two eqal regions, the left side (containing 50% of the $t values), and the right side containing 50% of the $t-values).</p>
<p>What if we wanted to take a more fine-grained approach, let’s say we were interested in regions of 10%. What kinds of <span class="math inline">\(t\)</span>s occur 10% of the time. We would apply lines like the following. Notice, the likelihood of bigger numbers (positive or negative) gets smaller, so we have to increase the width of the bars for each of the intervals between the bars to contain 10% of the t-values, it looks like this:</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>Consider the probabilities (p) of <span class="math inline">\(t\)</span> for the different ranges.</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(t\)</span> &lt;= -1.5 (t is les than or equal to -1.5), p = 10%</li>
<li>-1.5 &gt;= <span class="math inline">\(t\)</span> &lt;= -0.9 (t is equal to or between -1.5 and -.9), p = 10%</li>
<li>-.9 &gt;= <span class="math inline">\(t\)</span> &lt;= -0.6 (t is equal to or between -.9 and -.6), p = 10%</li>
<li><span class="math inline">\(t\)</span> &gt;= 1.5 (t is greater than or equal to 1.5), p = 10%</li>
</ol>
<p>Notice, that the <span class="math inline">\(p\)</span>s are always 10%. <span class="math inline">\(t\)</span>s occur in these ranges with 10% probability.</p>
</div>
<div id="getting-the-p-values-for-t-values" class="section level3">
<h3><span class="header-section-number">5.3.7</span> Getting the p-values for t-values</h3>
<p>You might be wondering where I am getting some of these values from. For example, how do I know that 10% of <span class="math inline">\(t\)</span> values (for this null distribution) have a value of approximately 1.5 or greater than 1.5? The answer is I used R to tell me.</p>
<p>In most statistics textbooks the answer would be, there is a table at the back of the book where you can look these things up…This textbook has no such table. We could make one for you. And, we might do that. But, we didn’t do that yet…</p>
<p>So, where do these values come from, how can you figure out what they are? The complicated answer is that we are not going to explain the math behind finding these values because 1) the authors (some of) admittedly don’t know the math well enough to explain it, and 2) it would sidetrack us to much, 3) you will learn how to get these numbers in the lab with software, 4) you will learn how to get these numbers in lab without the math, just by doing a simulation, and 5) you can do it in R, or excel, or you can use an <a href="http://www.socscistatistics.com/pvalues/tdistribution.aspx">online calculator</a>.</p>
<p>This is all to say that you can find the <span class="math inline">\(ts\)</span> and their associated <span class="math inline">\(ps\)</span> using software. But, the software won’t tell you what these values mean. That’s we are doing here. You will also see that software wants to know a few more things from you, such as the degrees of freedom for the test, and whether the test is one-tailed or two tailed. We haven’t explained any of these things yet. That’s what we are going to do now. Note, we explain degrees of freedom last. First, we start with a one-tailed test.</p>
</div>
<div id="one-tailed-tests" class="section level3">
<h3><span class="header-section-number">5.3.8</span> One-tailed tests</h3>
<p>A <strong>one-tailed test</strong> is sometimes also called a directional test. It is called a directional test, because a researcher might have a hypothesis in mind suggesting that the difference they observe in their means is going to have a particualr direction, either a positive difference, or a negative difference.</p>
<p>Typically, a researcher would set an alpha criterion. The alpha criterion describes a line in the sand for the researcher. Often, the alpha criterion is set at p=.05. What does this mean? Let’s look at again at the graph of the t-distribution, and show the alpha criterion.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-91-1.png" width="672" /></p>
<p>The figure shows that <span class="math inline">\(t\)</span> values of +2.13 or greater occur 5% of the time. Because the t-distribution is symmetrical, we also know that <span class="math inline">\(t\)</span> values of -2.13 or smaller also occur 5% of the time. Both of these properties are true under the null distribution of no differences. This means, that when there really are no differences, a researcher can expect to find <span class="math inline">\(t\)</span> values of 2.13 or larger 5% of the time.</p>
<p>Let’s review and connect some of the terms:</p>
<ol style="list-style-type: decimal">
<li><p><strong>alpha criterion</strong>: the criterion set by the researcher to make decisions about whether the believe chance did or did not cause the difference. The alpha criterion here is set to p=.05</p></li>
<li><p><strong>Critical <span class="math inline">\(t\)</span></strong>. The critical <span class="math inline">\(t\)</span> is the <span class="math inline">\(t\)</span>-value associated with the alpha-criterion. In this case for a one-tailed test, it is the <span class="math inline">\(t\)</span> value where 5% of all <span class="math inline">\(t\)</span>s are this number or greater. In our example, the critical <span class="math inline">\(t\)</span> is 2.13. 5% of all <span class="math inline">\(t\)</span> values (with degrees of freedom = 4) are +2.13, or greater than +2.13.</p></li>
<li><p><strong>Observed <span class="math inline">\(t\)</span></strong>. The observed <span class="math inline">\(t\)</span> is the one that you calculated from your sample. In our example about the infants, the observed <span class="math inline">\(t\)</span> was <span class="math inline">\(t\)</span> (4) = 0.72.</p></li>
<li><p><strong>p-value</strong>. The <strong>p-value</strong> is the probability of obtaining the observed <span class="math inline">\(t\)</span> value or larger. Now, you could look back at our previous example, and find that the p-value for <span class="math inline">\(t\)</span> (4) = .72, was p=.509. HOWEVER, this p-value was not calculated for a one-directional test…(we talk about what .509 means in the next section).</p></li>
</ol>
<p>Let’s see what p-value for <span class="math inline">\(t\)</span> (4) = .72 using a one-directional test would be, and what it would look like:</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>Let’s take this one step at a time. We have located the observed <span class="math inline">\(t\)</span> of .72 on the graph. We shaded right region all grey. What we see is that the grey region represents .256 or 25.6% of all <span class="math inline">\(t\)</span> values. In other words, 25.6% of <span class="math inline">\(t\)</span> values are .72 or larger than .72. You could expect, by chance alone, to a find a <span class="math inline">\(t\)</span> value of .72 or larger, 25.6% of the time. That’s fairly often. We did find a <span class="math inline">\(t\)</span> value of .72. Now that you know this kind of <span class="math inline">\(t\)</span> value or larger occurs 25.6% of the time, would you be confident that the mean difference was not due to chance? Probably not, given that chance can produce this difference fairly often.</p>
<p>Following the “standard” decision making procedure, we would claim that our <span class="math inline">\(t\)</span> value was <strong>not statistically significant</strong>, because it was not large enough. If our observed value was larger than the critical <span class="math inline">\(t\)</span> (larger than 2.13), defined by our alpha criterion, then we would claim that our <span class="math inline">\(t\)</span> value was <strong>statistically signicant</strong>. This would be equivalent to saying that we believe it is unlikely that the difference we observed was due to chance. In general, for any observed <span class="math inline">\(t\)</span> value, the associated p-value tells you how likely a <span class="math inline">\(t\)</span> of the observed size or larger would be observed. The p-value <strong>always</strong> refers to a <strong>range</strong> of t-values, never to a single t-value. Researchers use the alpha criterion of .05, as a matter of convenience and convention. There are other ways to interpret these values that do not rely on a strict (significant versus not) dichotomy.</p>
</div>
<div id="two-tailed-tests" class="section level3">
<h3><span class="header-section-number">5.3.9</span> Two-tailed tests</h3>
<p>Ok so that is one-tailed tests… What are two tailed tests, what is that? The p-value that we orginally calculated from our paired-samples t-test was for a 2-tailed test. Often, the default is that the p-value is for a two-tailed test.</p>
<p>The two-tailed test, is asking a more general question about whether a difference is likely to have been produced by chance. The question is, what is probability of any difference. It is also called a <strong>non-directional</strong> test, because here we don’t care about the direction or sign of the difference (positive or negative), we just care if there is any kind of difference.</p>
<p>The same basic things as before are involved. We define an alpha criterion (<span class="math inline">\(\alpha = 0.05\)</span>). And, we say that any observed <span class="math inline">\(t\)</span> value that has a probability of p&lt;.05 (p is less than .05) will be called <strong>statistically signficant</strong>, and ones that are more likely (p&gt;.05, p is greater than .05) will be called null-results, or not statistically significant. The only difference is how we draw the alpha range. Before it was on the right side of the <span class="math inline">\(t\)</span> distribution (we were conducting a one-sided test remember, so we were only interested in one side).</p>
<p>Let’s just take a look at what the most extreme 5% of the t-values are, when we ignore if they are positive or negative:</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>Here is what we are seeing. A distribution of no differences (the null, which is what we are looking at), will produce <span class="math inline">\(t\)</span>s that are 2.78 or greater 2.5% of the time, and <span class="math inline">\(t\)</span>s that are -2.78 or smaller 2.5% of the time. 2.5% + 2.5% is a total of 5% of the time. We could also say that <span class="math inline">\(t\)</span>s large than +/- 2.78 occur 5% of the time.</p>
<p>As a result, the critical <span class="math inline">\(t\)</span> value is (+/-) 2.78 for a two-tailed test. As you can see, the two-tailed test is blind to the direction or sign of the difference. Because of this, the critical <span class="math inline">\(t\)</span> value is also higher for a two-tailed test, than for the one-tailed test that we did earlier. Hopefully, now you can see why it is called a two-tailed test. There are two tails of the distribution, one on the left and right, both shaded in green.</p>
</div>
<div id="one-or-two-tailed-which-one" class="section level3">
<h3><span class="header-section-number">5.3.10</span> One or two tailed, which one?</h3>
<p>Now that you know there are two kinds of tests, one-tailed, and two-tailed, which one should you use? There is some conventional wisdom on this, but also some debate. In the end, it is up to you to be able to justify your choice and why it is appropriate for you data. That is the real answer.</p>
<p>The conventional answer is that you use you one-tailed test when you have a theory or hypothesis that is making a directional prediction (the theory predicts that the difference will be positive, or negative). Similarly, use a two-tailed test when you are looking for any difference, and you don’t have a theory that makes a directional prediction (it just makes the prediction that there will be a difference, either postive or negative).</p>
<p>Also, people appear to choose a one or two-tailed test based on how risky they are as researchers. If you always ran one-tailed tests, your critical <span class="math inline">\(t\)</span> values for your set alpha criterion would always be smaller than the critical <span class="math inline">\(t\)</span>s for a two-tailed test. Over the long run, you would make more type I errors, because the criterion to detect an effect is a lower bar for one than two tailed tests. Similarly, if you always ran two-tailed tests, even when you had a directional prediction, you would make fewer type I errors over the long run, because the <span class="math inline">\(t\)</span> for a two-tailed test is higher than the <span class="math inline">\(t\)</span> for a one-tailed test. It seems quite common for researchers to use a more conservative two-tailed test, even when they are making a directional prediction based on theory. In practice, researchers tend to adopt a standard for reporting that is common in their field. Whether or not the practice is justifiable can sometimes be an open question. The important task for any researcer, or student learning statistics, is to be able to justify their choice of test.</p>
</div>
<div id="degrees-of-freedom" class="section level3">
<h3><span class="header-section-number">5.3.11</span> Degrees of freedom</h3>
<p>Before we finsih up with paired-samples t-tests, we should talk about degrees of freedom. Our sense is that students don’t really understand degrees of freedom very well. If you are reading this textbook, you are probably still wondering what is degrees of freedom, seeing as we haven’t really talked about it all.</p>
<p>For the t-test, there is a formula for degrees of freedom. For the one-sample and paired sample t-tests, the formula is:</p>
<p><span class="math inline">\(\text{Degrees of Freedom} = \text{df} = n-1\)</span>. Where n is the number of samples in the test.</p>
<p>In our paired t-test example, there were 5 infants. Therefore, degrees of freedom = 5-1 = 4.</p>
<p>Ok, that’s formula. Who cares about degrees of freedom, what does the number mean? And why do we report it when we report a t-test…you’ve probably noticed the number in parentheses e.g., t(4)=.72, the 4 is the df, or degrees of freedom.</p>
<p>Degrees of freedom is both a concept, and a correction. The concept is that if you estimate a property of the numbers, and you use this estimate, you will be forcing some contraints on your numbers.</p>
<p>Consider the numbers: 1, 2, 3. The mean of these numbers is 2. Now, let’s say I told you that the mean of three numbers is 2. Then, how many of these three numbers have freedom? Funny question right. What we mean is, how many of the three numbers could be any number…has the freedom to be any number.</p>
<p>The first two numbers could be any number. But, once those two numbers are set, the final number (the third number), MUST be a particular number that makes the mean 2. The first two numbers have freedom. The third number has no freedom. It is forced…</p>
<p>To illustrate. Let’s freely pick two numbers: 51 and -3. I used my personal freedom to pick those two numbers. Now, if our three numbers are 51, -3, and x, and the mean of these three numbers is 2. There is only one solution, x has to be -42, otherwise the mean won’t be 2. This is one way to think about degrees of freedom. The degrees of freedom for these three numbers is n-1 = 3-1= 2, because 2 of the numbers can be free, but the last number has no freedom, it becomes fixed after the first two are decided.</p>
<p>Now, statisticians often apply degrees of freedom to their calculations, especially when a second calculation relies on an estimated value. For example, when we calculate the standard deviation of a sample, we first calculate the mean of the sample right! By estimating the mean, we are fixing an aspect of our sample, and so, our sample now has n-1 degrees of freedom when we calculate the standard deviation (remember for the sample standard deviation, we divide by n-1…there’s that n-1 again.)</p>
<div id="simulating-how-degrees-of-freedom-affects-the-t-distribution" class="section level4">
<h4><span class="header-section-number">5.3.11.1</span> Simulating how degrees of freedom affects the t distribution</h4>
<p>There are at least two ways to think the degrees of freedom for a t-test. For example, if you want to use math to compute aspects of the <span class="math inline">\(t\)</span> distribution, then you need the degrees of freedom to plug in to the formula… If you want to see the formulas I’m talking about, scroll down on the <a href="https://en.wikipedia.org/wiki/Student%27s_t-distribution">t-test wikipedia page</a> and look for the probability density or cumulative distribution functions…We think that is quite scary for most people, and one reason why degrees of freedom are not well-understood.</p>
<p>If we wanted to simulate the t distribution we could more easily see what influence degrees of freedom has on the shape of the distribution. Remember, <span class="math inline">\(t\)</span> is a sample statistic, it is something we measure from the sample. So, we could simulate the process of measuring <span class="math inline">\(t\)</span> from many different samples, then plot the histogram of <span class="math inline">\(t\)</span> to show us the simualted <span class="math inline">\(t\)</span> distribution.</p>
<p><img src="statistics_files/figure-html/unnamed-chunk-94-1.png" width="672" /></p>
<p>Notice that the red distribution for df =4, is a little bit shorter, and a little bit wider than the bluey-green distribution for df = 100. As degrees of freedom increase, the <span class="math inline">\(t\)</span>-distribution gets taller (in the middle), and narrower in the range. It get’s more peaky. Can you guess the reason for this? Remember, we are estimating a sample statistic, and degrees of freedom is really just a number that refers to the number of subjects (well minus). And, we already know that as we increase n, our sample statistics become better estimates (less variance) of the distributional parameters they are estimating. So, <span class="math inline">\(t\)</span> becomes a better estimate of it’s “true” value as sample size increase, and which results in a more narrow distribution of <span class="math inline">\(t\)</span>s.</p>
<p>There is a slightly different <span class="math inline">\(t\)</span> distribution for every degrees of freedom, and the critical regions associated with 5% of the extreme values are thus slightly different everytime. This is why we report the degrees of freedom for each t-test, they define the distribution of <span class="math inline">\(t\)</span> values for the sample-size in question. Why do we use n-1 and not n? Well, we calcualte <span class="math inline">\(t\)</span> using the sample standard deviation to estimate the standard error or the mean, that estimate uses n-1 in the denominator, so our <span class="math inline">\(t\)</span> distribution is built assuming n-1. That’s enough for degrees of freedom…</p>
</div>
</div>
</div>
<div id="the-paired-samples-t-test-strikes-back" class="section level2">
<h2><span class="header-section-number">5.4</span> The paired samples t-test strikes back</h2>
<p>You must be wondering if we will ever be finished talking about paired samples t-tests…why are we doing round 2, oh no! Don’t worry, we’re just going to 1) remind you about what we were doing with infant study, and 2) do a paired samples t-test on the entire data set and discuss.</p>
<p>Remember, we were wondering if the infants would look longer toward the singer who sang the familiar song during the test phase compared to the baseline phase. We showed you data from 5 infants, and walked through the computations for the t-test. As a reminder, it looked like this:</p>
<table>
<thead>
<tr class="header">
<th align="left">infant</th>
<th align="left">Baseline</th>
<th align="left">Test</th>
<th align="left">differences</th>
<th align="left">diff_from_mean</th>
<th align="left">Squared_differences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="left">0.44</td>
<td align="left">0.6</td>
<td align="left">0.16</td>
<td align="left">0.106</td>
<td align="left">0.011236</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="left">0.41</td>
<td align="left">0.68</td>
<td align="left">0.27</td>
<td align="left">0.216</td>
<td align="left">0.046656</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">0.75</td>
<td align="left">0.72</td>
<td align="left">-0.03</td>
<td align="left">-0.084</td>
<td align="left">0.00705600000000001</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="left">0.44</td>
<td align="left">0.28</td>
<td align="left">-0.16</td>
<td align="left">-0.214</td>
<td align="left">0.045796</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="left">0.47</td>
<td align="left">0.5</td>
<td align="left">0.03</td>
<td align="left">-0.024</td>
<td align="left">0.000575999999999999</td>
</tr>
<tr class="even">
<td align="left">Sums</td>
<td align="left">2.51</td>
<td align="left">2.78</td>
<td align="left">0.27</td>
<td align="left">0</td>
<td align="left">0.11132</td>
</tr>
<tr class="odd">
<td align="left">Means</td>
<td align="left">0.502</td>
<td align="left">0.556</td>
<td align="left">0.054</td>
<td align="left">0</td>
<td align="left">0.022264</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">sd</td>
<td align="left">0.167</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">SEM</td>
<td align="left">0.075</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left"></td>
<td align="left">t</td>
<td align="left">0.72</td>
</tr>
</tbody>
</table>
<pre><code>## 
##  One Sample t-test
## 
## data:  round(differences, digits = 2)
## t = 0.72381, df = 4, p-value = 0.5092
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -0.1531384  0.2611384
## sample estimates:
## mean of x 
##     0.054</code></pre>
<p>Let’s write down the finding one more time: The mean difference was 0.054, <span class="math inline">\(t\)</span>(4) = .72, p=.509. We can also now confirm, that the p-value was from a two-tailed test. So, what does this all really mean.</p>
<p>Well, we can say that a <span class="math inline">\(t\)</span> value of with an absolute of .72 or larger occurs 50.9% of the time. More precisaly, the distribution of no differences (the null), will produce a <span class="math inline">\(t\)</span> value this large or larger 50.9% of the time. In other words, chance alone good have easily produced the <span class="math inline">\(t\)</span> value from our sample, and the mean difference we observed or .054, could easily have been a result of chance.</p>
<p>Let’s quickly put all of the data in the t-test, and re-run the test using all of the infant subjects.</p>
<pre><code>## 
##  One Sample t-test
## 
## data:  differences
## t = 2.4388, df = 31, p-value = 0.02066
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  0.01192088 0.13370412
## sample estimates:
## mean of x 
## 0.0728125</code></pre>
<p>Now we get a very different answer. We would summarise the results saying the mean difference was .073, t(31) = 2.44, p = 0.020. How many total infants were their? Well the degrees of freedrom was 31, so there must have been 32 infants in the study. Now we see a much smaller p-value. This was also a two-tailed test, so we that observing a <span class="math inline">\(t\)</span> value of 2.4 or greater (absolute value) only occurs 2% of the time. In other words, the distribution of no differences will produce the observed t-value very rarely. So, it is unlikely that the observed mean difference of .073 was due to chance (it could have been due to chance, but that is very unlikely). As a result, we can be somewhat confident in concluding that something about seeing and hearing a unfamiliar person sing a familiar song, causes an infant to draw their attention toward the singer, and this potentially benefits social learning on the part of the infant.</p>
</div>
<div id="independent-samples-t-test-the-return-of-the-t-test" class="section level2">
<h2><span class="header-section-number">5.5</span> Independent samples t-test: The return of the t-test?</h2>
<p>If you’ve been following the Star Wars references, we are on last movie…the independent t-test. This were basically the same plot happens, only slightly different.</p>
<p>Remember there are different t-tests for different kinds of research designs. When your design is a <strong>between-subjects</strong> design, you use an <strong>independent samples t-test</strong>. Between-subjects design involve different people or subjects in each experimental condition. If there are two conditions, and 10 people in each, then there are 20 total people. And, there are no paired scores, because every single person is measured once, not twice, no repeated measures. Because there are no repeated measures we can not look at the difference scores between conditions one and two. The scores are not paired in any meaningful way, to it doesn’t make sense to subtract them. So what do we do?</p>
<p>The logic of the independent samples t-test is the very same as the other t tests. We calculated the means for each group, then we find the difference. That goes into the numerator of the t formala. Then we get an estimate of the variation for the denominator. We divide the mean difference by the estimate of the variation, and we get t. It’s the same as before.</p>
<p>The only wrinkly here is what goes into the denominator? How should we calculate the estimate of the variance? It would be nice if we could do seomething very straightforward like this, say for a n experiment with two groups A and B:</p>
<p><span class="math inline">\(t = \frac{\bar{A}-\bar{B}}{(\frac{SEM_A+SEM_B}{2})}\)</span></p>
<p>In plain language, this is just:</p>
<ol style="list-style-type: decimal">
<li>Find the mean difference for the top part</li>
<li>Compute the SEM (standard error of the mean) for each group, and average them together to make a single estimate, pooling over both samples.</li>
</ol>
<p>This would be nice, but unfortunately, it turns out that finding the average of two standard errors of the mean is not the best way to do it. This would create a biased estimator of the variation in for the hypothesized distribution of no differences. We won’t go into the math here, but instead of the above formula, we an use a different one that gives as an <strong>unbiased estimate of the pooled standard error of the sample mean</strong>. Our new and improved t formula would look like this:</p>
<p><span class="math inline">\(t = \frac{\bar{X_A}-\bar{X_B}}{s_p * \sqrt{\frac{1}{n_A} + \frac{1}{n_B}}}\)</span></p>
<p>and, <span class="math inline">\(s_p\)</span>, which is the pooled sample standard deviation is defined as, note the s’s in the formula are variances:</p>
<p><span class="math inline">\(s_p = \sqrt{\frac{(n_A-1)s_A^2 + (n_B-1)s^2_B}{n_A +n_B -2}}\)</span></p>
<p>Believe you me, that is so much more formula than I wanted to type out. Shall we do one independent t-test example by hand, just to see the computations? Let’s do it…but in a slightly different way than you expect. I show the steps using R. I made some fake scores for groups A and B. Then, I followed all of the steps from the formula, but made R do each of the calculations. This shows you the needed steps by following the code. At the end, I print the t-test values I computed “by hand”, and then the t-test value that the R software outputs using the t-test function. You should be able to get the same values for <span class="math inline">\(t\)</span>, if you were brave enough to compute <span class="math inline">\(t\)</span> by hand.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## By &quot;hand&quot; using R r code
a &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>)
b &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">9</span>)

mean_difference &lt;-<span class="st"> </span><span class="kw">mean</span>(a)-<span class="kw">mean</span>(b) <span class="co"># compute mean difference</span>

variance_a &lt;-<span class="st"> </span><span class="kw">var</span>(a) <span class="co"># compute variance for A</span>
variance_b &lt;-<span class="st"> </span><span class="kw">var</span>(b) <span class="co"># compute variance for B</span>

<span class="co"># Compute top part and bottom part of sp formula</span>

sp_numerator &lt;-<span class="st"> </span>(<span class="dv">4</span>*variance_a +<span class="st"> </span><span class="dv">4</span>*<span class="st"> </span>variance_b) 
sp_denominator &lt;-<span class="st"> </span><span class="dv">5+5-2</span>
sp &lt;-<span class="st"> </span><span class="kw">sqrt</span>(sp_numerator/sp_denominator) <span class="co"># compute sp</span>


<span class="co"># compute t following formulat</span>

t &lt;-<span class="st"> </span>mean_difference /<span class="st"> </span>( sp *<span class="st"> </span><span class="kw">sqrt</span>( (<span class="dv">1</span>/<span class="dv">5</span>) +(<span class="dv">1</span>/<span class="dv">5</span>) ) )

t <span class="co"># print results</span></code></pre></div>
<pre><code>## [1] -2.017991</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># using the R function t.test</span>
<span class="kw">t.test</span>(a,b, <span class="dt">paired=</span><span class="ot">FALSE</span>, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  a and b
## t = -2.018, df = 8, p-value = 0.0783
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -5.5710785  0.3710785
## sample estimates:
## mean of x mean of y 
##       3.0       5.6</code></pre>
<!--

Chapters [FoundationForInference] and [inferenceForCategoricalData] introduced us to inference for proportions using the normal model, and in Section [oneWayChiSquare], we encountered the chi-square distribution, which is useful for working with categorical data with many levels. In this chapter, our focus will be on numerical data, where we will encounter two more distributions: the $t$ distribution (looks a lot like the normal distribution) and the $F$ distribution. Our general approach will be:

1.  Determine which point estimate or test statistic is useful.

2.  Identify an appropriate distribution for the point estimate or test statistic.

3.  Apply the hypothesis and confidence interval techniques from Chapter [FoundationForInference] using the distribution from step 2.

## One-sample means with the $t$ distribution {#oneSampleMeansWithTDistribution}

The sampling distribution associated with a sample mean or difference of two sample means is, if certain conditions are satisfied, nearly normal. However, this becomes more complex when the sample size is small, where *small* here typically means a sample size smaller than 30 observations. For this reason, we’ll use a new distribution called the $t$ distribution that will often work for both small and large samples of numerical data.

### Two examples using the normal distribution

Before we get started with the $t$ distribution, let’s take a look at two applications where it is okay to use the normal model for the sample mean. For the case of a single mean, the standard error of the sample mean can be calculated as

$$\begin{aligned}
SE = \frac{\sigma}{\sqrt{n}}\end{aligned}$$

where $\sigma$ is the population standard deviation and $n$ is the sample size. Generally we use the sample standard deviation, denoted by $s$, in place of the population standard deviation when we compute the standard error:

$$\begin{aligned}
SE \approx \frac{s}{\sqrt{n}}\end{aligned}$$

If we look at this formula, there are some characteristics that we can think about intuitively.

-   If we examine the standard error formula, we would see that a larger $s$ corresponds to a larger $SE$. This makes intuitive sense: if the data are more volatile, then we’ll be less certain of the location of the true mean, so the standard error should be bigger. On the other hand, if the observations all fall very close together, then $s$ will be small, and the sample mean should be a more precise estimate of the true mean.

-   In the formula, the larger the sample size $n$, the smaller the standard error. This matches our intuition: we expect estimates to be more precise when we have more data, so the standard error $SE$ should get smaller when $n$ gets bigger.

As we did with proportions, we’ll also need to check a few conditions before using the normal model. We’ll forgo describing those details until later this section, but these conditions have been verified for the two examples below.

<span>We’ve taken a random sample of 100 runners from a race called the Cherry Blossom Run in Washington, DC, which was a race with 16,924 participants.[^4.1] The sample data for the 100 runners is summarized in Table [run10SampDF], histograms of the run time and age of participants are in Figure [run10SampHistograms], and summary statistics are available in Table [ptEstimatesNetTimeAge]. Create a 95% confidence interval for the average time it takes runners in the Cherry Blossom Run to complete the race.</span> We can use the same confidence interval formula for the mean that we used for a proportion:

$$\begin{aligned}
\text{point estimate}\ \pm\ 1.96 \times SE\end{aligned}$$

In this case, the best estimate of the overall mean is the sample mean, $\bar{x} = 95.61$ minutes. The standard error can be calculated using sample standard deviation ($s = 15.78$), the sample size ($n=100$), and the standard error formula:

$$\begin{aligned}
SE = \frac{s}{\sqrt{n}} = \frac{15.78}{\sqrt{100}} = 1.578\end{aligned}$$

Finally, we can calculate a 95% confidence interval:

$$\begin{aligned}
\text{point estimate}\ \pm\ z^{\star} \times SE \quad\rightarrow\quad
95.61 \pm 1.96 \times 1.578 \quad\rightarrow\quad
(92.52, 98.70)\end{aligned}$$

We are 95% confident that the average time for all runners in the 2012 Cherry Blossom Run is between 92.52 and 98.70 minutes.

          ID       time        age     gender      state
  ---------- ---------- ---------- ---------- ----------
           1      88.31         59          M         MD
           2     100.67         32          M         VA
           3     109.52         33          F         VA
    $\vdots$   $\vdots$   $\vdots$   $\vdots$   $\vdots$
         100      89.49         26          M         DC

  : Four observations for the **run10Samp** data set, which represents a simple random sample of 100 runners from the 2012 Cherry Blossom Run.

[run10SampDF]

![Histograms of **time** and **age** for the sample Cherry Blossom Run data. The average time is in the mid-90s, and the average age is in the mid-30s. The age distribution is moderately skewed to the right.](04/figures/run10SampHistograms/run10SampHistograms)

[run10SampHistograms]

  ----------------- ------- -------
  sample mean         95.61   35.05
  sample median       95.37   32.50
  sample st. dev.     15.78    8.97
  ----------------- ------- -------

  : Point estimates and parameter values for the **time** variable.

[ptEstimatesNetTimeAge]

Use the data to calculate a 90% confidence interval for the average age of participants in the 2012 Cherry Blossom Run. The conditions for applying the normal model have already been verified.[^4.2]

<span>The nutrition label on a bag of potato chips says that a one ounce (28 gram) serving of potato chips has 130 calories and contains ten grams of fat, with three grams of saturated fat. A random sample of 35 bags yielded a sample mean of 134 calories with a standard deviation of 17 calories. Is there evidence that the nutrition label does not provide an accurate measure of calories in the bags of potato chips? The conditions necessary for applying the normal model have been checked and are satisfied.</span> The question has been framed in terms of two possibilities: the nutrition label accurately lists the correct average calories per bag of chips or it does not, which may be framed as a hypothesis test:

-   The average is listed correctly. $\mu = 130$

-   The nutrition label is incorrect. $\mu \neq 130$

The observed average is $\bar{x} = 134$ and the standard error may be calculated as $SE = \frac{17}{\sqrt{35}} = 2.87$. First, we draw a picture summarizing this scenario.

![image](04/figures/potatoChips/potatoChips)

We can compute a test statistic as the Z score:

$$\begin{aligned}
Z = \frac{134 - 130}{2.87} = 1.39\end{aligned}$$

The upper-tail area is 0.0823, so the p-value is $2 \times 0.0823 = 0.1646$. Since the p-value is larger than 0.05, we do not reject the null hypothesis. That is, there is not enough evidence to show the nutrition label has incorrect information.

The normal model works well when the sample size is larger than about 30. For smaller sample sizes, we run into a problem: our estimate of $s$, which is used to compute the standard error, isn’t as reliable when the sample size is small. To solve this problem, we’ll use a new distribution: the $t$ distribution.

### Introducing the $t$ distribution {#introducingTheTDistribution}

A $t$ distribution, shown as a solid line in Figure [tDistCompareToNormalDist], has a bell shape that looks very similar to a normal distribution (dotted line). However, its tails are thicker, which means observations are more likely to fall beyond two standard deviations from the mean than under the normal distribution.[^4.3] When our sample is small, the value $s$ used to compute the standard error isn’t very reliable. The extra thick tails of the $t$ distribution are exactly the correction we need to resolve this problem.

![Comparison of a $t$ distribution (solid line) and a normal distribution (dotted line).](04/figures/tDistCompareToNormalDist/tDistCompareToNormalDist)

[tDistCompareToNormalDist]

The $t$ distribution, always centered at zero, has a single parameter: degrees of freedom. The describe the precise form of the bell-shaped $t$ distribution. Several $t$ distributions are shown in Figure [tDistConvergeToNormalDist] with various degrees of freedom. When there are more degrees of freedom, the $t$ distribution looks very much like the standard normal distribution.

![The larger the degrees of freedom, the more closely the $t$ distribution resembles the standard normal model.](04/figures/tDistConvergeToNormalDist/tDistConvergeToNormalDist)

[tDistConvergeToNormalDist]

<span> The degrees of freedom describe the shape of the $t$ distribution. The larger the degrees of freedom, the more closely the distribution approximates the normal model.</span>

When the degrees of freedom is about 30 or more, the $t$ distribution is nearly indistinguishable from the normal distribution, e.g. see Figure [tDistConvergeToNormalDist]. In Section [tDistSolutionToSEProblem], we relate degrees of freedom to sample size.

We will find it very useful to become familiar with the $t$ distribution, because it plays a very similar role to the normal distribution during inference for numerical data. We use a , partially shown in Table [tTableSample], in place of the normal probability table for small sample numerical data. A larger table is presented in Appendix . Alternatively, we could use statistical software to get this same information.

<span>r | rrr rr</span> one tail &

0.100 &

0.050 &

0.025 &

0.010 &

0.005\
two tails & 0.200 & 0.100 & 0.050 & 0.020 & 0.010\
 1 & <span>3.08</span> & <span>6.31</span> & <span>12.71</span> & <span>31.82</span> & <span>63.66</span>\
2 & <span>1.89</span> & <span>2.92</span> & <span>4.30</span> & <span>6.96</span> & <span>9.92</span>\
3 & <span>1.64</span> & <span>2.35</span> & <span>3.18</span> & <span>4.54</span> & <span>5.84</span>\
$\vdots$ & $\vdots$ &$\vdots$ &$\vdots$ &$\vdots$ &\
17 & <span>1.33</span> & <span>1.74</span> & <span>2.11</span> & <span>2.57</span> & <span>2.90</span>\
 & & & & &\
19 & <span>1.33</span> & <span>1.73</span> & <span>2.09</span> & <span>2.54</span> & <span>2.86</span>\
20 & <span>1.33</span> & <span>1.72</span> & <span>2.09</span> & <span>2.53</span> & <span>2.85</span>\
$\vdots$ & $\vdots$ &$\vdots$ &$\vdots$ &$\vdots$ &\
400 & <span>1.28</span> & <span>1.65</span> & <span>1.97</span> & <span>2.34</span> & <span>2.59</span>\
500 & <span>1.28</span> & <span>1.65</span> & <span>1.96</span> & <span>2.33</span> & <span>2.59</span>\
$\infty$ & <span>1.28</span> & <span>1.65</span> & <span>1.96</span> & <span>2.33</span> & <span>2.58</span>\

[tTableSample]

Each row in the $t$ table represents a $t$ distribution with different degrees of freedom. The columns correspond to tail probabilities. For instance, if we know we are working with the $t$ distribution with $df=18$, we can examine row 18, which is in Table [tTableSample]. If we want the value in this row that identifies the cutoff for an upper tail of 10%, we can look in the column where *one tail* is 0.100. This cutoff is 1.33. If we had wanted the cutoff for the lower 10%, we would use -1.33. Just like the normal distribution, all $t$ distributions are symmetric.

<span>What proportion of the $t$ distribution with 18 degrees of freedom falls below -2.10?</span> Just like a normal probability problem, we first draw the picture in Figure [tDistDF18LeftTail2Point10] and shade the area below -2.10. To find this area, we identify the appropriate row: $df=18$. Then we identify the column containing the absolute value of -2.10; it is the third column. Because we are looking for just one tail, we examine the top line of the table, which shows that a one tail area for a value in the third row corresponds to 0.025. About 2.5% of the distribution falls below -2.10. In the next example we encounter a case where the exact $t$ value is not listed in the table.

![The $t$ distribution with 18 degrees of freedom. The area below -2.10 has been shaded.](04/figures/tDistDF18LeftTail2Point10/tDistDF18LeftTail2Point10)

[tDistDF18LeftTail2Point10]

<span>A $t$ distribution with 20 degrees of freedom is shown in the left panel of Figure [tDistDF20RightTail1Point65]. Estimate the proportion of the distribution falling above 1.65.</span> We identify the row in the $t$ table using the degrees of freedom: $df=20$. Then we look for 1.65; it is not listed. It falls between the first and second columns. Since these values bound 1.65, their tail areas will bound the tail area corresponding to 1.65. We identify the one tail area of the first and second columns, 0.050 and 0.10, and we conclude that between 5% and 10% of the distribution is more than 1.65 standard deviations above the mean. If we like, we can identify the precise area using statistical software: 0.0573.

![Left: The $t$ distribution with 20 degrees of freedom, with the area above 1.65 shaded. Right: The $t$ distribution with 2 degrees of freedom, with the area further than 3 units from 0 shaded.](04/figures/tDistDF20RightTail1Point65/tDistDF20RightTail1Point65)

[tDistDF20RightTail1Point65]

<span>A $t$ distribution with 2 degrees of freedom is shown in the right panel of Figure [tDistDF20RightTail1Point65]. Estimate the proportion of the distribution falling more than 3 units from the mean (above or below).</span> As before, first identify the appropriate row: $df=2$. Next, find the columns that capture 3; because $2.92 < 3 < 4.30$, we use the second and third columns. Finally, we find bounds for the tail areas by looking at the two tail values: 0.05 and 0.10. We use the two tail values because we are looking for two (symmetric) tails.

What proportion of the $t$ distribution with 19 degrees of freedom falls above -1.79 units?[^4.4]

### Applying the $t$ distribution to the single-mean situation {#tDistSolutionToSEProblem}

When estimating the mean and standard error from a sample of numerical data, the $t$ distribution is a little more accurate than the normal model. This is true for both small and large samples, though the benefits for larger samples are limited.

<span> Use the $t$ distribution for inference of the sample mean when observations are independent and nearly normal. You may relax the nearly normal condition as the sample size increases. For example, the data distribution may be moderately skewed when the sample size is at least 30. </span>

Before applying the $t$ distribution for inference about a single mean, we check two conditions.

Independence of observations.

:   We verify this condition just as we did before. We collect a simple random sample from less than 10% of the population, or if the data are from an experiment or random process, we carefully check to the best of our abilities that the observations were independent.

Observations come from a nearly normal distribution.

:   This second condition is difficult to verify with small data sets. We often (i) take a look at a plot of the data for obvious departures from the normal model, usually in the form of prominent outliers, and (ii) consider whether any previous experiences alert us that the data may not be nearly normal. However, if the sample size is somewhat large, then we can relax this condition, e.g. moderate skew is acceptable when the sample size is 30 or more, and strong skew is acceptable when the size is about 60 or more.

When examining a sample mean and estimated standard error from a sample of $n$ independent and nearly normal observations, we use a $t$ distribution with $n-1$ degrees of freedom ($df$). For example, if the sample size was 19, then we would use the $t$ distribution with $df=19-1=18$ degrees of freedom and proceed in the same way as we did in Chapter [inferenceForCategoricalData], except that *now we use the $t$ table*.

<span> If the sample has $n$ observations and we are examining a single mean, then we use the $t$ distribution with $df=n-1$ degrees of freedom.</span>

### One sample $t$ confidence intervals {#oneSampleTConfidenceIntervals}

Dolphins are at the top of the oceanic food chain, which causes dangerous substances such as mercury to concentrate in their organs and muscles. This is an important problem for both dolphins and other animals, like humans, who occasionally eat them. For instance, this is particularly relevant in Japan where school meals have included dolphin at times.

![A Risso’s dolphin.](04/figures/rissosDolphin/rissosDolphin.jpg "fig:")\

[rissosDolphin]

Here we identify a confidence interval for the average mercury content in dolphin muscle using a sample of 19 Risso’s dolphins from the Taiji area in Japan.[^4.5] The data are summarized in Table [summaryStatsOfHgInMuscleOfRissosDolphins]. The minimum and maximum observed values can be used to evaluate whether or not there are obvious outliers or skew.

  ----- ----------- ----- --------- ---------
   $n$   $\bar{x}$   $s$   minimum   maximum
   19       4.4      2.3     1.7       9.2
  ----- ----------- ----- --------- ---------

  : Summary of mercury content in the muscle of 19 Risso’s dolphins from the Taiji area. Measurements are in $\mu$g/wet g (micrograms of mercury per wet gram of muscle).

[summaryStatsOfHgInMuscleOfRissosDolphins]

<span>Are the independence and normality conditions satisfied for this data set?</span> The observations are a simple random sample and consist of less than 10% of the population, therefore independence is reasonable. Ideally we would see a visualization of the data to check for skew and outliers. However, we can instead examine the summary statistics in Table [summaryStatsOfHgInMuscleOfRissosDolphins], which do not suggest any skew or outliers. All observations are within 2.5 standard deviations of the mean. Based on this evidence, the normality assumption seems reasonable.

In the normal model, we used $z^{\star}$ and the standard error to determine the width of a confidence interval. We revise the confidence interval formula slightly when using the $t$ distribution:

$$\begin{aligned}
\bar{x} \ \pm\  t^{\star}_{df} \times SE\end{aligned}$$

[

$t^{\star}_{df}$

\
Multiplication\
factor for\
$t$ conf. interval]

$t^{\star}_{df}$

\
Multiplication\
factor for\
$t$ conf. interval

The sample mean and estimated standard error are computed just as in our earlier examples that used the normal model ($\bar{x} = 4.4$ and $SE = s/\sqrt{n} = 0.528$). The value $t^{\star}_{df}$ is a cutoff we obtain based on the confidence level and the $t$ distribution with $df$ degrees of freedom. Before determining this cutoff, we will first need the degrees of freedom.

In our current example, we should use the $t$ distribution with $df = n - 1 = 19 - 1 = 18$ degrees of freedom. Then identifying $t_{18}^{\star}$ is similar to how we found $z^{\star}$:

-   For a 95% confidence interval, we want to find the cutoff $t^{\star}_{18}$ such that 95% of the $t$ distribution is between -$t^{\star}_{18}$ and $t^{\star}_{18}$.

-   We look in the $t$ table on page , find the column with area totaling 0.05 in the two tails (third column), and then the row with 18 degrees of freedom: $t^{\star}_{18} = 2.10$.

Generally the value of $t^{\star}_{df}$ is slightly larger than what we would get under the normal model with $z^{\star}$.

Finally, we can substitute all the values into the confidence interval equation to create the 95% confidence interval for the average mercury content in muscles from Risso’s dolphins that pass through the Taiji area:

$$\begin{aligned}
\bar{x} \ \pm\  t^{\star}_{18} \times SE
    \quad \to \quad
4.4 \ \pm\  2.10 \times 0.528
    \quad \to \quad
(3.29, 5.51)\end{aligned}$$

We are 95% confident the average mercury content of muscles in Risso’s dolphins is between 3.29 and 5.51 $\mu$g/wet gram, which is considered extremely high.

Based on a sample of $n$ independent and nearly normal observations, a confidence interval for the population mean is

$$\begin{aligned}
\bar{x} \ \pm\  t^{\star}_{df} \times SE\end{aligned}$$

where $\bar{x}$ is the sample mean, $t^{\star}_{df}$ corresponds to the confidence level and degrees of freedom, and $SE$ is the standard error as estimated by the sample. The normality condition may be relaxed for larger sample sizes.

[croakerWhiteFishPacificExerConditions] The FDA’s webpage provides some data on mercury content of fish.[^4.6] Based on a sample of 15 croaker white fish (Pacific), a sample mean and standard deviation were computed as 0.287 and 0.069 ppm (parts per million), respectively. The 15 observations ranged from 0.18 to 0.41 ppm. We will assume these observations are independent. Based on the summary statistics of the data, do you have any objections to the normality condition of the individual observations?[^4.7]

<span>Estimate the standard error of the sample mean using the data summaries in Guided Practice [croakerWhiteFishPacificExerConditions]. If we are to use the $t$ distribution to create a 90% confidence interval for the actual mean of the mercury content, identify the degrees of freedom we should use and also find $t^{\star}_{df}$.</span> [croakerWhiteFishPacificExerSEDFTStar] The standard error: $SE = \frac{0.069}{\sqrt{15}} = 0.0178$. Degrees of freedom: $df = n - 1 = 14$.

Looking in the column where two tails is 0.100 (for a 90% confidence interval) and row $df=14$, we identify $t^{\star}_{14} = 1.76$.

Using the results of Guided Practice [croakerWhiteFishPacificExerConditions] and Example [croakerWhiteFishPacificExerSEDFTStar], compute a 90% confidence interval for the average mercury content of croaker white fish (Pacific).[^4.8]

### One sample $t$ tests {#oneSampleTTests}

Is the typical US runner getting faster or slower over time? We consider this question in the context of the Cherry Blossom Run, comparing runners in 2006 and 2012. Technological advances in shoes, training, and diet might suggest runners would be faster in 2012. An opposing viewpoint might say that with the average body mass index on the rise, people tend to run slower. In fact, all of these components might be influencing run time.

The average time for all runners who finished the Cherry Blossom Run in 2006 was 93.29 minutes (93 minutes and about 17 seconds). We want to determine using data from 100 participants in the 2012 Cherry Blossom Run whether runners in this race are getting faster or slower, versus the other possibility that there has been no change.

What are appropriate hypotheses for this context?[^4.9]

The data come from a simple random sample from less than 10% of all participants, so the observations are independent. However, should we be worried about skew in the data? A histogram of the differences was shown in the left panel of Figure . [^4.10]

With independence satisfied and skew not a concern, we can proceed with performing a hypothesis test using the $t$ distribution.

The sample mean and sample standard deviation are 95.61 and 15.78 minutes, respectively. Recall that the sample size is 100. What is the p-value for the test, and what is your conclusion?[^4.11]

<span> To help us remember to use the $t$ distribution, we use a $T$ to represent the test statistic, and we often call this a **T score**. The Z score and T score are computed in the exact same way and are conceptually identical: each represents how many standard errors the observed value is from the null value.</span>

## Paired data {#pairedData}

Are textbooks actually cheaper online? Here we compare the price of textbooks at the University of California, Los Angeles’ (UCLA’s) bookstore and prices at Amazon.com. Seventy-three UCLA courses were randomly sampled in Spring 2010, representing less than 10% of all UCLA courses.[^4.12] A portion of the data set is shown in Table [textbooksDF].

             dept       course           ucla     amazon       diff
  ---------- ---------- ---------- ---------- ---------- ----------
           1 Am Ind     C170            27.67      27.95      -0.28
           2 Anthro     9               40.59      31.14       9.45
           3 Anthro     135T            31.68      32.00      -0.32
           4 Anthro     191HB           16.00      11.52       4.48
    $\vdots$ $\vdots$   $\vdots$     $\vdots$   $\vdots$   $\vdots$
          72 Wom Std    M144            23.76      18.72       5.04
          73 Wom Std    285             27.70      18.22       9.48

  : Six cases of the **textbooks** data set.

[textbooksDF]

### Paired observations

Each textbook has two corresponding prices in the data set: one for the UCLA bookstore and one for Amazon. Therefore, each textbook price from the UCLA bookstore has a natural correspondence with a textbook price from Amazon. When two sets of observations have this special correspondence, they are said to be **paired**.

<span> Two sets of observations are *paired* if each observation in one set has a special correspondence or connection with exactly one observation in the other data set.</span>

To analyze paired data, it is often useful to look at the difference in outcomes of each pair of observations. In the **textbook** data set, we look at the difference in prices, which is represented as the **diff** variable in the **textbooks** data. Here the differences are taken as

$$\begin{aligned}
\text{UCLA price} - \text{Amazon price}\end{aligned}$$

for each book. It is important that we always subtract using a consistent order; here Amazon prices are always subtracted from UCLA prices. A histogram of these differences is shown in Figure [diffInTextbookPricesS10]. Using differences between paired observations is a common and useful way to analyze paired data.

![Histogram of the difference in price for each book sampled. These data are strongly skewed.](04/figures/textbooksS10/diffInTextbookPricesS10)

[diffInTextbookPricesS10]

The first difference shown in Table [textbooksDF] is computed as $27.67-27.95=-0.28$. Verify the differences are calculated correctly for observations 2 and 3.[^4.13]

### Inference for paired data

To analyze a paired data set, we simply analyze the differences. We can use the same $t$ distribution techniques we applied in the last section.

<span>ccccc</span> $n_{_{diff}}$ &

& $\bar{x}_{_{diff}}$ &

& $s_{_{diff}}$

\
73 && 12.76 && 14.26\

[textbooksSummaryStats]

<span>Set up and implement a hypothesis test to determine whether, on average, there is a difference between Amazon’s price for a book and the UCLA bookstore’s price.</span> [htForDiffInUCLAAndAmazonTextbookPrices] We are considering two scenarios: there is no difference or there is some difference in average prices.

-   $\mu_{diff}=0$. There is no difference in the average textbook price.

-   $\mu_{diff} \neq 0$. There is a difference in average prices.

Can the $t$ distribution be used for this application? The observations are based on a simple random sample from less than 10% of all books sold at the bookstore, so independence is reasonable. While the distribution is strongly skewed, the sample is reasonably large ($n=73$), so we can proceed. Because the conditions are reasonably satisfied, we can apply the $t$ distribution to this setting.

We compute the standard error associated with $\bar{x}_{diff}$ using the standard deviation of the differences ($s_{_{diff}}=14.26$) and the number of differences ($n_{_{diff}}=73$): $$SE_{\bar{x}_{diff}} = \frac{s_{diff}}{\sqrt{n_{diff}}} = \frac{14.26}{\sqrt{73}} = 1.67$$ To visualize the p-value, the sampling distribution of $\bar{x}_{diff}$ is drawn as though $H_0$ is true, which is shown in Figure [textbooksS10HTTails]. The p-value is represented by the two (very) small tails.

To find the tail areas, we compute the test statistic, which is the T score of $\bar{x}_{diff}$ under the null condition that the actual mean difference is 0: $$T = \frac{\bar{x}_{diff} - 0}{SE_{x_{diff}}} = \frac{12.76 - 0}{1.67} = 7.59$$ The degrees of freedom are $df = 73 - 1 = 72$. If we examined Appendix , we would see that this value is larger than any in the 70 df row (we round down for $df$ when using the table), meaning the two-tailed p-value is less than 0.01. If we used statistical software, we would find the p-value is less than 1-in-10 billion! Because the p-value is less than 0.05, we reject the null hypothesis. We have found convincing evidence that Amazon is, on average, cheaper than the UCLA bookstore for UCLA course textbooks.

![Sampling distribution for the mean difference in book prices, if the true average difference is zero.](04/figures/textbooksS10/textbooksS10HTTails)

[textbooksS10HTTails]

Create a 95% confidence interval for the average price difference between books at the UCLA bookstore and books on Amazon.[^4.14]

In the textbook price example, we applied the $t$ distribution. However, as we mentioned in the last section, the $t$ distribution looks a lot like the normal distribution when the degrees of freedom are larger than about 30. In such cases, including this one, it would be reasonable to use the normal distribution in place of the $t$ distribution.

## Difference of two means {#differenceOfTwoMeans}

In this section we consider a difference in two population means, $\mu_1 - \mu_2$, under the condition that the data are not paired. Just as with a single sample, we identify conditions to ensure we can use the $t$ distribution with a point estimate of the difference, $\bar{x}_1 - \bar{x}_2$.

We apply these methods in three contexts: determining whether stem cells can improve heart function, exploring the impact of pregnant womens’ smoking habits on birth weights of newborns, and exploring whether there is statistically significant evidence that one variations of an exam is harder than another variation. This section is motivated by questions like “Is there convincing evidence that newborns from mothers who smoke have a different average birth weight than newborns from mothers who don’t smoke?”

### Confidence interval for a differences of means

Does treatment using embryonic stem cells (ESCs) help improve heart function following a heart attack? Table [summaryStatsForSheepHeartDataWhoReceivedMiceESCs] contains summary statistics for an experiment to test ESCs in sheep that had a heart attack. Each of these sheep was randomly assigned to the ESC or control group, and the change in their hearts’ pumping capacity was measured in the study. A positive value corresponds to increased pumping capacity, which generally suggests a stronger recovery. Our goal will be to identify a 95% confidence interval for the effect of ESCs on the change in heart pumping capacity relative to the control group.

A point estimate of the difference in the heart pumping variable can be found using the difference in the sample means:

$$\begin{aligned}
\bar{x}_{esc} - \bar{x}_{control}\ =\ 3.50 - (-4.33)\ =\ 7.83\end{aligned}$$

<span>l rrrrr</span>

& $n$ & $\bar{x}$ & $s$\
ESCs & 9 & 3.50 & 5.17\
control & 9 & -4.33 & 2.76\

[summaryStatsForSheepHeartDataWhoReceivedMiceESCs]

![Histograms for both the embryonic stem cell group and the control group. Higher values are associated with greater improvement. We don’t see any evidence of skew in these data; however, it is worth noting that skew would be difficult to detect with such a small sample.](04/figures/stemCellTherapyForHearts/stemCellTherapyForHearts)

[stemCellTherapyForHearts]

<span> [ConditionsForTwoSampleTDist]The $t$ distribution can be used for inference when working with the standardized difference of two means if (1) each sample meets the conditions for using the $t$ distribution and (2) the samples are independent.</span>

<span>Can the point estimate, $\bar{x}_{esc} - \bar{x}_{control} = 7.83$, be analyzed using the $t$ distribution?</span> We check the two required conditions:

1.  In this study, the sheep were independent of each other. Additionally, the distributions in Figure [stemCellTherapyForHearts] don’t show any clear deviations from normality, where we watch for prominent outliers in particular for such small samples. These findings imply each sample mean could itself be modeled using a $t$ distribution.

2.  The sheep in each group were also independent of each other.

Because both conditions are met, we can use the $t$ distribution to model the difference of the two sample means.

Before we construct a confidence interval, we must calculate the standard error of the point estimate of the difference. For this, we use the following formula, where just as before we substitute the sample standard deviations into the formula:

$$\begin{aligned}
SE_{\bar{x}_{esc} - \bar{x}_{control}}
    &= \sqrt{\frac{\sigma_{esc}^2}{n_{esc}} + \frac{\sigma_{control}^2}{n_{control}}} \\
    &\approx \sqrt{\frac{s_{esc}^2}{n_{esc}} + \frac{s_{control}^2}{n_{control}}}
    = \sqrt{\frac{5.17^2}{9} + \frac{2.76^2}{9}} = 1.95\end{aligned}$$

Because we will use the $t$ distribution, we also must identify the appropriate degrees of freedom. This can be done using computer software. An alternative technique is to use the smaller of $n_1 - 1$ and $n_2 - 1$, which is the method we will typically apply in the examples and guided practice.[^4.15]

The sample difference of two means, $\bar{x}_1 - \bar{x}_2$, can be modeled using the $t$ distribution and the standard error

$$\begin{aligned}
\textstyle
SE_{\bar{x}_{1} - \bar{x}_{2}} = \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}
\label{seOfDifferenceInMeans}\end{aligned}$$

when each sample mean can itself be modeled using a $t$ distribution and the samples are independent. To calculate the degrees of freedom, use statistical software or the smaller of $n_1 - 1$ and $n_2 - 1$.

<span>Calculate a 95% confidence interval for the effect of ESCs on the change in heart pumping capacity of sheep after they’ve suffered a heart attack.</span> We will use the sample difference and the standard error for that point estimate from our earlier calculations:

$$\begin{aligned}
& \bar{x}_{esc} - \bar{x}_{control} = 7.83 \\
& SE = \sqrt{\frac{5.17^2}{9} + \frac{2.76^2}{9}} = 1.95\end{aligned}$$

Using $df = 8$, we can identify the appropriate $t^{\star}_{df} = t^{\star}_{8}$ for a 95% confidence interval as 2.31. Finally, we can enter the values into the confidence interval formula:

$$\begin{aligned}
\text{point estimate} \ \pm\ z^{\star}SE \quad\rightarrow\quad
7.83 \ \pm\ 2.31\times 1.95 \quad\rightarrow\quad (3.38, 12.38)\end{aligned}$$

We are 95% confident that embryonic stem cells improve the heart’s pumping function in sheep that have suffered a heart attack by 3.38% to 12.38%.

### Hypothesis tests based on a difference in means

A data set called represents a random sample of 150 cases of mothers and their newborns in North Carolina over a year. Four cases from this data set are represented in Table [babySmokeDF]. We are particularly interested in two variables: **weight** and **smoke**. The **weight** variable represents the weights of the newborns and the **smoke** variable describes which mothers smoked during pregnancy. We would like to know, is there convincing evidence that newborns from mothers who smoke have a different average birth weight than newborns from mothers who don’t smoke? We will use the North Carolina sample to try to answer this question. The smoking group includes 50 cases and the nonsmoking group contains 100 cases, represented in Figure [babySmokePlotOfTwoGroupsToExamineSkew].

                   fAge       mAge      weeks     weight sexBaby    smoke
  ---------- ---------- ---------- ---------- ---------- ---------- -----------
           1         NA         13         37       5.00 female     nonsmoker
           2         NA         14         36       5.88 female     nonsmoker
           3         19         15         41       8.13 male       smoker
    $\vdots$   $\vdots$   $\vdots$   $\vdots$   $\vdots$ $\vdots$   
         150         45         50         36       9.25 female     nonsmoker

  : Four cases from the data set. The value “NA”, shown for the first two entries of the first variable, indicates that piece of data is missing.

[babySmokeDF]

![The top panel represents birth weights for infants whose mothers smoked. The bottom panel represents the birth weights for infants whose mothers who did not smoke. The distributions exhibit moderate-to-strong and strong skew, respectively.](04/figures/babySmokePlotOfTwoGroupsToExamineSkew/babySmokePlotOfTwoGroupsToExamineSkew)

[babySmokePlotOfTwoGroupsToExamineSkew]

<span>Set up appropriate hypotheses to evaluate whether there is a relationship between a mother smoking and average birth weight.</span>[babySmokeHTForWeight] The null hypothesis represents the case of no difference between the groups.

-   There is no difference in average birth weight for newborns from mothers who did and did not smoke. In statistical notation: $\mu_{n} - \mu_{s} = 0$, where $\mu_{n}$ represents non-smoking mothers and $\mu_s$ represents mothers who smoked.

-   There is some difference in average newborn weights from mothers who did and did not smoke ($\mu_{n} - \mu_{s} \neq 0$).

We check the two conditions necessary to apply the $t$ distribution to the difference in sample means. (1) Because the data come from a simple random sample and consist of less than 10% of all such cases, the observations are independent. Additionally, while each distribution is strongly skewed, the sample sizes of 50 and 100 would make it reasonable to model each mean separately using a $t$ distribution. The skew is reasonable for these sample sizes of 50 and 100. (2) The independence reasoning applied in (1) also ensures the observations in each sample are independent. Since both conditions are satisfied, the difference in sample means may be modeled using a $t$ distribution.

  ------------ ------ ------
  mean           6.78   7.18
  st. dev.       1.43   1.60
  samp. size       50    100
  ------------ ------ ------

  : Summary statistics for the data set.

[summaryStatsOfBirthWeightForNewbornsFromSmokingAndNonsmokingMothers]

The summary statistics in Table [summaryStatsOfBirthWeightForNewbornsFromSmokingAndNonsmokingMothers] may be useful for this exercise. (a) What is the point estimate of the population difference, $\mu_{n} - \mu_{s}$? (b) Compute the standard error of the point estimate from part (a).[^4.16]

<span>Draw a picture to represent the p-value for the hypothesis test from Example [babySmokeHTForWeight].</span> [pictureOfPValueForEstimateOfDiffOfMeansOfBirthWeights] To depict the p-value, we draw the distribution of the point estimate as though $H_0$ were true and shade areas representing at least as much evidence against $H_0$ as what was observed. Both tails are shaded because it is a two-sided test.

![image](04/figures/distOfDiffOfSampleMeansForBWOfBabySmokeData/distOfDiffOfSampleMeansForBWOfBabySmokeData)

<span>Compute the p-value of the hypothesis test using the figure in Example [pictureOfPValueForEstimateOfDiffOfMeansOfBirthWeights], and evaluate the hypotheses using a significance level of $\alpha=0.05$.</span> [babySmokeHTForWeightComputePValueAndEvalHT] We start by computing the T score:

$$\begin{aligned}
T = \frac{\ 0.40 - 0\ }{0.26} = 1.54\end{aligned}$$

Next, we compare this value to values in the $t$ table in Appendix , where we use the smaller of $n_n - 1 = 99$ and $n_s - 1 = 49$ as the degrees of freedom: $df = 49$. The T score falls between the first and second columns in the $df = 49$ row of the $t$ table, meaning the two-tailed p-value falls between 0.10 and 0.20 (reminder, find tail areas along the top of the table). This p-value is larger than the significance value, 0.05, so we fail to reject the null hypothesis. There is insufficient evidence to say there is a difference in average birth weight of newborns from North Carolina mothers who did smoke during pregnancy and newborns from North Carolina mothers who did not smoke during pregnancy.

Does the conclusion to Example [babySmokeHTForWeightComputePValueAndEvalHT] mean that smoking and average birth weight are unrelated?[^4.17]

[babySmokeHTIDingHowToDetectDifferences] If we made a Type 2 Error and there is a difference, what could we have done differently in data collection to be more likely to detect such a difference?[^4.18]

### Case study: two versions of a course exam

An instructor decided to run two slight variations of the same exam. Prior to passing out the exams, she shuffled the exams together to ensure each student received a random version. Summary statistics for how students performed on these two exams are shown in Table [summaryStatsForTwoVersionsOfExams]. Anticipating complaints from students who took Version B, she would like to evaluate whether the difference observed in the groups is so large that it provides convincing evidence that Version B was more difficult (on average) than Version A.

<span>l rrrrr</span> Version

& $n$ & $\bar{x}$ & $s$ & min & max\
A & 30 & 79.4 & 14 & 45 & 100\
B & 27 & 74.1 & 20 & 32 & 100\

[summaryStatsForTwoVersionsOfExams]

[htSetupForEvaluatingTwoExamVersions] Construct a hypotheses to evaluate whether the observed difference in sample means, $\bar{x}_A - \bar{x}_B=5.3$, is due to chance.[^4.19]

[conditionsForTDistForEvaluatingTwoExamVersions] To evaluate the hypotheses in Guided Practice [htSetupForEvaluatingTwoExamVersions] using the $t$ distribution, we must first verify assumptions. (a) Does it seem reasonable that the scores are independent within each group? (b) What about the normality / skew condition for observations in each group? (c) Do you think scores from the two groups would be independent of each other, i.e. the two samples are independent?[^4.20]

After verifying the conditions for each sample and confirming the samples are independent of each other, we are ready to conduct the test using the $t$ distribution. In this case, we are estimating the true difference in average test scores using the sample data, so the point estimate is $\bar{x}_A - \bar{x}_B = 5.3$. The standard error of the estimate can be calculated as

$$\begin{aligned}
SE = \sqrt{\frac{s_A^2}{n_A} + \frac{s_B^2}{n_B}} = \sqrt{\frac{14^2}{30} + \frac{20^2}{27}} = 4.62\end{aligned}$$

Finally, we construct the test statistic:

$$\begin{aligned}
T = \frac{\text{point estimate} - \text{null value}}{SE} = \frac{(79.4-74.1) - 0}{4.62} = 1.15\end{aligned}$$

If we have a computer handy, we can identify the degrees of freedom as 45.97. Otherwise we use the smaller of $n_1-1$ and $n_2-1$: $df=26$.

![The $t$ distribution with 26 degrees of freedom. The shaded right tail represents values with $T \geq 1.15$. Because it is a two-sided test, we also shade the corresponding lower tail.](04/figures/pValueOfTwoTailAreaOfExamVersionsWhereDFIs26/pValueOfTwoTailAreaOfExamVersionsWhereDFIs26)

[pValueOfTwoTailAreaOfExamVersionsWhereDFIs26]

<span>Identify the p-value using $df = 26$ and provide a conclusion in the context of the case study.</span> We examine row $df=26$ in the $t$ table. Because this value is smaller than the value in the left column, the p-value is larger than 0.200 (two tails!). Because the p-value is so large, we do not reject the null hypothesis. That is, the data do not convincingly show that one exam version is more difficult than the other, and the teacher should not be convinced that she should add points to the Version B exam scores.

### Summary for inference using the $t$ distribution

**Hypothesis tests.** When applying the $t$ distribution for a hypothesis test, we proceed as follows:

-   Write appropriate hypotheses.

-   Verify conditions for using the $t$ distribution.

    -   One-sample or differences from paired data: the observations (or differences) must be independent and nearly normal. For larger sample sizes, we can relax the nearly normal requirement, e.g. slight skew is okay or sample sizes of 15, moderate skew for sample sizes of 30, and strong skew for sample sizes of 60.

    -   For a difference of means when the data are not paired: each sample mean must separately satisfy the one-sample conditions for the $t$ distribution, and the data in the groups must also be independent.

-   Compute the point estimate of interest, the standard error, and the degrees of freedom. For $df$, use $n-1$ for one sample, and for two samples use either statistical software or the smaller of $n_1 - 1$ and $n_2 - 1$.

-   Compute the T score and p-value.

-   Make a conclusion based on the p-value, and write a conclusion in context and in plain language so anyone can understand the result.

**Confidence intervals.** Similarly, the following is how we generally computed a confidence interval using a $t$ distribution:

-   Verify conditions for using the $t$ distribution. (See above.)

-   Compute the point estimate of interest, the standard error, the degrees of freedom, and $t^{\star}_df$.

-   Calculate the confidence interval using the general formula, point estimate $\pm t_{df}^{\star} SE$.

-   Put the conclusions in context and in plain language so even non-statisticians can understand the results.

### Pooled standard deviation estimate (special topic) {#pooledStandardDeviations}

Occasionally, two populations will have standard deviations that are so similar that they can be treated as identical. For example, historical data or a well-understood biological mechanism may justify this strong assumption. In such cases, we can make the $t$ distribution approach slightly more precise by using a pooled standard deviation.

The **pooled standard deviation** of two groups is a way to use data from both samples to better estimate the standard deviation and standard error. If $s_1^{}$ and $s_2^{}$ are the standard deviations of groups 1 and 2 and there are good reasons to believe that the population standard deviations are equal, then we can obtain an improved estimate of the group variances by pooling their data:

$$\begin{aligned}
s_{pooled}^2 = \frac{s_1^2\times (n_1-1) + s_2^2\times (n_2-1)}{n_1 + n_2 - 2}\end{aligned}$$

where $n_1$ and $n_2$ are the sample sizes, as before. To use this new statistic, we substitute $s_{pooled}^2$ in place of $s_1^2$ and $s_2^2$ in the standard error formula, and we use an updated formula for the degrees of freedom:

$$\begin{aligned}
df = n_1 + n_2 - 2\end{aligned}$$

The benefits of pooling the standard deviation are realized through obtaining a better estimate of the standard deviation for each group and using a larger degrees of freedom parameter for the $t$ distribution. Both of these changes may permit a more accurate model of the sampling distribution of $\bar{x}_1 - \bar{x}_2$.

<span>Pooling standard deviations should be done only after careful research</span> <span>A pooled standard deviation is only appropriate when background research indicates the population standard deviations are nearly equal. When the sample size is large and the condition may be adequately checked with data, the benefits of pooling the standard deviations greatly diminishes.</span>

[^4.1]: See [www.cherryblossom.org](http://www.cherryblossom.org).

[^4.2]: As before, we identify the point estimate, $\bar{x} = 35.05$, and the standard error, $SE = 8.97 / \sqrt{100} = 0.897$. Next, we apply the formula for a 90% confidence interval, which uses $z^{\star} = 1.65$: $35.05 \pm 1.65\times 0.897 \to (33.57, 36.53)$. We are 90% confident that the average age of all participants in the 2012 Cherry Blossom Run is between 33.57 and 36.53 years.

[^4.3]: The standard deviation of the $t$ distribution is actually a little more than 1. However, it is useful to always think of the $t$ distribution as having a standard deviation of 1 in all of our applications.

[^4.4]: We find the shaded area *above* -1.79 (we leave the picture to you). The small left tail is between 0.025 and 0.05, so the larger upper region must have an area between 0.95 and 0.975.

[^4.5]: Taiji was featured in the movie *The Cove*, and it is a significant source of dolphin and whale meat in Japan. Thousands of dolphins pass through the Taiji area annually, and we will assume these 19 dolphins represent a simple random sample from those dolphins. Data reference: Endo T and Haraguchi K. 2009. High mercury levels in hair samples from residents of Taiji, a Japanese whaling town. Marine Pollution Bulletin 60(5):743-747.

[^4.6]: http://www.fda.gov/food/foodborneillnesscontaminants/metals/ucm115644.htm

[^4.7]: There are no obvious outliers; all observations are within 2 standard deviations of the mean. If there is skew, it is not evident. There are no red flags for the normal model based on this (limited) information, and we do not have reason to believe the mercury content is not nearly normal in this type of fish.

[^4.8]: $\bar{x} \ \pm\ t^{\star}_{14} \times SE \ \to\  0.287 \ \pm\  1.76\times 0.0178\ \to\ (0.256, 0.318)$. We are 90% confident that the average mercury content of croaker white fish (Pacific) is between 0.256 and 0.318 ppm.

[^4.9]: $H_0$: The average 10 mile run time was the same for 2006 and 2012. $\mu = 93.29$ minutes. $H_A$: The average 10 mile run time for 2012 was *different* than that of 2006. $\mu \neq 93.29$ minutes.

[^4.10]: With a sample of 100, we should only be concerned if there is extreme skew. The histogram of the data suggest, at worst, slight skew.

[^4.11]: With the conditions satisfied for the $t$ distribution, we can compute the standard error ($SE = 15.78 / \sqrt{100} = 1.58$ and the *T score*: $T = \frac{95.61 - 93.29}{1.58} = 1.47$. (There is more on this after the guided practice, but a T score and Z score are basically the same thing.) For $df = 100 - 1 = 99$, we would find $T = 1.47$ to fall between the first and second column, which means the p-value is between 0.05 and 0.10 (use $df = 90$ and consider two tails since the test is two-sided). Because the p-value is greater than 0.05, we do not reject the null hypothesis. That is, the data do not provide strong evidence that the average run time for the Cherry Blossom Run in 2012 is any different than the 2006 average.

[^4.12]: When a class had multiple books, only the most expensive text was considered.

[^4.13]: Observation 2: $40.59 - 31.14 = 9.45$. Observation 3: $31.68 - 32.00 = -0.32$.

[^4.14]: Conditions have already verified and the standard error computed in Example [htForDiffInUCLAAndAmazonTextbookPrices]. To find the interval, identify $t^{\star}_{72}$ (use $df=70$ in the table, $t^{\star}_{70} = 1.99$) and plug it, the point estimate, and the standard error into the confidence interval formula: $$\text{point estimate} \ \pm\ z^{\star}SE \quad\to\quad 12.76 \ \pm\ 1.99\times 1.67 \quad\to\quad (9.44, 16.08)$$ We are 95% confident that Amazon is, on average, between \$9.44 and \$16.08 cheaper than the UCLA bookstore for UCLA course books.

[^4.15]: This technique for degrees of freedom is conservative with respect to a Type 1 Error; it is more difficult to reject the null hypothesis using this $df$ method. In this example, computer software would have provided us a more precise degrees of freedom of $df = 12.225$.

[^4.16]: (a) The difference in sample means is an appropriate point estimate: $\bar{x}_{n} - \bar{x}_{s} = 0.40$. (b) The standard error of the estimate can be estimated using Equation ([seOfDifferenceInMeans]):

    $$\begin{aligned}
    SE = \sqrt{\frac{\sigma_n^2}{n_n} + \frac{\sigma_s^2}{n_s}}
        \approx \sqrt{\frac{s_n^2}{n_n} + \frac{s_s^2}{n_s}}
        = \sqrt{\frac{1.60^2}{100} + \frac{1.43^2}{50}}
        = 0.26\end{aligned}$$

[^4.17]: Absolutely not. It is possible that there is some difference but we did not detect it. If there is a difference, we made a Type 2 Error. Notice: we also don’t have enough information to, if there is an actual difference difference, confidently say which direction that difference would be in.

[^4.18]: We could have collected more data. If the sample sizes are larger, we tend to have a better shot at finding a difference if one exists.

[^4.19]: Because the teacher did not expect one exam to be more difficult prior to examining the test results, she should use a two-sided hypothesis test. $H_0$: the exams are equally difficult, on average. $\mu_A - \mu_B = 0$. $H_A$: one exam was more difficult than the other, on average. $\mu_A - \mu_B \neq 0$.

[^4.20]: \(a) It is probably reasonable to conclude the scores are independent, provided there was no cheating. (b) The summary statistics suggest the data are roughly symmetric about the mean, and it doesn’t seem unreasonable to suggest the data might be normal. Note that since these samples are each nearing 30, moderate skew in the data would be acceptable. (c) It seems reasonable to suppose that the samples are independent since the exams were handed out randomly.

-->

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sampling-and-estimation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="inferenceForNumericalDataANOVA.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/CrumpLab/statistics/blob/master/06-ttests.Rmd",
"text": "Edit"
},
"download": ["statistics.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
